DROP TABLE IF EXISTS core_alignments;

CREATE TABLE core_alignments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    abbreviation TEXT NOT NULL UNIQUE,
    alignment_order TEXT NOT NULL,
    alignment_morality TEXT NOT NULL,
    description TEXT
);

-- Inserção dos atributos padrão de D&D 5e
INSERT INTO core_alignments (name, abbreviation, alignment_order, alignment_morality, description) VALUES
('Lawful Good','LG','Lawful','Good','A Lawful Good character acts as a model citizen, upholding the law and order to create a better society for everyone. They combine a strong sense of honor and duty with compassion, always striving to do what is right and just, even if it means personal sacrifice. They believe a well-ordered society is the best way to protect the innocent and ensure a high quality of life.'),
('Neutral Good','NG','Neutral','Good','A Neutral Good character prioritizes doing good and helping others, but does so without a rigid adherence to law or a total disregard for it. They are driven by their conscience and personal sense of compassion, rather than by codes or traditions. They will cooperate with lawful authorities or work independently, choosing the best path to achieve a good outcome, regardless of the rules.'),
('Chaotic Good','CG','Chaotic','Good','A Chaotic Good character follows their own moral compass, guided by a strong belief in individual freedom and benevolence. They detest tyranny and oppressive laws, often acting on instinct to help others and fight injustice. While their methods may seem unpredictable or unorthodox, their heart is in the right place. They value individual liberty above all else, seeing rigid laws as potential tools of oppression.'),
('Lawful Neutral','LN','Lawful','Neutral','A Lawful Neutral character lives by a code, whether it be a personal creed, a religious doctrine, or a legal system. Order is their paramount concern, not morality. They follow the rules to the letter and believe in a strict, predictable system above all. They may enforce the law without mercy or emotion, seeing it as the only way to prevent chaos and maintain stability.'),
('True Neutral','TN','Neutral','Neutral','A True Neutral character is driven by a deep sense of balance and indifference to moral extremes. They avoid taking sides in conflicts between good and evil, law and chaos, viewing all as natural forces. They are pragmatic and will often act in their own best interest, but will intervene to prevent any single force from becoming too dominant. Their motto is often "Live and let live."'),
('Chaotic Neutral','CN','Chaotic','Neutral','A Chaotic Neutral character is the ultimate individualist, acting on a whim and valuing their own freedom above all. They don''t have a strong moral or ethical compass and are highly unpredictable. They are neither maliciously evil nor sacrificially good; they simply act as they please. Their actions are often driven by personal freedom and a desire to escape societal constraints.'),
('Lawful Evil','LE','Lawful','Evil','A Lawful Evil character is a methodical and calculating villain who uses a code, law, or hierarchy to achieve their selfish goals. They believe in the power of structure and organization, often creating their own systems to dominate others. They are reliable to their allies as long as their mutual interests align, but they are ruthless and ambitious, willing to exploit any rule or loophole to gain power. They see good as a weakness and chaos as a liability.'),
('Neutral Evil','NE','Neutral','Evil','A Neutral Evil character is primarily self-interested and acts with malice for personal gain, without a strong preference for order or chaos. They are opportunistic and will use any means necessary to get what they want, whether it involves breaking laws or following them. They are pragmatic villains who don''t care about moral debates; they simply want power, wealth, or personal pleasure, and they will take it at the expense of others.'),
('Chaotic Evil','CE','Chaotic','Evil','A Chaotic Evil character is driven by a desire for destruction, selfishness, and an utter disregard for any form of order. They act on impulse, taking pleasure in others'' suffering and seeking to sow discord and misery wherever they go. They are unpredictable, have no respect for life, and see rules as a joke. Their actions are motivated by pure, unadulterated evil and a desire to watch the world burn.');
