-- =============================================
-- SISTEMA DE TRINKETS COMPLETO - D&D 5E
-- =============================================
-- Schema completo com TODOS os trinkets (695 total)
-- Estrutura otimizada com suporte a ranges de dados

-- ================================================================================================
-- TRINKET CATEGORIES - Categorias de trinkets por livro e região
-- ================================================================================================

CREATE TABLE IF NOT EXISTS item_trinket_categories (
    trinket_category_id INTEGER PRIMARY KEY,
    book_id INTEGER NOT NULL,
    category_name TEXT NOT NULL UNIQUE,
    category_description TEXT,
    dice_type TEXT NOT NULL, -- 'd100', 'd8', etc.
    
    FOREIGN KEY (book_id) REFERENCES core_books(book_id)
);

-- ================================================================================================
-- TRINKETS - Trinkets individuais (ESTRUTURA OTIMIZADA)
-- ================================================================================================

CREATE TABLE IF NOT EXISTS item_trinkets (
    trinket_id INTEGER PRIMARY KEY AUTOINCREMENT,
    trinket_category_id INTEGER NOT NULL,
    dice_min INTEGER NOT NULL,     -- Valor mínimo do dado (ex: 1 em "1-2")
    dice_max INTEGER NOT NULL,     -- Valor máximo do dado (ex: 2 em "1-2")
    description TEXT NOT NULL,     -- Apenas descrição (sem nome redundante)
    
    FOREIGN KEY (trinket_category_id) REFERENCES item_trinket_categories(trinket_category_id)
);

-- ================================================================================================
-- ÍNDICES PARA PERFORMANCE
-- ================================================================================================

CREATE INDEX IF NOT EXISTS idx_trinkets_category ON item_trinkets(trinket_category_id);
CREATE INDEX IF NOT EXISTS idx_trinkets_dice_range ON item_trinkets(trinket_category_id, dice_min, dice_max);

-- ================================================================================================
-- DADOS DAS CATEGORIAS (ESTRUTURA OTIMIZADA)
-- ================================================================================================

INSERT OR IGNORE INTO item_trinket_categories VALUES
(1, 1, 'Standard Trinkets', 'General trinkets from the Player''s Handbook', 'd100'),
(2, 14, 'Elemental Evil Trinkets', 'Trinkets with elemental themes', 'd100'),
(3, 12, 'Gothic Horror Trinkets', 'Dark and mysterious trinkets from Curse of Strahd', 'd100'),
(4, 6, 'Elven Trinkets', 'Trinkets with elven heritage from Mordenkainen''s Tome of Foes', 'd8'),
(5, 5, 'Trinkets from Aerenal', 'Trinkets from the elven continent of Aerenal', 'd8'),
(6, 8, 'Kwalish Trinkets', 'Mechanical and strange trinkets from Kwalish''s laboratory', 'd100'),
(7, 7, 'Corporate Trinkets', 'Business-themed trinkets from Acquisitions Incorporated', 'd100'),
(8, 9, 'Icewind Dale Trinkets', 'Cold-themed trinkets from the frozen north', 'd100'),
(9, 10, 'Horror Trinkets', 'Terrifying trinkets from Van Richten''s Guide', 'd100'),
(10, 11, 'Trinkets from the Frostfell and Everice', 'Feywild trinkets from The Wild Beyond The Witchlight', 'd100'),
(11, 5, 'Trinkets from Xen''drik', 'Ancient trinkets from the ruined continent', 'd8'),
(12, 5, 'Trinkets from the Mournland', 'Corrupted trinkets from Eberron''s devastated region', 'd8'),
(13, 5, 'Trinkets from Sarlona', 'Exotic trinkets from the distant continent', 'd8'),
(14, 5, 'Trinkets from Argonnessen', 'Draconic trinkets from the dragon continent', 'd8'),
(15, 5, 'Trinkets from the Lhazaar Principalities', 'Pirate-themed trinkets from island nations', 'd8'),
(16, 5, 'Trinkets from the Shadow Marches', 'Mysterious trinkets from the marshlands', 'd8');

-- ================================================================================================
-- TODOS OS TRINKETS - DADOS COMPLETOS (695 TRINKETS)
-- ================================================================================================
-- Dados extraídos automaticamente do HTML oficial

-- Standard Trinkets (d100) - 105 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(1, 1, 1, 'A mummified goblin hand'),
(1, 1, 1, 'A mummified goblin hand'),
(1, 2, 2, 'A piece of crystal that faintly glows in the moonlight'),
(1, 2, 2, 'A piece of crystal that faintly glows in the moonlight'),
(1, 3, 3, 'A gold coin minted in an unknown land'),
(1, 3, 3, 'A gold coin minted in an unknown land'),
(1, 4, 4, 'A diary written in a language you don''t know'),
(1, 4, 4, 'A diary written in a language you don''t know'),
(1, 5, 5, 'A brass ring that never tarnishes'),
(1, 5, 5, 'A brass ring that never tarnishes'),
(1, 6, 6, 'An old chess piece made from glass'),
(1, 7, 7, 'A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips'),
(1, 8, 8, 'A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it'),
(1, 9, 9, 'A rope necklace from which dangles four mummified elf fingers'),
(1, 10, 10, 'The deed for a parcel of land in a realm unknown to you'),
(1, 11, 11, 'A 1-ounce block made from an unknown material'),
(1, 12, 12, 'A small cloth doll skewered with needles'),
(1, 13, 13, 'A tooth from an unknown beast'),
(1, 14, 14, 'An enormous scale, perhaps from a dragon'),
(1, 15, 15, 'A bright green feather'),
(1, 16, 16, 'An old divination card bearing your likeness'),
(1, 17, 17, 'A glass orb filled with moving smoke'),
(1, 18, 18, 'A 1-pound egg with a bright red shell'),
(1, 19, 19, 'A pipe that blows bubbles'),
(1, 20, 20, 'A glass jar containing a weird bit of flesh floating in pickling fluid'),
(1, 21, 21, 'A tiny gnome-crafted music box that plays a song you dimly remember from your childhood'),
(1, 22, 22, 'A small wooden statuette of a smug halfling'),
(1, 23, 23, 'A brass orb etched with strange runes'),
(1, 24, 24, 'A multicolored stone disk'),
(1, 25, 25, 'A tiny silver icon of a raven'),
(1, 26, 26, 'A bag containing forty-seven humanoid teeth, one of which is rotten'),
(1, 27, 27, 'A shard of obsidian that always feels warm to the touch'),
(1, 28, 28, 'A dragon''s bony talon hanging from a plain leather necklace'),
(1, 29, 29, 'A pair of old socks'),
(1, 30, 30, 'A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking'),
(1, 31, 31, 'A silver badge in the shape of a five-pointed star'),
(1, 32, 32, 'A knife that belonged to a relative'),
(1, 33, 33, 'A glass vial filled with nail clippings'),
(1, 34, 34, 'A rectangular metal device with two tiny metal cups on one end that throws sparks when wet'),
(1, 35, 35, 'A white, sequined glove sized for a human'),
(1, 36, 36, 'A vest with one hundred tiny pockets'),
(1, 37, 37, 'A small, weightless stone block'),
(1, 38, 38, 'A tiny sketch portrait of a goblin'),
(1, 39, 39, 'An empty glass vial that smells of perfume when opened'),
(1, 40, 40, 'A gemstone that looks like a lump of coal when examined by anyone but you'),
(1, 41, 41, 'A scrap of cloth from an old banner'),
(1, 42, 42, 'A rank insignia from a lost legionnaire'),
(1, 43, 43, 'A tiny silver bell without a clapper'),
(1, 44, 44, 'A mechanical canary inside a gnomish lamp'),
(1, 45, 45, 'A tiny chest carved to look like it has numerous feet on the bottom'),
(1, 46, 46, 'A dead sprite inside a clear glass bottle'),
(1, 47, 47, 'A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)'),
(1, 48, 48, 'A glass orb filled with water, in which swims a clockwork goldfish'),
(1, 49, 49, 'A silver spoon with an ''M'' engraved on the handle'),
(1, 50, 50, 'A whistle made from gold-colored wood'),
(1, 51, 51, 'A dead scarab beetle the size of your hand'),
(1, 52, 52, 'Two toy soldiers, one with a missing head'),
(1, 53, 53, 'A small box filled with different-sized buttons'),
(1, 54, 54, 'A candle that can''t be lit'),
(1, 55, 55, 'A tiny cage with no door'),
(1, 56, 56, 'An old key'),
(1, 57, 57, 'An indecipherable treasure map'),
(1, 58, 58, 'A hilt from a broken sword'),
(1, 59, 59, 'A rabbit''s foot'),
(1, 60, 60, 'A glass eye'),
(1, 61, 61, 'A cameo carved in the likeness of a hideous person'),
(1, 62, 62, 'A silver skull the size of a coin'),
(1, 63, 63, 'An alabaster mask'),
(1, 64, 64, 'A pyramid of sticky black incense that smells very bad'),
(1, 65, 65, 'A nightcap that, when worn, gives you pleasant dreams'),
(1, 66, 66, 'A single caltrop made from bone'),
(1, 67, 67, 'A gold monocle frame without the lens'),
(1, 68, 68, 'A 1-inch cube, each side painted a different color'),
(1, 69, 69, 'A crystal knob from a door'),
(1, 70, 70, 'A small packet filled with pink dust'),
(1, 71, 71, 'A fragment of a beautiful song, written as musical notes on two pieces of parchment'),
(1, 72, 72, 'A silver teardrop earring made from a real teardrop'),
(1, 73, 73, 'The shell of an egg painted with scenes of human misery in disturbing detail'),
(1, 74, 74, 'A fan that, when unfolded, shows a sleeping cat'),
(1, 75, 75, 'A set of bone pipes'),
(1, 76, 76, 'A four-leaf clover pressed inside a book discussing manners and etiquette'),
(1, 77, 77, 'A sheet of parchment upon which is drawn a complex mechanical contraption'),
(1, 78, 78, 'An ornate scabbard that fits no blade you have found so far'),
(1, 79, 79, 'An invitation to a party where a murder happened'),
(1, 80, 80, 'A bronze pentacle with an etching of a rat''s head in its center'),
(1, 81, 81, 'A purple handkerchief embroidered with the name of a powerful archmage'),
(1, 82, 82, 'Half of a floorplan for a temple, castle, or some other structure'),
(1, 83, 83, 'A bit of folded cloth that, when unfolded, turns into a stylish cap'),
(1, 84, 84, 'A receipt of deposit at a bank in a far-flung city'),
(1, 85, 85, 'A diary with seven missing pages'),
(1, 86, 86, 'An empty silver snuffbox bearing an inscription on the surface that says "dreams"'),
(1, 87, 87, 'An iron holy symbol devoted to an unknown god'),
(1, 88, 88, 'A book that tells the story of a legendary hero''s rise and fall, with the last chapter missing'),
(1, 89, 89, 'A vial of dragon blood'),
(1, 90, 90, 'An ancient arrow of elven design'),
(1, 91, 91, 'A needle that never bends'),
(1, 92, 92, 'An ornate brooch of dwarven design'),
(1, 93, 93, 'An empty wine bottle bearing a pretty label that says, "The Wizard of Wines Winery, Red Dragon Crush, 331422-W"'),
(1, 94, 94, 'A mosaic tile with a multicolored, glazed surface'),
(1, 95, 95, 'A petrified mouse'),
(1, 96, 96, 'A black pirate flag adorned with a dragon''s skull and crossbones'),
(1, 97, 97, 'A tiny mechanical crab or spider that moves about when it''s not being observed'),
(1, 98, 98, 'A glass jar containing lard with a label that reads, "Griffon Grease"'),
(1, 99, 99, 'A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body'),
(1, 100, 100, 'A metal urn containing the ashes of a hero');

-- Elemental Evil Trinkets (d100) - 100 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(2, 1, 1, 'A compass that always points to Mulmaster.'),
(2, 2, 2, 'A paper fan that won''t produce a breeze no matter how hard it''s waved.'),
(2, 3, 3, 'A petrified potato that resembles someone important to you.'),
(2, 4, 4, 'A glass cup that can only be filled half way no matter how much liquid is poured into it.'),
(2, 5, 5, 'A mirror that only shows the back of your head.'),
(2, 6, 6, 'A small glass bird that when set down near water dips its head in as if to get a drink.'),
(2, 7, 7, 'A lady''s coin purse containing two sharp fangs.'),
(2, 8, 8, 'A small sea conch with the words "From the beginning" painted on the lip.'),
(2, 9, 9, 'A frost-covered silver locket that''s frozen shut.'),
(2, 10, 10, 'A seal which imprints a mysterious, unknown coat of arms into hard rock.'),
(2, 11, 11, 'A small wooden doll that when held brings back fond memories.'),
(2, 12, 12, 'A small handmirror which only reflects inanimate objects.'),
(2, 13, 13, 'A glass eyeball that looks about of its own accordance, and can roll around.'),
(2, 14, 14, 'A glass orb that replicates yesterday''s weather inside itself.'),
(2, 15, 15, 'A drinking cup that randomly fills with fresh or saltwater. Refilling once emptied.'),
(2, 16, 16, 'A deep blue piece of flint, that when struck with steel produces not a spark but a drop of water.'),
(2, 17, 17, 'A conch shell which is always damp and constantly drips saltwater.'),
(2, 18, 18, 'A charred, half-melted pewter clasp that glows as if smoldering but releases no heat.'),
(2, 19, 19, 'A clockwork finch that flaps its wings in the presence of a breeze.'),
(2, 20, 20, 'An unbreakable sealed jar of glowing water that hums when shaken.'),
(2, 21, 21, 'A small, finely polished geode whose crystals slowly fade between every color of the spectrum.'),
(2, 22, 22, 'A rough stone eye pulled from a petrified creature.'),
(2, 23, 23, 'A stone smoking pipe that never needs lighting.'),
(2, 24, 24, 'A small whistle, that when blown, whispers a name of a person or place unknown to you, instead of the whistle sound.'),
(2, 25, 25, 'A fist sized rock that "beats" like a heart.'),
(2, 26, 26, 'A pair of bronze scissors in the shape of a pair of leaping dolphins.'),
(2, 27, 27, 'A bronze oil lamp which is rumored to have once held a genie.'),
(2, 28, 28, 'A single gauntlet inscribed with a fire motif and an unfamiliar name in Primordial.'),
(2, 29, 29, 'A one-eyed little fish inside a spherical vial, much bigger than the vial''s neck. He has a cunning look.'),
(2, 30, 30, 'The tiny skull of a rabbit that whispers scathing insults when nobody is looking.'),
(2, 31, 31, 'A rag doll in the likeness of an owlbear.'),
(2, 32, 32, 'The desiccated body of a small eight-legged black lizard.'),
(2, 33, 33, 'A small toy boat made with a walnut shell, toothpick, and piece of cloth.'),
(2, 34, 34, 'A small pocket mirror that slowly fogs over while held.'),
(2, 35, 35, 'Wind chimes that glow when the wind blows.'),
(2, 36, 36, 'A small, clay square with an unknown rune etched into one side.'),
(2, 37, 37, 'A tea kettle that heats itself when filled with water.'),
(2, 38, 38, 'An old scratched monocle which shows an underwater landscape whenever someone looks through it.'),
(2, 39, 39, 'A rose carved from coral.'),
(2, 40, 40, 'A set of dice with elemental symbols and primordial runes instead of pips or numbers.'),
(2, 41, 41, 'An amulet filled with liquid that churns, freezes, or boils to match its wearer''s mood.'),
(2, 42, 42, 'A small silver bell that makes a sound like quiet, distant thunder when it''s struck.'),
(2, 43, 43, 'A small vial of black sand that glows slightly in the moonlight.'),
(2, 44, 44, 'A small whale tooth with etched with an image of waves crashing upon a beach.'),
(2, 45, 45, 'An hourglass in which the sands pour upward instead of downward.'),
(2, 46, 46, 'A glass pendant with a hole in the center that a mild breeze always blows out of.'),
(2, 47, 47, 'A soft feather that falls like a stone when dropped.'),
(2, 48, 48, 'A large transparent gem that, when gripped tightly, whispers in Terran.'),
(2, 49, 49, 'A small crystal snowglobe that, when shaken, seems to form silhouettes of dancing forms.'),
(2, 50, 50, 'Half of a palm-sized geode that pulses dimly with purple light.'),
(2, 51, 51, 'A book filled with writing that only appears when the book is held underwater.'),
(2, 52, 52, 'A sealed envelope made of red leather that you haven’t been able to open. It smells of campfire.'),
(2, 53, 53, 'A locket of hair that is rumored to have come from a famed fire genasi.'),
(2, 54, 54, 'Flint and steel that, when used to start a fire, creates a random colored flame.'),
(2, 55, 55, 'A blank piece of wet parchment that never seems to dry.'),
(2, 56, 56, 'A small puzzle box made of brass, that is slightly warm to the touch.'),
(2, 57, 57, 'A cloudy chunk of glass that is said to hold a spark of breath from a blue dragon.'),
(2, 58, 58, 'A crude chalice made of coal.'),
(2, 59, 59, 'A miniature brass horn, silent when played, but fills the air with the scent of warm and exotic spices.'),
(2, 60, 60, 'An eye-sized blue pearl that floats in salt water.'),
(2, 61, 61, 'A tuning fork made from a dark metal which glows with a pale, white light during thunderstorms.'),
(2, 62, 62, 'A small vial that is always filled with the smell of autumn wind.'),
(2, 63, 63, 'A clear marble that slowly rolls toward the nearest source of running water.'),
(2, 64, 64, 'A small collapsible silver cup that perspires constantly when opened.'),
(2, 65, 65, 'An hourglass that tells time with falling mist instead of sand.'),
(2, 66, 66, 'An ornate razor, which only cuts in freezing cold temperature.'),
(2, 67, 67, 'A shark tooth covered in tiny etched words from a lost language.'),
(2, 68, 68, 'A large brass coin with no markings or images on it.'),
(2, 69, 69, 'A small wooden box filled with a strange red clay.'),
(2, 70, 70, 'A necklace with a small, rusted iron anchor.'),
(2, 71, 71, 'A small brass flute adorned with silver wire that is always faintly sounding.'),
(2, 72, 72, 'A red and black Aarakocra feather.'),
(2, 73, 73, 'A palm-sized stone with a hole in it, through which can be heard a constantly whispering wind.'),
(2, 74, 74, 'A small conch shell covered in black crystal.'),
(2, 75, 75, 'A small music box made of brass. It features a pair of tiny automatons that resemble Azer working at a forge.'),
(2, 76, 76, 'A glass jar containing the preserved corpse of an unfamiliar aquatic creature.'),
(2, 77, 77, 'A piece of petrified wood carved into the shape of a seashell.'),
(2, 78, 78, 'A wooden puzzle cube covered in elemental symbols.'),
(2, 79, 79, 'A small stone cube that acts as a magnet when placed against another stone.'),
(2, 80, 80, 'A ring made of a white metal. On the inside is a name etched in Auran.'),
(2, 81, 81, 'A bracelet made of silvered fish hooks.'),
(2, 82, 82, 'A journal filled with poetry hand-written in Primordial.'),
(2, 83, 83, 'A yellow gemstone that glows dimly when a storm is nearby.'),
(2, 84, 84, 'A charred chisel with an unfamiliar symbol stamped into its base.'),
(2, 85, 85, 'A canteen filled with a foul smelling orange mud.'),
(2, 86, 86, 'A faceless doll made of driftwood.'),
(2, 87, 87, 'A heavy iron key bearing the name of a ship long lost to the sea.'),
(2, 88, 88, 'A small jewelry box made from the shell of a turtle.'),
(2, 89, 89, 'A chess piece fashioned to look like fire myrmidon.'),
(2, 90, 90, 'A spinning top with an image of one of the four elements on each side.'),
(2, 91, 91, 'A single hoop earring made of a porous red stone.'),
(2, 92, 92, 'An arrowhead carved from seasalt.'),
(2, 93, 93, 'A small comb made of blue coral.'),
(2, 94, 94, 'Seven small beads of sandstone on a string, all different colors.'),
(2, 95, 95, 'A romance chapbook written in Undercommon titled "Just one Layer of Grey".'),
(2, 96, 96, 'A tiny, broken clockwork Harpy.'),
(2, 97, 97, 'An ivory whale statuette.'),
(2, 98, 98, 'A fist-sized cog, covered in barnacles.'),
(2, 99, 99, 'An eyepatch made of obsidian and a black leather cord.'),
(2, 100, 100, 'A glass bottle with a tiny ship of unfamiliar design inside.');

-- Gothic Horror Trinkets (d100) - 53 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(3, 1, 2, 'A picture you drew as a child of your imaginary friend'),
(3, 1, 2, 'A picture you drew as a child of your imaginary friend'),
(3, 3, 4, 'A lock that opens when blood is dripped in its keyhole'),
(3, 3, 4, 'A lock that opens when blood is dripped in its keyhole'),
(3, 5, 6, 'Clothes stolen from a scarecrow'),
(3, 5, 6, 'Clothes stolen from a scarecrow'),
(3, 7, 8, 'A spinning top carved with four faces: happy, sad, wrathful, and dead'),
(3, 9, 10, 'The necklace of a sibling who died on the day you were born'),
(3, 11, 12, 'A wig from someone executed by beheading'),
(3, 13, 14, 'The unopened letter to you from your dying father'),
(3, 15, 16, 'A pocket watch that runs backward for an hour every midnight'),
(3, 17, 18, 'A winter coat stolen from a dying soldier'),
(3, 19, 20, 'A bottle of invisible ink that can only be read at sunset'),
(3, 21, 22, 'A wineskin that refills when interred with a dead person for a night'),
(3, 23, 34, 'A set of silverware used by a king for his last meal'),
(3, 25, 26, 'A spyglass that always shows the world suffering a terrible storm'),
(3, 27, 28, 'A cameo with the profile''s face scratched away'),
(3, 29, 30, 'A lantern with a black candle that never runs out and that burns with green flame'),
(3, 31, 32, 'A teacup from a child''s tea set, stained with blood'),
(3, 33, 34, 'A little black book that records your dreams, and yours alone, when you sleep'),
(3, 35, 36, 'A necklace formed of the interlinked holy symbols of a dozen deities'),
(3, 37, 38, 'A hangman''s noose that feels heavier than it should'),
(3, 39, 40, 'A birdcage into which small birds fly but once inside never eat or leave'),
(3, 41, 42, 'A lepidopterist''s box filled dead moths with skulllike patterns on their wings'),
(3, 43, 44, 'A jar of pickled ghouls'' tongues'),
(3, 45, 56, 'The wooden hand of a notorious pirate'),
(3, 47, 48, 'An urn with the ashes of a dead relative'),
(3, 49, 50, 'A hand mirror backed with a bronze depiction of a medusa'),
(3, 51, 52, 'Pallid leather gloves crafted with ivory fingernails'),
(3, 53, 54, 'Dice made from the knuckles of a notorious charlatan'),
(3, 55, 56, 'A ring of keys for forgotten locks'),
(3, 57, 58, 'Nails from the coffin of a murderer'),
(3, 59, 60, 'A key to the family crypt'),
(3, 61, 62, 'A bouquet of funerary flowers that always looks and smells fresh'),
(3, 63, 64, 'A switch used to discipline you as a child'),
(3, 65, 66, 'A music box that plays by itself whenever someone holding it dances'),
(3, 67, 68, 'A walking cane with an iron ferrule that strikes sparks on stone'),
(3, 69, 70, 'A flag from a ship lost at sea'),
(3, 71, 72, 'Porcelain doll''s head that always seems to be looking at you'),
(3, 73, 74, 'A wolf''s head wrought in silver that is also a whistle'),
(3, 75, 76, 'A small mirror that shows a much older version of the viewer'),
(3, 77, 78, 'Small, worn book of children''s nursery rhymes'),
(3, 79, 80, 'A mummified raven claw'),
(3, 81, 82, 'A broken pendent of a silver dragon that''s always cold to the touch'),
(3, 83, 84, 'A small locked box that quietly hums a lovely melody at night but you always forget it in the morning'),
(3, 85, 86, 'An inkwell that makes one a little nauseous when staring at it'),
(3, 87, 88, 'An old little doll made from a dark, dense wood and missing a hand and a foot'),
(3, 89, 90, 'A black executioner''s hood'),
(3, 91, 92, 'A pouch made of flesh, with a sinew drawstring'),
(3, 93, 94, 'A tiny spool of black thread that never runs out'),
(3, 95, 96, 'A tiny clockwork figurine of a dancer that''s missing a gear and doesn''t work'),
(3, 97, 98, 'A black wooden pipe that creates puffs of smoke that look like skulls'),
(3, 99, 100, 'A vial of perfume, the scent of which only certain creatures can detect');

-- Elven Trinkets (d8) - 10 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(4, 1, 1, 'A small notebook that causes anything written in it to disappear after 1 hour'),
(4, 1, 1, 'A small notebook that causes anything written in it to disappear after 1 hour'),
(4, 2, 2, 'A crystal lens made of ivory and gold that causes anything observed through it to appear to be surrounded by motes of multicolored light'),
(4, 2, 2, 'A crystal lens made of ivory and gold that causes anything observed through it to appear to be surrounded by motes of multicolored light'),
(4, 3, 3, 'A small golden pyramid inscribed with elven symbols and about the size of a walnut'),
(4, 4, 4, 'A cloak pin made from enamel in the shape of a butterfly; when you take the pin off, it turns into a real butterfly, and returns when you are ready to put your cloak back on again'),
(4, 5, 5, 'A golden compass that points toward the nearest portal to the Feywild within 10 miles'),
(4, 6, 6, 'A small silver spinning top that, when spun, endlessly spins until interrupted'),
(4, 7, 7, 'A small songbird made of enamel, gold wire, and precious stone; uttering the songbird''s name in Elvish causes the trinket to emit that bird''s birdsong'),
(4, 8, 8, 'A small enamel flower that, when put in one''s hair, animates, tying back the wearer''s hair with a living vine with flowers; plucking a single flower from this vine returns it to its inanimate form');

-- Trinkets from Aerenal (d8) - 8 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(5, 1, 1, 'A bronzewood ring inscribed with the Elvish word for "hope"'),
(5, 2, 2, 'A dried flower; if it''s placed in water, it blooms'),
(5, 3, 3, 'An ebony locket; when it''s opened, an elven voice whispers "Always"'),
(5, 4, 4, 'A tiny skull carved from dark wood'),
(5, 5, 5, 'A tiny skull carved from dark wood'),
(5, 6, 6, 'An ivory flute which produces no sound'),
(5, 7, 7, 'A small journal made from preserved leaves'),
(5, 8, 8, 'A small journal made from preserved leaves');

-- Kwalish Trinkets (d100) - 50 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(6, 1, 2, 'A handheld device containing a glowing green gem that darkens when no oxygen is present'),
(6, 3, 4, 'A foot-long, egg-shaped object made from stitched leather'),
(6, 5, 6, 'A black metal cylinder that dictates the history of an unknown plant or animal species when held'),
(6, 7, 8, 'A cylindrical jar containing a pickled crustacean of unknown origin'),
(6, 9, 10, 'A small thumb-button storage cylinder that releases a useless iron key when pressed'),
(6, 11, 12, 'An unusual heraldic cloak pin that emits a short musical fanfare when tapped'),
(6, 13, 14, 'A handheld tube that sucks in dust when squeezed and captures it in a detachable compartment'),
(6, 15, 16, 'A scintillating disk of unknown material'),
(6, 17, 18, 'A dial that can be twisted to slowly click back to its origin, whereupon it emits a loud ringing noise'),
(6, 19, 20, 'A hovering, apple-sized orb of metal that follows you around'),
(6, 21, 22, 'The petrified cocoon of an unknown insect'),
(6, 23, 34, 'A bronze gauntlet set with many slots, and which violently expels any object pressed into those slots'),
(6, 25, 26, 'A box that plays an illusory message in an unknown language when opened'),
(6, 27, 28, 'A rod that causes you to forget the last five minutes when you press a button near its tip'),
(6, 29, 30, 'A palm-sized cylinder that emits a harmless ray of glowing blue light when squeezed'),
(6, 31, 32, 'A bead that suppresses your hearing when secreted inside either ear, causing you to be deafened'),
(6, 33, 34, 'An amulet that displays your current health as a green bar above your head, with the bar retracting as your hit point total decreases'),
(6, 35, 36, 'A casket containing one hundred tasteless blue pills that produce no discernible effect when swallowed'),
(6, 37, 38, 'A metal mechanical puzzle with no apparent solution'),
(6, 39, 40, 'A metal spinning top that never tips over when spun'),
(6, 41, 42, 'Two strips of cloth-like material, each coated with a soft, hair-like fuzz on one side'),
(6, 43, 44, 'A simple wire pyramid that preserves any foodstuffs it is placed over'),
(6, 45, 56, 'A star chart labeled in an unknown script'),
(6, 47, 48, 'A rectangle of black glass that displays indecipherable arcane runes when you swipe your finger across it'),
(6, 49, 50, 'A schematic that shows the inner workings of an impossibly complex device'),
(6, 51, 52, 'An odd pair of comfortable shoes made from supple, multicolored material'),
(6, 53, 54, 'A mirror that makes you appear more beautiful when you tap your reflection'),
(6, 55, 56, 'A mechanical metal puppy that playfully follows you around when activated'),
(6, 57, 58, 'A talking bracelet that speaks only to correct your grammar'),
(6, 59, 60, 'A bar of soap that can remove any stain'),
(6, 61, 62, 'A journal in Common, written by someone in a world similar to but not quite the same as your own'),
(6, 63, 64, 'A tub containing one serving of disgusting but nutritious goop that refills itself slowly over the course of one week'),
(6, 65, 66, 'An instruction manual for activating a mysterious, world-destroying device'),
(6, 67, 68, 'A small supple disk that displays weird moving symbols when placed over either eye'),
(6, 69, 70, 'A tiny desk set with large, colorful buttons, each of which plays a discordant musical fanfare when pressed'),
(6, 71, 72, 'A pair of tinted spectacles that reduce the glare of the sun when worn'),
(6, 73, 74, 'An inflatable bedroll made from an unknown material, and which slowly deflates when used'),
(6, 75, 76, 'A rod tipped with a blunt metal pincer whose grip can be adjusted by turning a screw'),
(6, 77, 78, 'A battered helmet with a transparent orange visor that flips into place when donned'),
(6, 79, 80, 'An animated map of a mysterious city that appears to be tracking the movements of five creatures'),
(6, 81, 82, 'A cylinder of mist that holds your hair perfectly in shape when sprayed onto your head'),
(6, 83, 84, 'A talking wand that tells you the name of any plant you point it at'),
(6, 85, 86, 'A metal bracelet that displays the number of steps you''ve taken since your last long rest'),
(6, 87, 88, 'A tiny handheld device that projects a glowing dot onto whatever you point it at'),
(6, 89, 90, 'A rectangular piece of glass that displays a twelve-digit countdown on its surface'),
(6, 91, 92, 'A wall chart of mysterious formulae arranged into a color-coded grid'),
(6, 93, 94, 'A handheld device that solves any math problem you input using its buttons'),
(6, 95, 96, 'A ball of speckled brown fur that appears to be alive'),
(6, 97, 98, 'A complicated crystal board game that you don''t know how to play'),
(6, 99, 100, 'A large glass rectangle that displays a storm of black and white patterns when you press a button on its underside');

-- Corporate Trinkets (d100) - 100 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(7, 1, 1, 'A perfect skipping stone'),
(7, 2, 2, 'Three weighted dice that always roll low'),
(7, 3, 3, 'A locket with a picture of Jim Darkmagic'),
(7, 4, 4, 'A tiny anvil and smith''s hammer'),
(7, 5, 5, 'A nonfunctional Immovable Rod'),
(7, 6, 6, 'A DIY acupuncture kit'),
(7, 7, 7, 'A stuffed owlbear toy'),
(7, 8, 8, 'A diagram for a new war lute'),
(7, 9, 9, 'A declaration of war against a nation no one has ever heard of'),
(7, 10, 10, 'A pipe that emits green smoke'),
(7, 11, 11, 'A glass eye'),
(7, 12, 12, 'The centerpiece of a priceless chandelier'),
(7, 13, 13, 'A fine cane with a secret compartment'),
(7, 14, 14, 'A letter written by Rosie Beestinger'),
(7, 15, 15, 'A coin that always lands on its edge'),
(7, 16, 16, 'The deed and title to an abandoned windmill and three acres of tillable land that you''ve never been able to find'),
(7, 17, 17, 'A menu from Big Daddy Donaar''s Yum Yum Hut'),
(7, 18, 18, 'A small purse that screams loudly when opened'),
(7, 19, 19, 'A deep-crow-feather quill'),
(7, 20, 20, 'A pair of breeches that always smells faintly of honey'),
(7, 21, 21, 'A one-armed Viari doll (Apocalypse Dagger accessory missing)'),
(7, 22, 22, 'A leather pouch filled with various finger bones of unknown provenance'),
(7, 23, 23, 'The collar of your childhood pet, Nutmeg'),
(7, 24, 24, 'A seashell that, when pressed to the ear, speaks in lowing rhymes'),
(7, 25, 25, 'A recipe book for cooking with mushrooms'),
(7, 26, 26, 'One expired coupon for "A Free Cornerstone"'),
(7, 27, 27, 'A portable beehive'),
(7, 28, 28, 'Goggles that literally tint everything rose colored'),
(7, 29, 29, 'A Wand of Wonder that allows you to cast only Mending'),
(7, 30, 30, 'A bracelet woven from mistletoe'),
(7, 31, 31, 'A curved claw from an unknown beast that small children are always frightened of'),
(7, 32, 32, 'A longsword that can be folded down in 1 minute and hidden in your pocket'),
(7, 33, 33, 'A living graft of what you believe to be the World Tree'),
(7, 34, 34, 'A tattered scarf with the Acquisitions Incorporated logo'),
(7, 35, 35, 'A box containing a torn-up letter'),
(7, 36, 36, 'An old contract marked "Void"'),
(7, 37, 37, 'A small pigeon in a cage'),
(7, 38, 38, 'An Acquisitions Incorporated "Green Flame" foam finger'),
(7, 39, 39, 'A "C" Team lunchbox'),
(7, 40, 40, 'A potted plant that grows different fruit on every branch'),
(7, 41, 41, 'A book of adventures for children'),
(7, 42, 42, 'An Omin action figure with detachable maul and holy symbol'),
(7, 43, 43, 'A pint glass engraved with a picture of a keg robot'),
(7, 44, 44, 'A giant hockey puck'),
(7, 45, 45, 'A miniature cannon that actually fires'),
(7, 46, 46, 'A very fancy red scarf and matching handkerchief'),
(7, 47, 47, 'An arrow once shot by Morgraen'),
(7, 48, 48, 'A purple worm toy'),
(7, 49, 49, 'A burned doll whose eyes follow you around the room'),
(7, 50, 50, 'An infinite inkwell'),
(7, 51, 51, 'A band embroidered with the symbol of the Six'),
(7, 52, 52, 'A squishy cactus'),
(7, 53, 53, 'A velvet blindfold'),
(7, 54, 54, 'A dirty figurine of a triceratops that can''t be cleaned'),
(7, 55, 55, 'A used (and thus nonmagical) noble knife from the Noble Knife'),
(7, 56, 56, 'A quill that rotates through all the colors of the rainbow'),
(7, 57, 57, 'A twenty-sided die that only rolls the number 4'),
(7, 58, 58, 'A pointed hat that glows in the dark'),
(7, 59, 59, 'A cup that hums when filled with water'),
(7, 60, 60, 'A mug fashioned from the skull of someone else''s enemy'),
(7, 61, 61, 'A small glass jar containing an immortal firefly'),
(7, 62, 62, 'A fake mustache made from gnome facial hair'),
(7, 63, 63, 'A petrified troll finger'),
(7, 64, 64, 'Half of a map'),
(7, 65, 65, 'The other half of a map'),
(7, 66, 66, 'An unreasonable amount of pocket lint'),
(7, 67, 67, 'A dozen flyers for a local gnome food place'),
(7, 68, 68, 'Omin Dran''s business card'),
(7, 69, 69, 'A lock of hair from a changeling'),
(7, 70, 70, 'A marble that rolls uphill'),
(7, 71, 71, 'A piece of parchment listing a command word for a powerful magic item'),
(7, 72, 72, 'A book titled Conversational Giant'),
(7, 73, 73, 'A user''s manual for an Apparatus of Kwalish'),
(7, 74, 74, 'A signed headshot of famous bard Spice Caraway'),
(7, 75, 75, 'The eye of a basilisk in a crystal box'),
(7, 76, 76, 'A postcard from Ravnica'),
(7, 77, 77, 'A stamp collection'),
(7, 78, 78, 'A small piece of solidified smoke'),
(7, 79, 79, 'A six-sided die that sometimes rolls a seven'),
(7, 80, 80, 'A left-handed gauntlet'),
(7, 81, 81, 'A music box that plays nursery rhymes'),
(7, 82, 82, 'A locket that''s bigger on the outside than the inside'),
(7, 83, 83, 'A potted plant that grows hair instead of leaves'),
(7, 84, 84, 'A collection of teeth'),
(7, 85, 85, 'A coin whose minting date always shows three years in the future'),
(7, 86, 86, 'A green drinking horn taken from a very large bull'),
(7, 87, 87, 'A small book containing pressed and dried botanical samples'),
(7, 88, 88, 'A hatched chimera egg'),
(7, 89, 89, 'A slightly used red bandit mask'),
(7, 90, 90, 'A tiny stirge encased in amber'),
(7, 91, 91, 'A large bottle of Red Larch Ale that can''t be opened'),
(7, 92, 92, 'A cane topped with a stylized golden bulldog'),
(7, 93, 93, 'A note in your own hand that you don''t remember writing'),
(7, 94, 94, 'A sprig of herbs from your family''s garden'),
(7, 95, 95, 'A tankard stolen from the Dran & Courtier'),
(7, 96, 96, 'A small, severed tentacle preserved in alcohol'),
(7, 97, 97, 'A walnut with a face drawn on it'),
(7, 98, 98, 'A small flask of liquid from the Lake of Radiant Mists'),
(7, 99, 99, 'An ice cube that never melts'),
(7, 100, 100, 'An expertly carved sword hilt with the blade snapped cleanly off');

-- Icewind Dale Trinkets (d100) - 25 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(8, 1, 4, 'A small wooden figurine of a yawning walrus, painted in red and black'),
(8, 5, 8, 'A pair of scrimshaw cufflinks with an image of a fisherman on a boat engraved on them'),
(8, 9, 12, 'A small iron key with a frayed blue and gold cord tied to it'),
(8, 13, 16, 'A small illustrated book of Northlander myths that has pages missing'),
(8, 17, 20, 'A damaged scrimshaw cameo depicting a merfolk'),
(8, 21, 24, 'A stone from a burial cairn with a tiny Dwarvish rune carved into it'),
(8, 25, 28, 'A ripped cloth sail with a symbol you don''t recognize'),
(8, 29, 32, 'An Ulu knife with a scrimshaw handle'),
(8, 33, 36, 'A jar containing an unidentifiable, sweet, sticky substance'),
(8, 37, 40, 'A delicate glass ball painted with snowflakes, capped by a metal loop with a tiny hook attached to it'),
(8, 41, 44, 'An expedition log with missing pages and a pressed flower used as a bookmark'),
(8, 45, 48, 'An owl figurine carved from whalebone'),
(8, 49, 52, 'A sewing box that smells of old wood and has three spools of blue thread inside'),
(8, 53, 56, 'A scrimshaw-handled ink pen with black runic designs along its length'),
(8, 57, 60, 'A brooch made from a small insect encased in amber'),
(8, 61, 64, 'A scrimshaw pepper shaker etched with the letter W'),
(8, 65, 68, 'An old, wooden-handled ice pick stained with blood that won''t wash off'),
(8, 69, 72, 'A fabric doll bearing an angry expression'),
(8, 73, 76, 'A set of wind chimes made from seashells'),
(8, 77, 80, 'A beautiful silver tin that, when opened, emits the smell of rotting fish'),
(8, 81, 84, 'A bloodstained dreamcatcher made from fishing line, gold wire, and snowy owlbear feathers'),
(8, 85, 88, 'A figurine of a polar bear made of ice that never melts'),
(8, 89, 92, 'A snow globe that doesn''t need to be shaken'),
(8, 93, 96, 'A piece of sea glass shaped like a unicorn''s horn'),
(8, 97, 0, 'A dark blue scarf that gets lighter in shade the higher the altitude of the wearer');

-- Horror Trinkets (d100) - 100 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(9, 1, 1, 'A picture you drew as a child of your imaginary friend'),
(9, 2, 2, 'A lock that opens when blood is dripped in its keyhole'),
(9, 3, 3, 'Clothes stolen from a scarecrow'),
(9, 4, 4, 'A spinning top carved with four faces: happy, sad, wrathful, and dead'),
(9, 5, 5, 'The necklace of a sibling who died on the day you were born'),
(9, 6, 6, 'A wig from someone executed by beheading'),
(9, 7, 7, 'The unopened letter to you from your dying father'),
(9, 8, 8, 'A pocket watch that runs backward for an hour every midnight'),
(9, 9, 9, 'A winter coat stolen from a dying soldier'),
(9, 10, 10, 'A bottle of invisible ink that can only be read at sunset'),
(9, 11, 11, 'A wineskin that refills when interred with a dead person for a night'),
(9, 12, 12, 'A set of silverware used by a king for his last meal'),
(9, 13, 13, 'A spyglass that always shows the world suffering a terrible storm'),
(9, 14, 14, 'A cameo with the profile''s face scratched away'),
(9, 15, 15, 'A lantern with a black candle that never runs out and that burns with green flame'),
(9, 16, 16, 'A teacup from a child''s tea set, stained with blood'),
(9, 17, 17, 'A little black book that records your dreams, and yours alone, when you sleep'),
(9, 18, 18, 'A necklace formed of the interlinked holy symbols of a dozen deities'),
(9, 19, 19, 'A noose that feels heavier than it should'),
(9, 20, 20, 'A birdcage into which small birds fly but once inside never eat or leave'),
(9, 21, 21, 'A lepidopterist''s box filled with dead moths with skull-like patterns on their wings'),
(9, 22, 22, 'A jar of pickled ghouls’ tongues'),
(9, 23, 23, 'The wooden hand of a notorious pirate'),
(9, 24, 24, 'A urn with the ashes of a dead relative'),
(9, 25, 25, 'A hand mirror backed with a bronze depiction of a medusa'),
(9, 26, 26, 'Pallid leather gloves crafted with ivory fingernails'),
(9, 27, 27, 'Dice made from the knuckles of a notorious charlatan'),
(9, 28, 28, 'A ring of keys for forgotten locks'),
(9, 29, 29, 'Nails from the coffin of a murderer'),
(9, 30, 30, 'A key to the family crypt'),
(9, 31, 31, 'A bouquet of funerary flowers that always looks and smells fresh'),
(9, 32, 32, 'A switch used to discipline you as a child'),
(9, 33, 33, 'A music box that plays by itself whenever someone holding it dances'),
(9, 34, 34, 'A walking cane with an iron ferrule that strikes sparks on stone'),
(9, 35, 35, 'A flag from a ship lost at sea'),
(9, 36, 36, 'A porcelain doll’s head that always seems to be looking at you'),
(9, 37, 37, 'A wolf’s head wrought in silver that is also a whistle'),
(9, 38, 38, 'A small mirror that shows a much older version of the viewer'),
(9, 39, 39, 'A small, worn book of children’s nursery rhymes'),
(9, 40, 40, 'A mummified raven claw'),
(9, 41, 41, 'A broken pendant of a silver dragon that’s always cold to the touch'),
(9, 42, 42, 'A small locked box that quietly hums a lovely melody at night, but you always forget it in the morning'),
(9, 43, 43, 'An inkwell that makes one a little nauseous when staring at it'),
(9, 44, 44, 'An old doll made from a dark, dense wood and missing a hand and a foot'),
(9, 45, 45, 'A black executioner’s hood'),
(9, 46, 46, 'A pouch made of flesh, with a sinew drawstring'),
(9, 47, 47, 'A tiny spool of black thread that never runs out'),
(9, 48, 48, 'A tiny clockwork figurine of a dancer that’s missing a gear and doesn’t work'),
(9, 49, 49, 'A black wooden pipe that creates puffs of smoke that look like skulls'),
(9, 50, 50, 'A vial of perfume, the scent of which only certain creatures can detect'),
(9, 51, 51, 'A stone that emits a single endless sigh'),
(9, 52, 52, 'A rag doll with two red dots on its neck'),
(9, 53, 53, 'A spring-loaded toy with a missing crank'),
(9, 54, 54, 'A mason jar containing a harmless but agitated animate ooze'),
(9, 55, 55, 'A black wooden die with 1’s on all the faces'),
(9, 56, 56, 'A child’s portrait with “born” written on the back, along with the next year’s date'),
(9, 57, 57, 'A dagger-sized shark tooth'),
(9, 58, 58, 'A finger that’s taken root in a small pot'),
(9, 59, 59, 'A toolbox containing the remains of a dangerous but broken clockwork arachnid'),
(9, 60, 60, 'A pitcher-sized, opalescent snail shell that occasionally, inexplicably shudders or tips over'),
(9, 61, 61, 'The logbook of an ice-breaking ship called The Haifisch'),
(9, 62, 62, 'A small portrait of you as a child, alongside your identically dressed twin'),
(9, 63, 63, 'A silver pocket watch with thirteen hours marked on the face'),
(9, 64, 64, 'A woodcut of a wolf devouring its own hind leg'),
(9, 65, 65, 'A planchette etched with raven skulls'),
(9, 66, 66, 'A moist coral figurine of a lamprey with arms, legs, and a bipedal stance'),
(9, 67, 67, 'A bronze fingertrap sculpted with roaring tigers'),
(9, 68, 68, 'A pearl necklace that turns read under the full moon'),
(9, 69, 69, 'A fossil of a fish with humanoid features'),
(9, 70, 70, 'A plague doctor’s mask'),
(9, 71, 71, 'A paper talisman with smudged ink'),
(9, 72, 72, 'A locket containing the smeared image of an eyeless figure'),
(9, 73, 73, 'A canopic jar with a lid sculpted like a goat'),
(9, 74, 74, 'A jack-o’-lantern made from a small, pale gourd'),
(9, 75, 75, 'A single high-heeled, iron shoe'),
(9, 76, 76, 'A candle made from a severed hand'),
(9, 77, 77, 'A clockwork device that beats like a heart'),
(9, 78, 78, 'A blank masquerade mask'),
(9, 79, 79, 'A glass eye with a live worm inside'),
(9, 80, 80, 'A sheet with two eyeholes cut in it'),
(9, 81, 81, 'The deed to someplace called Tergeron Manor'),
(9, 82, 82, 'An ornate, wax-sealed crimson envelope that resists all attempts to open it'),
(9, 83, 83, 'A mourning veil trimmed in black lace'),
(9, 84, 84, 'A straitjacket covered in charcoal runes'),
(9, 85, 85, 'A tattered, burlap mask with a crooked smile painted on it'),
(9, 86, 86, 'A green ribbon designed to be worn as a choker'),
(9, 87, 87, 'Dentures with mismatched, sharpened teeth'),
(9, 88, 88, 'A warm, fist-sized egg case'),
(9, 89, 89, 'A copper ring with “mine” engraved on the inside'),
(9, 90, 90, 'A glass ampoule containing a neon green fluid'),
(9, 91, 91, 'An eye patch embroidered with a holy symbol'),
(9, 92, 92, 'A severed big toe with a nail that continues to grow'),
(9, 93, 93, 'A journal that has been heavily redacted'),
(9, 94, 94, 'A glove with a mouth-like design stitched on the palm'),
(9, 95, 95, 'An ornate but empty reliquary made of silver and fractured glass'),
(9, 96, 96, 'A ceramic figure of a cat with too many eyes'),
(9, 97, 97, 'A crumpled paper ticket bearing the words “admit none”'),
(9, 98, 98, 'An electrum coin with your face on one side'),
(9, 99, 99, 'A shrunken gremishka head that twitches when anyone casts magic nearby'),
(9, 100, 100, 'A sunburst amulet with a red stone at the center');

-- Trinkets from the Frostfell and Everice (d100) - 100 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(10, 1, 1, 'Cookie cutter shaped like a unicorn'),
(10, 2, 2, 'Two yew rings linked together'),
(10, 3, 3, 'Silver hand mirror with a nymph-shaped handle'),
(10, 4, 4, 'Painted wooden key whose teeth change configuration every day at dawn'),
(10, 5, 5, 'Delicate silver cameo with pictures of twin children opposite one another'),
(10, 6, 6, 'Golden pendant charm shaped like a leprechaun'),
(10, 7, 7, 'Tiny wooden box containing a croquet set sized for pixies or sprites'),
(10, 8, 8, 'Tiny pair of sharp, iron scissors'),
(10, 9, 9, 'Chess piece shaped like a dancing satyr wearing a bishop''s hat and clutching a gnarled staff'),
(10, 10, 10, 'Saltshaker shaped like a wizard''s tower'),
(10, 11, 11, 'Crystal orb that allows an elf who holds it to sleep'),
(10, 12, 12, 'Pendant that shows the phases of the moon'),
(10, 13, 13, 'Large iron fingernail'),
(10, 14, 14, 'Tiny electrum whistle that only Fey can hear'),
(10, 15, 15, 'Wooden jigsaw puzzle piece as big as a saucer, with a painted image of a jug on it'),
(10, 16, 16, 'Spool of glistening silver thread'),
(10, 17, 17, 'Sheet of music that goblins find upsetting when they hear it played or sung'),
(10, 18, 18, 'Rotten ogre''s tooth with the Elvish glyph for "moon" etched into it'),
(10, 19, 19, 'Vitrified eye of a displacer beast'),
(10, 20, 20, 'Tiny duskwood coffin containing the ashes of a troll'),
(10, 21, 21, 'Old invitation to a banquet in the Summer Court, written in ink on vellum in Sylvan'),
(10, 22, 22, 'Gossamer shawl that glows faintly in moonlight'),
(10, 23, 23, 'Ball-and-cup toy that plays a short, victorious jingle whenever the ball lands in the cup'),
(10, 24, 24, 'Sprite''s skull covered in ink fingerprints'),
(10, 25, 25, 'Silver fork with the outer tines bent sideways'),
(10, 26, 26, 'A soot-stained sock in which a nugget of coal magically appears each day at dawn'),
(10, 27, 27, 'Tiny wooden stool (sized for a pixie or sprite) that gives splinters to those who hold it'),
(10, 28, 28, 'Tiny clockwork dragonfly that slowly beats its wings (but can''t fly) when wound up'),
(10, 29, 29, 'Toy unicorn made of wood, painted with bright colors'),
(10, 30, 30, 'Pixie plushie that sings when you squeeze it'),
(10, 31, 31, '1-inch-square painting of a sleeping elf'),
(10, 32, 32, 'Thimble that helps you daydream when worn'),
(10, 33, 33, 'Pumpkin cupcake that magically regenerates itself in its paper cup each day at dawn'),
(10, 34, 34, 'Fake Three-Dragon Ante card depicting a faerie dragon'),
(10, 35, 35, 'Teacup made from a varnished mushroom cap that magically keeps its liquid contents lukewarm'),
(10, 36, 36, 'Rock that floats and is small enough to hide in your closed fist'),
(10, 37, 37, 'Tiny bottle filled with rainwater collected from the Feywild'),
(10, 38, 38, 'Opalescent conch shell that laughs when you hold it to your ear'),
(10, 39, 39, 'Vial of viscous liquid labeled "Fomorian spit. Do not drink!"'),
(10, 40, 40, 'Wax candle that roars and crackles like a bonfire while lit'),
(10, 41, 41, 'Potted daffodil that sways when near a source of music'),
(10, 42, 42, '8-ounce, glass wine bottle that magically reassembles itself 1 minute after being broken'),
(10, 43, 43, 'Tiny wooden sylph figurehead from a model ship'),
(10, 44, 44, 'Tiny pumpkin-shaped cauldron carved out of bog oak'),
(10, 45, 45, 'Bar of soap that smells like something memorable from your childhood'),
(10, 46, 46, 'Piece of orange parchment folded to look like a knight astride a unicorn'),
(10, 47, 47, 'Tinted glasses so dark that they can''t be seen through'),
(10, 48, 48, '8-inch-long glass ant figurine'),
(10, 49, 49, 'Piece of parchment bearing a child''s drawing of an oni'),
(10, 50, 50, 'Tiny hourglass without sand in it'),
(10, 51, 51, 'Empty vial with corked ends at the top and bottom'),
(10, 52, 52, 'Pair of green leprechaun boots tied together by their laces'),
(10, 53, 53, 'Smoking pipe made from a tree root'),
(10, 54, 54, 'Red cap that droops down to one''s shoulders when worn'),
(10, 55, 55, 'Mask that helps you remember your dreams if you wear it while you sleep'),
(10, 56, 56, 'Notebook that shows what''s written on it only when held upside down'),
(10, 57, 57, 'Wooden top with four sides, each bearing the image of children enjoying a different season'),
(10, 58, 58, 'Tiny beehive wig made for sprites or pixies'),
(10, 59, 59, 'Wooden mouse figurine that squeaks when held'),
(10, 60, 60, 'Stuffed oni doll with a creepy smile and one missing eye'),
(10, 61, 61, 'Empty bag labeled "Candy"'),
(10, 62, 62, 'Tinted glass monocle that makes things look green'),
(10, 63, 63, 'Black executioner''s hood sized for a pixie or sprite'),
(10, 64, 64, 'Piano key carved from a satyr''s horn'),
(10, 65, 65, 'Tiny wooden lute with cat hairs for strings'),
(10, 66, 66, 'Iron needle with an eye that refuses to let thread pass through it'),
(10, 67, 67, 'Tiny sundial that casts a shadow only in moonlight'),
(10, 68, 68, 'Wooden pan flute that attracts harmless local fauna when played'),
(10, 69, 69, 'Silvered pinecone'),
(10, 70, 70, 'Flask of spectral glowworms that change color to reflect the mood of the flask''s holder'),
(10, 71, 71, 'Wooden apple painted blue'),
(10, 72, 72, 'Tuning fork that sounds the tone for the F key'),
(10, 73, 73, 'Nunchaku sized for a pixie or sprite'),
(10, 74, 74, 'Copper coin with a smiling satyr''s face on one side and a satyr''s skull on the other'),
(10, 75, 75, 'Severed chicken''s foot attached to a leather cord'),
(10, 76, 76, 'Collection of baby teeth in a tiny wooden box'),
(10, 77, 77, 'Pinwheel whirligig that spins even when there''s no wind'),
(10, 78, 78, 'Child''s parasol covered in moss and leaves'),
(10, 79, 79, 'Wooden magnifying glass missing its lens'),
(10, 80, 80, 'Glossy mushroom with a red, bell-shaped cap that jingles when shook'),
(10, 81, 81, 'Pouch of seeds that smell like home'),
(10, 82, 82, 'Petrified robin''s egg'),
(10, 83, 83, 'Wooden spoon with a hole in the center'),
(10, 84, 84, 'Paper wasp nest in a jar'),
(10, 85, 85, 'Sprig of rosemary wrapped with ribbon at one end'),
(10, 86, 86, 'Tiny, unfurnished dollhouse sized for a pixie child'),
(10, 87, 87, 'Paintbrush made entirely of ceramic-even the bristles'),
(10, 88, 88, 'Candlestick whose candlelight looks like a tiny, dancing fairy made of fire'),
(10, 89, 89, 'Spectacle frames in the shape of butterfly wings'),
(10, 90, 90, 'Set of false wooden teeth'),
(10, 91, 91, 'Tiny book of fairytales'),
(10, 92, 92, 'Rucksack in which one potato magically appears each day at dawn'),
(10, 93, 93, 'Pixie''s winter jacket lined with fox fur'),
(10, 94, 94, 'Tasseled wine charm shaped like a sprite'),
(10, 95, 95, 'Weak magnetic wand'),
(10, 96, 96, '100-sided die the size of a plum, cut from coal'),
(10, 97, 97, 'Glass slipper, missing its mate'),
(10, 98, 98, 'Tiny dreamcatcher'),
(10, 99, 99, 'Barbell sized for a pixie or sprite'),
(10, 100, 100, 'Music box that plays a sprightly tune you remember from your childhood');

-- Trinkets from Xen'drik (d8) - 10 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(11, 1, 1, 'A pierced dragon scale on a cord'),
(11, 2, 2, 'A statuette of a dragon carved from black bone'),
(11, 3, 3, 'A dragon''s tooth, engraved with an unknown sigil'),
(11, 4, 4, 'A child''s doll of a dragon, woven from leather cords'),
(11, 5, 5, 'A dagger carved from a dragon''s talon'),
(11, 6, 6, 'A brass disk bearing the silhouette of a black dragon'),
(11, 7, 7, 'A small egg-shaped piece of polished bone'),
(11, 8, 8, 'A bone fragment with brass inlaid runes'),
(11, 9, 9, 'A leather pouch filled with tiny draconic teeth'),
(11, 10, 10, 'A single large seed that''s warm to the touch');

-- Trinkets from the Mournland (d8) - 8 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(12, 1, 1, 'A small prism carved from ice that doesn''t melt'),
(12, 2, 2, 'A rusted iron coin, depicting a dwarf lord and the worlds "Five Rex Undra"'),
(12, 3, 3, 'A pair of eight-sided dice carved from ice that doesn''t melt'),
(12, 4, 4, 'A swatch of silvery fur that''s cold to the touch, possibly from a winter wolf'),
(12, 5, 5, 'A snowball; it doesn''t melt and can''t be compressed into ice'),
(12, 6, 6, 'A tiny white dragon sculpted from ice that doesn''t melt'),
(12, 7, 7, 'A key carved from ice that doesn''t melt'),
(12, 8, 8, 'A single scale from a white dragon');

-- Trinkets from Sarlona (d8) - 10 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(13, 1, 1, 'A pressed flower with vivid green petals; when you smell it, you hear eerie music'),
(13, 2, 2, 'A tiny ball of putty; if you set it down, it begins to slowly crawl around'),
(13, 3, 3, 'A perpetually warm disk of dark iron'),
(13, 4, 4, 'A small journal with leathery pages; any words you write in it slowly disappear'),
(13, 5, 5, 'A four-sided die carved with strange markings'),
(13, 6, 6, 'A cameo with the silhouette of an unknown species'),
(13, 7, 7, 'A preserved finger with purple flesh and four joints'),
(13, 8, 8, 'A perfectly preserved eye; if you set it down, it rotates to follow your movement'),
(13, 9, 9, 'A small box; when opened, you alone hear screaming'),
(13, 10, 10, 'A preserved insect; you''ve never seen another like it');

-- Trinkets from Argonnessen (d8) - 8 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(14, 1, 1, 'A polished crystal sphere; when you clutch it in your fist, a telepathic voice recites a story in your mind'),
(14, 2, 2, 'A teardrop pendant made from polished shell; when you hold it, you see the image of a young Riedran man'),
(14, 3, 3, 'A six-sided crystal die; when you roll it, you feel a surge of emotion for six seconds'),
(14, 4, 4, 'A sealed vial filled with faintly luminescent blue mist'),
(14, 5, 5, 'A crystal disk engraved with a labyrinthine pattern'),
(14, 6, 6, 'A leather-bound collection of kalashtar poetry called Shards of the Light'),
(14, 7, 7, 'A sphere of polished crystal; when you hold it in your palm, you feel that it knows you and understands you'),
(14, 8, 8, 'A cup and ball toy; when you successfully catch the ball in the cup, you feel a momentary surge of joy ​');

-- Trinkets from the Lhazaar Principalities (d8) - 8 trinkets
INSERT OR IGNORE INTO item_trinkets (trinket_category_id, dice_min, dice_max, description) VALUES
(15, 1, 1, 'A punched ticket for a voyage from Sharn to Stormreach'),
(15, 2, 2, 'A scorpion''s barb engraved with a single Elvish letter'),
(15, 3, 3, 'A copper coin so big you could use it as a dinner plate'),
(15, 4, 4, 'An image of an elf warrior engraved on a giant''s tooth'),
(15, 5, 5, 'A single page from a giant wizard''s spellbook, bearing an incomplete spell'),
(15, 6, 6, 'A scrap of parchment, part of a map of Stormreach'),
(15, 7, 7, 'A small book titled Feersome Beests of Zendrik'),
(15, 8, 8, 'A scrimshaw carving of a sahuagin');

-- ================================================================================================
-- FUNÇÃO DE UTILIDADE PARA BUSCAR TRINKET POR DADO
-- ================================================================================================
-- Esta view facilita a busca de trinkets baseada em rolagem de dados
-- Uso: SELECT * FROM trinket_search WHERE category_id = 1 AND 42 BETWEEN dice_min AND dice_max;

CREATE VIEW IF NOT EXISTS trinket_search AS
SELECT 
    t.trinket_id,
    t.trinket_category_id as category_id,
    tc.category_name,
    tc.dice_type,
    t.dice_min,
    t.dice_max,
    t.description,
    cb.name as book_name
FROM item_trinkets t
JOIN item_trinket_categories tc ON t.trinket_category_id = tc.trinket_category_id
JOIN core_books cb ON tc.book_id = cb.book_id;

-- ================================================================================================
-- COMENTÁRIOS SOBRE O SISTEMA
-- ================================================================================================
/*
SISTEMA COMPLETO DE TRINKETS D&D 5E:

✅ DADOS INCLUÍDOS:
- 695 trinkets de 15 categorias diferentes
- Player's Handbook: 100 trinkets
- Elemental Evil: 100 trinkets  
- Curse of Strahd: 50 trinkets (com ranges)
- Mordenkainen's Tome of Foes: 8 trinkets élfico
- Eberron (6 subcategorias): 52 trinkets
- Kwalish: 50 trinkets
- Acquisitions Incorporated: 100 trinkets
- Icewind Dale: 25 trinkets
- Van Richten's Guide: 100 trinkets
- Wild Beyond Witchlight: 100 trinkets

🎲 FUNCIONALIDADES:
- Suporte completo a ranges de dados (1-2, 3-4, etc.)
- Busca eficiente por rolagem de dados
- Estrutura otimizada sem colunas redundantes
- Relacionamentos íntegros com livros
- View de busca para facilitar consultas

📋 INSTRUÇÕES:
- Execute este schema para ter todos os trinkets
- Use trinket_search view para buscar por rolagem
- Exemplo: SELECT * FROM trinket_search WHERE category_id = 1 AND 50 BETWEEN dice_min AND dice_max;
*/

-- ================================================================================================
-- FIM DO SISTEMA COMPLETO DE TRINKETS
-- ================================================================================================
