-- =============================================================================
-- SORCERER SUBCLASSES
-- =============================================================================

-- Subclasse: Aberrant Mind (ID: 150)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(150, 'Psionic Spells', 1, 'Starting at 1st level, you learn additional spells when you reach certain levels in this class, as shown on the Psionic Spells table. Each of these spells counts as a sorcerer spell for you, but it doesn''t count against the number of sorcerer spells you know. Whenever you gain a sorcerer level, you can replace one spell you gained from this feature with another spell of the same level. The new spell must be a divination or an enchantment spell from the sorcerer, warlock, or wizard spell list. Psionic Spells: 1st Level - Arms of Hadar, Dissonant Whispers, Mind Sliver; 3rd Level - Calm Emotions, Detect Thoughts; 5th Level - Hunger of Hadar, Sending; 7th Level - Evard''s Black Tentacles, Summon Aberration; 9th Level - Rary''s Telepathic Bond, Telekinesis.'),
(150, 'Telepathic Speech', 1, 'Starting at 1st level, you can form a telepathic connection between your mind and the mind of another. As a bonus action, choose one creature you can see within 30 feet of you. You and the chosen creature can speak telepathically with each other while the two of you are within a number of miles of each other equal to your Charisma modifier (minimum of 1 mile). To understand each other, you each must speak mentally in a language the other knows. The telepathic connection lasts for a number of minutes equal to your sorcerer level. It ends early if you are incapacitated or die or if you use this ability to form a connection with a different creature.'),
(150, 'Psionic Sorcery', 6, 'Beginning at 6th level, when you cast any spell of 1st level or higher from your Psionic Spells feature, you can cast it by expending a spell slot as normal or by spending a number of sorcery points equal to the spell''s level. If you cast the spell using sorcery points, it requires no verbal or somatic components, and it requires no material components, unless they are consumed by the spell.'),
(150, 'Psychic Defenses', 6, 'At 6th level, you gain resistance to psychic damage, and you have advantage on saving throws against being charmed or frightened.'),
(150, 'Revelation in Flesh', 14, 'Beginning at 14th level, you can unleash the aberrant truth hidden within yourself. As a bonus action, you can spend 1 or more sorcery points to magically transform your body for 10 minutes. For each sorcery point you spend, you can gain one of the following benefits of your choice, the effects of which last until the transformation ends: You can see any invisible creature within 60 feet of you, provided it isn''t behind total cover. Your eyes also turn black or become writhing sensory tendrils. You gain a flying speed equal to your walking speed and can hover. As you fly, your skin glistens with mucus or shines with an otherworldly light. You gain a swimming speed equal to twice your walking speed, and you can breathe underwater. Moreover, gills grow from your neck or fan out from behind your ears, your fingers become webbed, or you grow writhing cilia that extend through your clothing. Your body, along with any equipment you are wearing or carrying, becomes slimy and pliable. You can move through any space as narrow as 1 inch without squeezing, and you can spend 5 feet of movement to escape from nonmagical restraints or being grappled.'),
(150, 'Warping Implosion', 18, 'At 18th level, you can unleash your aberrant power as a space-warping anomaly. As an action, you can teleport to an unoccupied space you can see within 120 feet of you. Immediately after you disappear, each creature within 30 feet of the space you left must make a Strength saving throw against your spell save DC. On a failed save, a creature takes 3d10 force damage and is pulled straight toward the space you left, ending in an unoccupied space as close to your former space as possible. On a successful save, the creature takes half as much damage and isn''t pulled. Once you use this feature, you can''t do so again until you finish a long rest, unless you spend 5 sorcery points to use it again.');

-- Subclasse: Clockwork Soul (ID: 151)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(151, 'Clockwork Magic', 1, 'You learn additional spells when you reach certain levels in this class, as shown on the Clockwork Spells table. Each spell counts as a sorcerer spell for you, but it doesn''t count against the number of sorcerer spells you know. These spells can''t be replaced when you gain a level in this class. Whenever you gain a sorcerer level, you can replace one spell you gained from this feature with another spell of the same level. The new spell must be an abjuration or a transmutation spell from the sorcerer, warlock, or wizard spell list. Clockwork Spells: 1st Level - Alarm, Protection from Evil and Good; 3rd Level - Aid, Lesser Restoration; 5th Level - Dispel Magic, Protection from Energy; 7th Level - Freedom of Movement, Summon Construct; 9th Level - Greater Restoration, Wall of Force. Manifestations of Order: 1 - Spectral cogwheels hover behind you; 2 - The hands of a clock spin in your eyes; 3 - Your skin glows with a brassy sheen; 4 - Floating equations and geometric objects overlay your body; 5 - Your spellcasting focus temporarily takes the form of a Tiny clockwork mechanism; 6 - The ticking of gears or ringing of a clock can be heard by you and those affected by your magic.'),
(151, 'Restore Balance', 1, 'Starting at 1st level, your connection to the plane of absolute order allows you to equalize chaotic moments. When a creature you can see within 60 feet of you is about to roll a d20 with advantage or disadvantage, you can use your reaction to prevent the roll from being affected by advantage and disadvantage. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(151, 'Bastion of Law', 6, 'Starting at 6th level, you can tap into the grand equation of existence to imbue a creature with a shimmering shield of order. As an action, you can expend 1 to 5 sorcery points to create a magical ward around yourself or another creature you can see within 30 feet of you. The ward lasts until you finish a long rest or until you use this feature again. The ward is represented by a number of d8s equal to the number of sorcery points spent to create it. When the warded creature takes damage, it can expend a number of those dice, roll them, and reduce the damage taken by the total rolled on those dice.'),
(151, 'Trance of Order', 14, 'Starting at 14th level, you gain the ability to align your consciousness to the endless calculations of Mechanus. As a bonus action, you can enter this state for 1 minute. For the duration, attack rolls against you can''t benefit from advantage, and whenever you make an attack roll, an ability check, or a saving throw, you can treat a roll of 9 or lower on the d20 as a 10. Once you use this bonus action, you can''t use it again until you finish a long rest, unless you spend 5 sorcery points to use it again.'),
(151, 'Clockwork Cavalcade', 18, 'At 18th level, you summon spirits of order to expunge disorder around you. As an action, you summon the spirits in a 30-foot cube originating from you. The spirits look like modrons or other constructs of your choice. The spirits are intangible and invulnerable, and they create the following effects within the cube before vanishing: The spirits restore up to 100 hit points, divided as you choose among any number of creatures of your choice in the cube. Any damaged objects entirely in the cube are repaired instantly. Every spell of 6th level or lower ends on creatures and objects of your choice in the cube. Once you use this action, you can''t use it again until you finish a long rest, unless you spend 7 sorcery points to use it again.');

-- Subclasse: Draconic Bloodline (ID: 152)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(152, 'Dragon Ancestor', 1, 'At 1st level, you choose one type of dragon as your ancestor. The damage type associated with each dragon is used by features you gain later. You can speak, read, and write Draconic. Additionally, whenever you make a Charisma check when interacting with dragons, your proficiency bonus is doubled if it applies to the check.'),
(152, 'Draconic Resilience', 1, 'As magic flows through your body, it causes physical traits of your dragon ancestors to emerge. At 1st level, your hit point maximum increases by 1 and increases by 1 again whenever you gain a level in this class. Additionally, parts of your skin are covered by a thin sheen of dragon-like scales. When you aren''t wearing armor, your AC equals 13 + your Dexterity modifier.'),
(152, 'Elemental Affinity', 6, 'Starting at 6th level, when you cast a spell that deals damage of the type associated with your draconic ancestry, add your Charisma modifier to one damage roll of that spell. At the same time, you can spend 1 sorcery point to gain resistance to that damage type for 1 hour.'),
(152, 'Dragon Wings', 14, 'At 14th level, you gain the ability to sprout a pair of dragon wings from your back, gaining a flying speed equal to your current speed. You can create these wings as a bonus action on your turn. They last until you dismiss them as a bonus action on your turn. You can''t manifest your wings while wearing armor unless the armor is made to accommodate them, and clothing not made to accommodate your wings might be destroyed when you manifest them.'),
(152, 'Draconic Presence', 18, 'Beginning at 18th level, you can channel the dread presence of your dragon ancestor, causing those around you to become awestruck or frightened. As an action, you can spend 5 sorcery points to draw on this power and exude an aura of awe or fear (your choice) to a distance of 60 feet. For 1 minute or until you lose your concentration (as if you were casting a concentration spell), each hostile creature that starts its turn in this aura must succeed on a Wisdom saving throw or be charmed (if you chose awe) or frightened (if you chose fear) until the aura ends. A creature that succeeds on this saving throw is immune to your aura for 24 hours.');

-- Subclasse: Divine Soul (ID: 153)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(153, 'Divine Magic', 1, 'Your link to the divine allows you to learn spells normally associated with the cleric class. When your Spellcasting feature lets you learn a sorcerer cantrip or a sorcerer spell of 1st level or higher, you can choose the new spell from the cleric spell list or the sorcerer spell list. You must otherwise obey all the restrictions for selecting the spell, and it becomes a sorcerer spell for you. In addition, choose an affinity for the source of your divine power: good, evil, law, chaos, or neutrality. You learn an additional spell based on that affinity, as shown below. It is a sorcerer spell for you, but it doesn''t count against your number of sorcerer spells known. If you later replace this spell, you must replace it with a spell from the cleric spell list.'),
(153, 'Favored by the Gods', 1, 'Starting at 1st level, divine power guards your destiny. If you fail a saving throw or miss with an attack roll, you can roll 2d4 and add it to the total, possibly changing the outcome. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(153, 'Empowered Healing', 6, 'Starting at 6th level, the divine energy coursing through you can empower healing spells. Whenever you or an ally within 5 feet of you rolls dice to determine the number of hit points a spell restores, you can spend 1 sorcery point to reroll any number of those dice once, provided you aren''t incapacitated. You can use this feature only once per turn.'),
(153, 'Angelic Form', 14, 'Starting at 14th level, you can use a bonus action to manifest a pair of spectral wings from your back. While the wings are present, you have a flying speed of 30 feet. The wings last until you''re incapacitated, you die, or you dismiss them as a bonus action. The affinity you chose for your Divine Magic feature determines the appearance of the spectral wings: eagle wings for good or law, bat wings for evil or chaos, and dragonfly wings for neutrality.'),
(153, 'Unearthly Recovery', 18, 'At 18th level, you gain the ability to overcome grievous injuries. As a bonus action when you have fewer than half of your hit points remaining, you can regain a number of hit points equal to half your hit point maximum. Once you use this feature, you can’t use it again until you finish a long rest.');

-- Subclasse: Lunar Sorcery (ID: 154)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(154, 'Lunar Embodiment', 1, 'You learn additional spells when you reach certain levels in this class, as shown on the Lunar Spells table. Each of these spells counts as a sorcerer spell for you, but it doesn''t count against the number of sorcerer spells you know. Lunar Spells table: 1st level - Full Moon: Shield; New Moon: Ray of Sickness; Crescent Moon: Color Spray. 3rd level - Full Moon: Lesser Restoration; New Moon: Blindness/Deafness; Crescent Moon: Alter Self. 5th level - Full Moon: Dispel Magic; New Moon: Vampiric Touch; Crescent Moon: Phantom Steed. 7th level - Full Moon: Death Ward; New Moon: Confusion; Crescent Moon: Hallucinatory Terrain. 9th level - Full Moon: Rary''s Telepathic Bond; New Moon: Hold Monster; Crescent Moon: Mislead. Whenever you finish a long rest, you can choose what lunar phase manifests its power through your magic: Full Moon, New Moon, or Crescent Moon. While in the chosen phase, you can cast one 1st-level spell of the associated phase in the Lunar Spells table once without expending a spell slot. Once you cast a spell in this way, you can''t do so again until you finish a long rest.'),
(154, 'Moon Fire', 1, 'Starting at 1st level, you can call down the radiant light of the moon on command. You learn the Sacred Flame spell, which doesn''t count against the number of sorcerer cantrips you know. When you cast the spell, you can target one creature as normal or target two creatures within range that are within 5 feet of each other.'),
(154, 'Lunar Boons', 6, 'Starting at 6th level, the current phase of your Lunar Embodiment can affect your Metamagic feature. Each Lunar Embodiment phase is associated with certain schools of magic, as shown here: Full Moon: Abjuration and Divination spells. New Moon: Enchantment and Necromancy spells. Crescent Moon: Illusion and Transmutation spells. Whenever you use Metamagic on a spell of a school of magic associated with your current Lunar Embodiment phase, you can reduce the sorcery points spent by 1 (minimum 0). You can reduce the sorcery points spent for your Metamagic a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(154, 'Waxing and Waning', 6, 'Starting at 6th level, you gain greater control over the phases of your lunar magic. As a bonus action, you can spend 1 sorcery point to change your current Lunar Embodiment phase for a different one. You can now cast one 1st-level spell from each lunar phase of the Lunar Spells table once without expending a spell slot, provided your current phase is the same as the lunar phase spell. Once you cast a lunar phase spell in this way, you can''t do so again until you finish a long rest.'),
(154, 'Lunar Empowerment', 14, 'Starting at 14th level, the power of a lunar phase saturates your being. While you are in a Lunar Embodiment phase, you also gain the following benefit associated with that phase: Full Moon: You can use a bonus action to shed bright light in a 10-foot radius and dim light for an additional 10 feet or to douse the light. In addition, you and creatures of your choice have advantage on Intelligence (Investigation) and Wisdom (Perception) checks while within the bright light you shed. New Moon: You have advantage on Dexterity (Stealth) checks. In addition, while you are entirely in darkness, attack rolls have disadvantage against you. Crescent Moon: You have resistance to necrotic and radiant damage.'),
(154, 'Lunar Phenomenon', 18, 'At 18th level, as a bonus action, you can tap into a special power of your current Lunar Embodiment phase. Alternatively, as part of the bonus action you take to change your lunar phase using the Waxing and Waning feature, you can immediately use the power of the lunar phase you are entering: Full Moon: You radiate moonlight for a moment. Each creature of your choice within 30 feet of you must succeed on a Constitution saving throw against your spell save DC or be blinded until the end of its next turn. In addition, one creature of your choice in that area regains 3d8 hit points. New Moon: You momentarily emanate gloom. Each creature of your choice within 30 feet of you must succeed on a Dexterity saving throw against your spell save DC or take 3d10 necrotic damage and have its speed reduced to 0 until the end of its next turn. In addition, you become invisible until the end of your next turn, or until immediately after you make an attack or cast a spell. Crescent Moon: You can magically teleport to an unoccupied space you can see within 60 feet of yourself. You can bring along one willing creature you can see within 5 feet of yourself. That creature teleports to an unoccupied space of your choice that you can see within 5 feet of your destination space. In addition, you and that creature gain resistance to all damage until the start of your next turn. Once you use one of these bonus action benefits, you can''t use that benefit again until you finish a long rest, unless you spend 5 sorcery points to use it again.');

-- Subclasse: Shadow Magic (ID: 155)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(155, 'Eyes of the Dark', 1, 'From 1st level, you have darkvision with a range of 120 feet. When you reach 3rd level in this class, you learn the darkness spell, which doesn''t count against your number of sorcerer spells known. In addition, you can cast it by spending 2 sorcery points or by expending a spell slot. If you cast it with sorcery points, you can see through the darkness created by the spell.'),
(155, 'Strength of the Grave', 1, 'Starting at 1st level, your existence in a twilight state between life and death makes you difficult to defeat. When damage reduces you to 0 hit points, you can make a Charisma saving throw (DC 5 + the damage taken). On a success, you instead drop to 1 hit point. You can''t use this feature if you are reduced to 0 hit points by radiant damage or by a critical hit. After the saving throw succeeds, you can''t use this feature again until you finish a long rest.'),
(155, 'Hound of Ill Omen', 6, 'At 6th level, you gain the ability to call forth a howling creature of darkness to harass your foes. As a bonus action, you can spend 3 sorcery points to summon a hound of ill omen to target one creature you can see within 120 feet of you. The hound uses the dire wolf''s statistics, with the following changes: The hound is size Medium, not Large, and it counts as a monstrosity, not a beast. It appears with a number of temporary hit points equal to half your sorcerer level. It can move through other creatures and objects as if they were difficult terrain. The hound takes 5 force damage if it ends its turn inside an object. At the start of its turn, the hound automatically knows its target''s location. If the target was hidden, it is no longer hidden from the hound. The hound appears in an unoccupied space of your choice within 30 feet of the target. Roll initiative for the hound. On its turn, it can move only toward its target by the most direct route, and it can use its action only to attack its target. The hound can make opportunity attacks, but only against its target. Additionally, while the hound is within 5 feet of the target, the target has disadvantage on saving throws against any spell you cast. The hound disappears if it is reduced to 0 hit points, if its target is reduced to 0 hit points, or after 5 minutes.'),
(155, 'Shadow Walk', 14, 'At 14th level, you gain the ability to step from one shadow into another. When you are in dim light or darkness, as a bonus action, you can teleport up to 120 feet to an unoccupied space you can see that is also in dim light or darkness.'),
(155, 'Umbral Form', 18, 'Starting at 18th level, you can spend 6 sorcery points as a bonus action to transform yourself into a shadowy form. In this form, you have resistance to all damage except force and radiant damage, and you can move through other creatures and objects as if they were difficult terrain. You take 5 force damage if you end your turn inside an object. You remain in this form for 1 minute. It ends early if you are incapacitated, if you die, or if you dismiss it as a bonus action.');

-- Subclasse: Storm Sorcery (ID: 156)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(156, 'Tempestuous Magic', 1, 'Starting at 1st level, you can use a bonus action on your turn to cause whirling gusts of elemental air to briefly surround you, immediately before or after you cast a sorcerer spell of 1st level or higher. Doing so allows you to fly up to 10 feet without provoking opportunity attacks.'),
(156, 'Heart of the Storm', 6, 'At 6th level, you gain resistance to lightning and thunder damage. In addition, whenever you start casting a spell of 1st level or higher that deals lightning or thunder damage, stormy magic erupts from you. Each creature of your choice that is within 10 feet of you must make a Dexterity saving throw against your spell save DC, taking lightning or thunder damage (your choice) equal to half your sorcerer level on a failed save, and half as much damage on a successful one.'),
(156, 'Storm Guide', 6, 'Also at 6th level, you gain the ability to subtly control the weather around you. As an action, you can change the weather in a 5-mile radius centered on yourself. You can choose from any effect that would be appropriate for the climate and season. The change lasts for 1 hour. Once you use this feature, you can''t use it again until you finish a long rest.'),
(156, 'Storm''s Fury', 14, 'Starting at 14th level, when you are hit by an attack while you are wearing no armor and not wielding a shield, you can use your reaction to deal lightning or thunder damage (your choice) to the attacker. The damage equals your sorcerer level.'),
(156, 'Wind Soul', 18, 'At 18th level, you have become one with the elemental air around you. You have a flying speed of 60 feet whenever you aren''t underground or indoors. In addition, you can cast the freedom of movement spell on yourself at will, without expending a spell slot or material components.');

-- Subclasse: Wild Magic (ID: 157)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(157, 'Wild Magic Surge', 1, 'Starting when you choose this origin at 1st level, your spellcasting can unleash surges of untamed magic. Immediately after you cast a sorcerer spell of 1st level or higher, the DM can have you roll a d20. If you roll a 1, roll on the Wild Magic Surge table to create a random magical effect.'),
(157, 'Tides of Chaos', 1, 'Also at 1st level, you can manipulate the forces of chance and chaos to gain advantage on one attack roll, ability check, or saving throw. Once you use this feature, you can''t use it again until you finish a long rest. Any time before you regain the use of this feature, the DM can have you roll on the Wild Magic Surge table immediately after you cast a sorcerer spell of 1st level or higher. You then regain the use of this feature.'),
(157, 'Bend Luck', 6, 'Starting at 6th level, you can twist fate using your wild magic. When another creature you can see makes an attack roll, an ability check, or a saving throw, you can use your reaction and spend 2 sorcery points to roll 1d4 and apply the number rolled as a bonus or penalty (your choice) to the creature''s roll. You can do so after the creature rolls but before any effects of the roll occur.'),
(157, 'Controlled Chaos', 14, 'Beginning at 14th level, you learn to exert some control over your wild magic. Immediately after you roll on the Wild Magic Surge table, you can choose to reroll the d20 and must use the new roll.'),
(157, 'Spell Bombardment', 18, 'At 18th level, when you cast a sorcerer spell that forces a creature to make a saving throw to resist its effects, one target of the spell takes an extra 1d6 damage of the spell''s type if it fails its saving throw against the spell.');

-- Subclasse: Pyromancy (Plane Shift) (ID: 158)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(158, 'Firestarter', 1, 'At 1st level, you gain the ability to ignite flammable objects with your magic. You can use a bonus action to cause a nonmagical flame to appear in your hand, which lasts until the end of your turn. You can use this flame to light a torch, a campfire, or any other flammable object.'),
(158, 'Flame Blade', 6, 'At 6th level, you can create a sword made of fire as a bonus action. This sword is a melee weapon that you are proficient with, and it deals 2d6 fire damage on a hit. The sword lasts for 1 minute or until you dismiss it as a bonus action.'),
(158, 'Fire Walk', 14, 'At 14th level, you gain the ability to walk through fire and flames without harm. You have resistance to fire damage, and you can move through fire and lava as if it were difficult terrain.'),
(158, 'Inferno', 18, 'At 18th level, you can unleash a wave of fire in a 30-foot cone as an action. Each creature in that area must make a Dexterity saving throw against your spell save DC, taking 6d10 fire damage on a failed save, or half as much damage on a successful one. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Lunar Magic (UA) (ID: 159)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(159, 'Lunar Affinity', 1, 'At 1st level, you gain proficiency in the Arcana skill. Additionally, you learn the *Dancing Lights* cantrip.'),
(159, 'Moonlit Magic', 6, 'Starting at 6th level, you can cast the *Faerie Fire* spell without expending a spell slot. You can do this once per long rest.'),
(159, 'Lunar Veil', 14, 'At 14th level, you can use your action to create a veil of silvery light around yourself. For 1 minute, you have advantage on Dexterity saving throws and can move through difficult terrain without expending extra movement. Once you use this feature, you can''t use it again until you finish a long rest.'),
(159, 'Embrace the Night', 18, 'At 18th level, you can draw upon the power of the moon to regain expended spell slots. Once per long rest, when you finish a short or long rest, you can regain a number of expended spell slots equal to your proficiency bonus.');

-- Aberrant Mind (UA) (ID: 160)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(160, 'Psionic Spells', 1, 'Starting at 1st level, your aberrant nature changes your mind in subtle but profound ways. You learn additional spells when you reach certain levels in this class, as shown on the Psionic Spells table. The spell counts as a sorcerer spell for you, but it doesn''t count against the number of sorcerer spells you know. Psionic Magic table: 1st level - Arms of Hadar, Dissonant Whispers; 3rd level - Calm Emotions, Detect Thoughts; 5th level - Hunger of Hadar, Sending; 7th level - Compulsion, Evard''s Black Tentacles; 9th level - Modify Memory, Rary''s Telepathic Bond.'),
(160, 'Warped Being', 1, 'Starting at 1st level, your aberrant origin protects you from harm. Your body might have a coating of viscous slime, tough hide, scales, or an invisible psionic barrier (choose the form of protection when you gain this feature). Whatever form the protection takes, your AC equals 13 + your Dexterity modifier while you aren''t wearing armor.'),
(160, 'Psionic Sorcery', 6, 'Beginning at 6th level, when you cast any of the spells gained from your Psionic Spells feature, you can cast it by expending a spell slot as normal or by spending a number of sorcery points equal to the spell''s level. If you cast the spell using sorcery points, it requires no components.'),
(160, 'Psychic Defenses', 6, 'At 6th level, you gain resistance to psychic damage, and you have advantage on saving throws against being charmed or frightened.'),
(160, 'Revelation in Flesh', 14, 'Beginning at 14th level, you can unleash the aberrant truth hidden within your flesh. As a bonus action, you can spend 1 or more sorcery points to magically transform your body for 1 minute. For each sorcery point you spend, you can gain one of the following benefits of your choice, the effects of which last until the transformation ends: You gain a swimming speed equal to your walking speed and the ability to breathe water. Gills grow from your neck or fan out from behind your ears, your fingers become webbed, or you grow lashing cilia that extend through your clothing. You gain a flying speed equal to your walking speed and can hover. As you fly, your skin glistens with mucus. Your body, along with any equipment you are wearing or carrying, becomes slimy and pliable. You can move through any space as narrow as 1 inch without squeezing, and you can spend 5 feet of movement to escape from nonmagical restraints or being grappled. Your eyes turn black or become writhing sensory tendrils. You are aware of the location of any hidden or invisible creature within 60 feet of you.'),
(160, 'Warp Reality', 18, 'At 18th level, you become the focal point of a reality-warping anomaly. As an action, you can magically radiate a transparent, 20-foot-radius aura for 1 minute. This might take the form of a sphere of rippling psychic energy, a fluctuating amoebic gel, an extrusion of ephemeral parasites, or some other manifestation. Other creatures treat the aura as difficult terrain, and when they start their turn in it, they take 2d10 psychic damage. When you activate this feature, you can choose any number of creatures you can see to be unaffected by the aura. As a bonus action, you can end the aura early. If you do so, you and any number of creatures you choose within the aura are teleported to a location you can see within 1 mile of you. Each creature must appear within 20 feet of you and in an unoccupied space. An unwilling creature that succeeds on a Charisma saving throw against your spell save DC is not teleported. Once you use this feature, you can''t use it again until you finish a long rest.'),

-- Clockwork Soul (UA) (ID: 161)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(161, 'Clockwork Magic', 1, 'You learn additional spells when you reach certain levels in this class, as shown on the Clockwork Spells table. Each spell counts as a sorcerer spell for you, but it doesn''t count against the number of sorcerer spells you know. These spells can''t be replaced when you gain a level in this class. Whenever you gain a sorcerer level, you can replace one spell you gained from this feature with another spell of the same level. The new spell must be an abjuration or a transmutation spell from the sorcerer, warlock, or wizard spell list. Clockwork Spells: 1st Level - Alarm, Protection from Evil and Good; 3rd Level - Aid, Lesser Restoration; 5th Level - Dispel Magic, Protection from Energy; 7th Level - Freedom of Movement, Summon Construct; 9th Level - Greater Restoration, Wall of Force. Manifestations of Order: 1 - Spectral cogwheels hover behind you; 2 - The hands of a clock spin in your eyes; 3 - Your skin glows with a brassy sheen; 4 - Floating equations and geometric objects overlay your body; 5 - Your spellcasting focus temporarily takes the form of a Tiny clockwork mechanism; 6 - The ticking of gears or ringing of a clock can be heard by you and those affected by your magic.'),
(161, 'Restore Balance', 1, 'Starting at 1st level, your connection to the plane of absolute order allows you to equalize chaotic moments. When a creature you can see within 60 feet of you is about to roll a d20 with advantage or disadvantage, you can use your reaction to prevent the roll from being affected by advantage and disadvantage. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(161, 'Bastion of Law', 6, 'Starting at 6th level, you can tap into the grand equation of existence to imbue a creature with a shimmering shield of order. As an action, you can expend 1 to 5 sorcery points to create a magical ward around yourself or another creature you can see within 30 feet of you. The ward lasts for 1 minute or until you use this feature again. The ward has hit points equal to 5 + five times the number of sorcery points you expended. Whenever the warded creature takes damage, the ward takes the damage instead. If the ward is reduced to 0 hit points, the warded creature takes any remaining damage. While the ward remains, the warded creature has advantage on saving throws against being charmed or frightened.'),
(161, 'Clockwork Cavalcade', 14, 'At 14th level, you can summon spirits of order to expunge disorder around you. As an action, you summon the spirits in a 30-foot cube originating from you. The spirits look like modrons or other constructs of your choice. The spirits are intangible and invulnerable, and they create the following effects within the cube before vanishing: The spirits restore up to 100 hit points, divided as you choose among any number of creatures of your choice in the cube. Any damaged objects entirely in the cube are repaired instantly. Every spell of 6th level or lower ends on creatures and objects of your choice in the cube. Once you use this action, you can''t use it again until you finish a long rest, unless you spend 7 sorcery points to use it again.'),
(161, 'Trance of Order', 18, 'Starting at 18th level, you gain the ability to align your consciousness to the endless calculations of Mechanus. As a bonus action, you can enter this state for 1 minute. For the duration, attack rolls against you can''t benefit from advantage, and whenever you make an attack roll, an ability check, or a saving throw, you can treat a roll of 9 or lower on the d20 as a 10. Once you use this bonus action, you can''t use it again until you finish a long rest, unless you spend 5 sorcery points to use it again.');

-- Subclasse: Favored Soul (UA) (ID: 162)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(162, 'Chosen of the Gods', 1, 'At 1st level, you choose one of the cleric class''s divine domains. You add that domain''s spells for 1st-level clerics to your known spells. These spells do not count against the number of spells you can know, and they are considered to be sorcerer spells for you. When you reach 3rd, 5th, 7th, and 9th levels in the sorcerer class, you likewise learn your domain''s spells that become available at those levels.'),
(162, 'Bonus Proficiencies', 1, 'At 1st level, you gain proficiency in light armor, medium armor, shields, and simple weapons.'),
(162, 'Extra Attack', 6, 'Starting at 6th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.'),
(162, 'Divine Wings', 14, 'At 14th level, you gain the ability to sprout a pair of wings from your back (feathered or bat-like, your choice), gaining a flying speed equal to your current walking speed. You can create these wings as a bonus action on your turn. They last until you dismiss them as a bonus action on your turn. You can''t manifest your wings while wearing armor unless the armor is made to accommodate them, and clothing not made to accommodate your wings might be destroyed when you manifest them.'),
(162, 'Power of the Chosen', 18, 'Starting at 18th level, when you cast one of the spells you learned from your Chosen of the Gods class feature, you regain hit points equal to your Charisma modifier (minimum +1) + the spell''s level.');

-- Favored Soul Revised (UA) (ID: 163)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(163, 'Divine Magic', 1, 'Your link to the divine allows you to learn spells normally associated with the cleric class. When your Spellcasting feature lets you learn a sorcerer cantrip or a sorcerer spell of 1st level or higher, you can choose the new spell from the cleric spell list or the sorcerer spell list. You must otherwise obey all the restrictions for selecting the spell, and it becomes a sorcerer spell for you. In addition, choose an affinity for the source of your divine power: good, evil, law, chaos, or neutrality. You learn an additional spell based on that affinity, as shown below. It is a sorcerer spell for you, but it doesn''t count against your number of sorcerer spells known. If you later replace this spell, you must replace it with a spell from the cleric spell list.'),
(163, 'Favored by the Gods', 1, 'Starting at 1st level, divine power guards your destiny. If you fail a saving throw or miss with an attack roll, you can roll 2d4 and add it to the total, possibly changing the outcome. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(163, 'Empowered Healing', 6, 'Starting at 6th level, the divine energy coursing through you can empower healing spells. Whenever you or an ally within 5 feet of you rolls dice to determine the number of hit points a spell restores, you can spend 1 sorcery point to reroll any number of those dice once, provided you aren''t incapacitated. You can use this feature only once per turn.'),
(163, 'Angelic Form', 14, 'Starting at 14th level, you can use a bonus action to manifest a pair of spectral wings from your back. While the wings are present, you have a flying speed of 30 feet. The wings last until you''re incapacitated, you die, or you dismiss them as a bonus action. The affinity you chose for your Divine Magic feature determines the appearance of the spectral wings: eagle wings for good or law, bat wings for evil or chaos, and dragonfly wings for neutrality.'),
(163, 'Unearthly Recovery', 18, 'At 18th level, you gain the ability to overcome grievous injuries. As a bonus action when you have fewer than half of your hit points remaining, you can regain a number of hit points equal to half your hit point maximum. Once you use this feature, you can’t use it again until you finish a long rest.');

-- Subclasse: Giant Soul (UA) (ID: 164)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(164, 'Jotun Resilience', 1, 'The resilience of giants flows through your body. At 1st level, your hit point maximum increases by 1, and it increases by 1 again whenever you gain a level in this class.'),
(164, 'Mark of the Ordning', 1, 'At 1st level, you discover innate magical abilities within yourself that are based on your giant heritage. Select one of the giant types from the Mark of the Ordning table. At 1st and 3rd level, you learn the spells associated with your choice, as shown in the table. These spells count as sorcerer spells for you, but they don''t count against your number of sorcerer spells known. Mark of the Ordning table: Cloud - 1st level: Fog Cloud, Minor Illusion; 3rd level: Invisibility. Fire - 1st level: Burning Hands, Fire Bolt; 3rd level: Flaming Sphere. Frost - 1st level: Armor of Agathys, Ray of Frost; 3rd level: Hold Person. Hill - 1st level: Heroism, Shillelagh; 3rd level: Enlarge/Reduce. Stone - 1st level: Entangle, Resistance; 3rd level: Spike Growth. Storm - 1st level: Shocking Grasp, Thunderwave; 3rd level: Gust of Wind.'),
(164, 'Soul of Lost Ostoria', 6, 'Starting at 6th level, you gain a benefit whenever you cast one of the spells granted by your Mark of the Ordning Feature. Cloud Giant: Immediately after you cast any of your Mark of the Ordning spells, you can magically teleport as a bonus action. You teleport to an unoccupied space you can see that is no farther away than a number of feet equal to 10 + your Constitution modifier. Fire Giant: You gain a bonus to the damage rolls of your Mark of the Ordning spells. The bonus equals your Constitution modifier (minimum of +1). Frost Giant: Immediately after you cast any of your Mark of the Ordning spells, you gain temporary hit points equal to your Constitution modifier (minimum of 1). If the spell is Armor of Agathys, you instead increase its temporary hit points by an amount equal to your Constitution modifier (minimum of 1). Hill Giant: Immediately after you cast any of your Mark of the Ordning spells, you can target up to two creatures within 5 feet of you that you can see. Each target must succeed on a Strength saving throw against your spell save DC or be pushed a number of feet away from you equal to 5 + your Constitution modifier (minimum of +1). A target can choose to fail this save. Stone Giant: Immediately after you cast any of your Mark of the Ordning spells, you gain a bonus to AC equal to your Constitution modifier (minimum of +1) until the end of your next turn. Storm Giant: Immediately after you cast any of your Mark of the Ordning spells, up to three creatures of your choice that you can see within 30 feet of you take lightning damage equal to your Constitution modifier (minimum of 1).'),
(164, 'Rage of Fallen Ostoria', 14, 'Starting at 14th level, you gain the ability to channel the souls of your ancestors into your physical form. When you start casting a sorcerer spell on your turn and expend a spell slot, you can increase your size by one category – from Medium to Large, for example. This increase lasts for 1 minute. It ends early if you die or are incapacitated. Until it ends, you gain the following benefits: Your current hit points and your hit point maximum both increase by 1 per sorcerer level. Your reach increases by 5 feet. Your walking speed increases by 5 feet. You have advantage on Strength checks and Strength saving throws. You gain a bonus to the damage rolls of your melee weapon attacks; the bonus equals your Constitution modifier (minimum of +1). Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(164, 'Blessing of the All Father', 18, 'At 18th level, your Constitution score increases by 2, up to a maximum of 22. In addition, you can now use Rage of Fallen Ostoria twice between rests, but no more than once on a turn. If you use that feature while under its effects, its increases to your size, hit points, reach, and walking speed are cumulative.');

-- Subclasse: Phoenix Sorcery (UA) (ID: 165)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(165, 'Ignite', 1, 'At 1st level, you gain the ability to start fires with a touch. As an action, you can magically ignite a flammable object you touch with your hand—an object such as a torch, a piece of tinder, or the hem of drapes.'),
(165, 'Mantle of Flame', 1, 'Starting at 1st level, you can unleash the phoenix fire that blazes within you. As a bonus action, you magically wreathe yourself in swirling fire, as your eyes glow like hot coals. For 1 minute, you gain the following benefits: You shed bright light in a 30-foot radius and dim light for an additional 30 feet. Any creature takes fire damage equal to your Charisma modifier if it hits you with a melee attack from within 5 feet of you or if it touches you. Whenever you roll fire damage on your turn, the roll gains a bonus equal to your Charisma modifier. Once you use this feature, you can''t use it again until you finish a long rest.'),
(165, 'Phoenix Spark', 6, 'Starting at 6th level, the fiery energy within you grows restless and vengeful. In the face of defeat, it surges outward to preserve you in a fiery roar. If you are reduced to 0 hit points, you can use your reaction to draw on the spark of the phoenix. You are instead reduced to 1 hit point, and each creature within 10 feet of you takes fire damage equal to half your sorcerer level + your Charisma modifier. If you use this feature while under the effects of your Mantle of Flame, this feature instead deals fire damage equal to your sorcerer level + double your Charisma modifier, and your Mantle of Flame immediately ends. Once you use this feature, you can''t use it again until you finish a long or long rest.'),
(165, 'Nourishing Fire', 14, 'Starting at 14th level, your fire spells soothe and restore you. When you expend a spell slot to cast a spell that includes a fire damage roll, you regain hit points equal to the slot''s level + your Charisma modifier.'),
(165, 'Form of the Phoenix', 18, 'At 18th level, you finally master the spark of fire that dances within you. While under the effect of your Mantle of Flame feature, you gain additional benefits: You have a flying speed of 40 feet and can hover. You have resistance to all damage. If you use your Phoenix Spark, that feature deals an extra 20 fire damage to each creature.');

-- Subclasse: Psionic Soul (UA) (ID: 166)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(166, 'Psionic Origin', 1, 'As a Psionic Soul sorcerer, you decide how you acquired your powers. Were you born with them, and did they manifest throughout childhood? Or did an extraordinary event later in life leave you shining with psionic awareness?'),
(166, 'Psionic Talent', 1, 'Starting at 1st-level you harbor a wellspring of psionic power within yourself, an energy that ebbs and flows as you channel it in various ways. This power is represented by your Psionic Talent die, the starting size of which is a d6.'),
(166, 'Psi Replenishment', 1, 'At 1st-level, as a bonus action, you can calm your mind for a moment and restore your Psionic Talent die to its starting size. You then can’t use Psi Replenishment again until you finish a long rest.'),
(166, 'Psychic Strike', 6, 'At 6th-level, you have learned to channel additional psychic energy into your spells. Immediately after you deal damage to a creature with a sorcerer spell for which you expend a spell slot, you can roll your Psionic Talent die and also deal psychic damage to that creature equal to the number rolled. You can deal this extra damage only once per turn.'),
(166, 'Mind Over Body', 14, 'When you reach 14th-level, you can now use the psi that flows through you to give your body extraordinary abilities. As a bonus action, you can roll your Psionic Talent die and spend 1 or more sorcery points to magically transform yourself for a number of hours equal to the number rolled. Until the transformation ends, you gain one of the following benefits of your choice for each sorcery point you spent, choosing a different benefit for each point: You can see any invisible creature within 60 feet of you, provided it isn’t behind total cover. You gain a flying speed equal to your walking speed, and you can hover. You gain a swimming speed equal to twice your walking speed, and you can breathe underwater. Your body, along with any equipment you are wearing or carrying, becomes pliable. You can move through any space as narrow as 1 inch without squeezing, and you can spend 5 feet of movement to escape from nonmagical restraints or being grappled.'),
(166, 'Psychic Aura', 18, 'At 18th-level, if your Psionic Talent die is available, you can unleash your psionic power in a crackling aura of psychic energy; as a bonus action, you can magically radiate this transparent, 30-foot radius aura for 1 minute or until you’re incapacitated or lose the use of your Psionic Talent die. Whenever a creature starts its turn in the aura or moves into it for the first time on a turn, you can roll your Psionic Talent die and deal psychic damage to the creature, equaling the number rolled plus your Charisma modifier. If the creature takes any of this damage, its speed is halved until the start of its next turn.');

-- Subclasse: Sea Sorcery (UA) (ID: 167)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(167, 'Soul of the Sea', 1, 'At 1st level, your tie to the sea grants you the ability to breathe underwater, and you have a swim speed equal to your walking speed.'),
(167, 'Curse of the Sea', 1, 'When you choose this origin at 1st level, you learn the secret of infusing your spells with a watery curse. When you hit a creature with a cantrip’s attack or when a creature fails a saving throw against your cantrip, you can curse the target until the end of your next turn or until you curse a different creature with this feature. Once per turn when you cast a spell, you can trigger the curse if that spell deals cold or lightning damage to the cursed target or forces it to move. Doing so subjects the target to the appropriate additional effect below, and then the curse ends if the spell isn’t a cantrip (you choose the effect to use if more than one effect applies): Cold Damage. If the affected target takes cold damage from your spell, the target’s speed is also reduced by 15 feet until the end of your next turn. If the spell already reduces the target’s speed, use whichever reduction is greater. Lightning Damage. If the affected target takes lightning damage from your spell, the target takes additional lightning damage equal to your Charisma modifier. Forced Movement. If the target is moved by your spell, increase the distance it is moved by 15 feet.'),
(167, 'Watery Defense', 6, 'At 6th level, you gain resistance to fire damage. You also gain the ability to defend yourself by momentarily assuming a watery form. As a reaction when you are hit by an attack and take bludgeoning, piercing, or slashing damage from it, you can reduce that damage by an amount equal to your sorcerer level plus your Charisma score, and then you can move up to 30 feet without provoking opportunity attacks. Once you use this special reaction, you can’t use it again until you finish a short or long rest.'),
(167, 'Shifting Form', 14, 'Starting at 14th level, you gain the ability to enter a liquid state while moving. When you move on your turn, you take only half damage from opportunity attacks, and you can move through any enemy’s space but can’t willingly end your move there. On your turn, you can move through any space that is at least 3 inches in diameter and do so without squeezing. When you stop moving, the regular squeezing rules apply if you’re in a space one size smaller than you. You can’t willingly stop in a space smaller than that, and if you’re forced to do so, you immediately flow to the nearest space that can fit you, back along the path of your movement.'),
(167, 'Water Soul', 18, 'Starting at 18th level, your being is altered by the power of the sea. You gain the following benefits: You no longer need to eat, drink, or sleep. A critical hit against you becomes a normal hit. You have resistance to bludgeoning, piercing, and slashing damage.');

-- Subclasse: Shadow (UA) (ID: 168)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(168, 'Eyes of the Dark', 1, 'From 1st level, you have darkvision with a range of 60 feet. You can cast darkness by spending 1 sorcery point. You can see through any darkness spell you cast using this ability.'),
(168, 'Strength of the Grave', 1, 'Starting at 1st level, your existence in a twilight state between life and death makes you difficult to defeat. Whenever damage reduces you to 0 hit points, you can make a Constitution saving throw (DC 5 + the damage taken). On a success, you instead drop to 1 hit point. You cannot use this feature if you are reduced to 0 hit points by radiant damage or by a critical hit.'),
(168, 'Hound of Ill Omen', 6, 'At 6th level, you gain the ability to call forth a howling creature of darkness to harass your foes. As a bonus action, you can spend 3 sorcery points to summon a hound of ill omen to target one creature you can see. The hound uses a dire wolf''s statistics with the following changes: The hound is size Medium. It can move through other creatures and objects as if they were difficult terrain. The hound takes 5 force damage if it ends its turn inside an object. At the start of its turn, the hound automatically knows its target''s location. If the target was hidden, it is no longer hidden from the hound. The hound appears in an unoccupied space of your choice within 30 feet of the target. Roll initiative for the hound. On its turn, it can move only toward its target by the most direct route, and it can use its action only to attack its target. The hound makes opportunity attacks, but only against its target. Additionally, the target has disadvantage on all saving throws against your spells while the hound is within 5 feet of it. The hound disappears if it is reduced to 0 hit points, if its target is reduced to 0 hit points, or after 5 minutes.'),
(168, 'Shadow Walk', 14, 'At 14th level, you gain the ability to step from one shadow into another. When you are in dim light or darkness, as a bonus action, you can teleport up to 120 feet to an unoccupied space you can see that is also in dim light or darkness.'),
(168, 'Shadow Form', 18, 'At 18th level, you can spend 3 sorcery points to transform yourself into a shadow form as a bonus action. In this form, you have resistance to all damage except force damage, and you can move through other creatures and objects as if they were difficult terrain. You take 5 force damage if you end your turn inside an object. You remain in this form for 1 minute.');

-- Subclasse: Stone Sorcery (UA) (ID: 169)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(169, 'Bonus Proficiencies', 1, 'At 1st level, you gain proficiency with shields, simple weapons, and martial weapons.'),
(169, 'Metal Magic', 1, 'Your affinity for metal gives you the option to learn some non-sorcerer spells that focus on weapon attacks. When your Spellcasting feature lets you learn a sorcerer spell of 1st level or higher, you can select the spell from the following list of spells, in addition to the sorcerer spell list. You must otherwise obey all the restrictions for selecting the spell, and it becomes a sorcerer spell for you.'),
(169, 'Stone''s Durability', 1, 'At 1st level, your connection to stone gives you extra fortitude. Your hit point maximum increases by 1, and it increases by 1 again whenever you gain a level in this class. As an action, you can gain a base AC of 13 + your Constitution modifier if you aren’t wearing armor, and your skin assumes a stony appearance. This effect lasts until you end it as a bonus action, you are incapacitated, or you don armor other than a shield.'),
(169, 'Stone Aegis', 6, 'Starting at 6th level, your command of earth magic grows stronger, allowing you to harness it for your allies’ protection. As a bonus action, you can grant an aegis to one allied creature you can see within 60 feet of you. The aegis is a dim, gray aura of earth magic that protects the target. Any bludgeoning, piercing, or slashing damage the target takes is reduced by 2 + your sorcerer level divided by 4. This effect lasts for 1 minute, until you use it again, or until you are incapacitated. In addition, when a creature you can see within 60 feet of you hits the protected target with a melee attack, you can use your reaction to teleport to an unoccupied space you can see within 5 feet of the attacker. You can teleport only if you and the attacker are on the same surface. You can then make one melee weapon attack against the attacker. If that attack hits, it deals an extra 1d10 force damage. This extra damage increases to 2d10 at 11th level and 3d10 at 17th level.'),
(169, 'Stone''s Edge', 14, 'Starting at 14th level, your mastery of earth magic allows you to add the force of elemental earth to your spells. When you cast a spell that deals damage, choose one creature damaged by that spell on the round you cast it. That creature takes extra force damage equal to half your sorcerer level. This feature can be used only once per casting of a spell.'),
(169, 'Earth Master''s Aegis', 18, 'Beginning at 18th level, when you use your Stone’s Aegis to protect an ally, you can choose up to three creatures to gain its benefits.');

-- Subclasse: Mage of Prismari (UA) (ID: 170)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(170, 'Creative Skills', 1, 'You gain proficiency in two of the following skills of your choice: Acrobatics, Athletics, Nature, or Performance.'),
(170, 'Kinetic Artistry', 1, 'You can Dash as a bonus action. When you take this bonus action, choose one of the following additional effects: Boreal Sweep. Icy water swirls around you. Until the end of your turn, you can move across the surface of water as if it were harmless solid ground. Additionally, when you leave a space within 5 feet of a creature, you can force that creature to make a Strength saving throw against your spell save DC. On a failed save, the creature is knocked prone. A creature can be affected by the water only once each turn. Scorching Whirl. Flames wreath your steps. Once before the end of your turn, you can force each creature within 5 feet of you to make a Dexterity saving throw against your spell save DC. On a failure, a creature takes fire damage equal to 1d4 + your spellcasting modifier. Thunderlight Jaunt. You take on a nimble lightning form. Until the end of your turn, you can move through the space of other creatures, and you do not provoke opportunity attacks. If you end your turn inside a creature’s space, you are pushed into the nearest unoccupied space. You can use a bonus action in this way a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(170, 'Favored Medium', 6, 'You have honed your forms of elemental expression to best suit your ideas. Choose one of the following damage types: cold, fire, or lightning. You gain resistance to that damage type. Additionally, when you cast a spell using a spell slot that deals the chosen damage type, you emit a spectacular aura of artistry, which extends 5 feet from you in every direction (but not through total cover) and lasts until the end of your next turn. While the aura is active, each creature of your choice has resistance to your chosen damage type while within the aura, as you shape your favored elemental medium around them. You can change your choice of damage type whenever you finish a long rest.'),
(170, 'Focused Expression', 10, 'Honing your talents, you skillfully infuse your motions with even more potent expressions of elemental might. Once per turn when you deal damage to at least one target, you gain an additional effect determined by the damage type chosen for your Favored Medium feature: Cold. One of the targets of your choice takes an additional 1d6 cold damage and must make a Constitution saving throw against your spell save DC. On a failed save, the target’s speed is reduced by 10 feet until the end of its next turn, as ice mires it. A target can be affected by the ice only once per round. Fire. One of the targets of your choice takes an additional 1d6 fire damage. Fortifying flames then dance around one creature of your choice within 30 feet of you. The chosen creature gains 1d6 temporary hit points. Lightning. One of the targets of your choice takes an additional 1d6 lightning damage and must make a Dexterity saving throw against your spell save DC. On a failed save, the target is unable to take reactions until the end of its next turn, as residual lightning shocks its form.'),
(170, 'Impeccable Physicality', 14, 'Your relentless dedication and training have instilled an outstanding sense of precision and grace in your art. You gain proficiency in Dexterity saving throws if you do not already have it. Additionally, when you make a Dexterity saving throw, you can treat a d20 roll of a 9 or lower as a 10.');

-- Subclasse: Mage of Quandrix (UA) (ID: 171)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(171, 'Quandrix Spells', 1, 'You learn the cantrip Guidance and the 1st-level spell Guiding Bolt. You learn additional spells when you reach certain levels in this class, as shown on the Quandrix Spells table. Each of these spells counts as a class spell for you, but it doesn’t count against the number of spells you know. If you are a wizard, you can add these spells to your spellbook upon learning them, without expending any gold, and prepare them as normal.'),
(171, 'Functions of Probability', 1, 'By iterating on the mathematical patterns of reality, you can nudge chance to tilt around a creature. When you cast a spell using a spell slot that targets at least one creature, you can choose that creature or another creature within 30 feet of it (including yourself) and add one of the following effects: Diminishing Function. The chosen creature must succeed on a Wisdom saving throw against your spell save DC, or the creature must roll a d6 and subtract the number rolled from the next attack roll it takes before the start of your next turn. Supplemental Function. Once before the start of your next turn, the chosen creature can roll a d6 and add the number rolled to an attack roll or a saving throw of its choice. The creature can roll the d6 after rolling the d20 but must decide before any effects of the roll occur.'),
(171, 'Velocity Shift', 6, 'You learn to manipulate kinetic formulas and alter the velocity of another creature. When a creature you can see starts its turn or moves to a space within 30 feet of you, you can use your reaction to force the creature to make a Charisma saving throw against your spell save DC, which it can choose to fail. On a failure, the creature is teleported to an unoccupied space of your choice that you can see within 30 feet of you. You can use your reaction in this way a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(171, 'Null Equation', 10, 'Through careful calculations, you beset your enemies with abstract equations that reduce their might. Once per turn, immediately after dealing damage to a creature, you can force the creature to make a Constitution saving throw against your spell save DC. On a failure, the creature has disadvantage on Strength and Dexterity saving throws, and its weapon attacks deal only half damage. These effects last until the start of your next turn. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(171, 'Quantum Tunneling', 14, 'Your mathematical expertise extends to altering the foundational equations of your very being. You gain resistance to bludgeoning, piercing, and slashing damage. Additionally, you can move through other creatures and objects as if they were difficult terrain, but you take 1d10 force damage for every 5 feet you move while inside another creature or object. If you end your turn inside a creature or an object, you are shunted into the nearest unoccupied space you last occupied.');
