
-- =============================================================================
-- WARLOCK SUBCLASSES
-- =============================================================================

-- The Archfey (ID: 172)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(172, 'Expanded Spell List', 1, 'The Archfey lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Archfey Expanded Spells: 1st level - Faerie Fire, Sleep; 2nd level - Calm Emotions, Phantasmal Force; 3rd level - Blink, Plant Growth; 4th level - Dominate Beast, Greater Invisibility; 5th level - Dominate Person, Seeming.'),
(172, 'Fey Presence', 1, 'Starting at 1st level, your patron bestows upon you the ability to project the beguiling and fearsome presence of the fey. As an action, you can cause each creature in a 10-foot cube originating from you to make a Wisdom saving throw against your warlock spell save DC. The creatures that fail their saving throws are all charmed or frightened by you (your choice) until the end of your next turn. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(172, 'Misty Escape', 6, 'Starting at 6th level, you can vanish in a puff of mist in response to harm. When you take damage, you can use your reaction to turn invisible and teleport up to 60 feet to an unoccupied space you can see. You remain invisible until the start of your next turn or until you attack or cast a spell. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(172, 'Beguiling Defenses', 10, 'Beginning at 10th level, your patron teaches you how to turn the mind-affecting magic of your enemies against them. You are immune to being charmed, and when another creature attempts to charm you, you can use your reaction to attempt to turn the charm back on that creature. The creature must succeed on a Wisdom saving throw against your warlock spell save DC or be charmed by you for 1 minute or until the creature takes any damage.'),
(172, 'Dark Delirium', 14, 'Starting at 14th level, you can plunge a creature into an illusory realm. As an action, choose a creature that you can see within 60 feet of you. It must make a Wisdom saving throw against your warlock spell save DC. On a failed save, it is charmed or frightened by you (your choice) for 1 minute or until your concentration is broken (as if you are concentrating on a spell). This effect ends early if the creature takes any damage. Until this illusion ends, the creature thinks it is lost in a misty realm, the appearance of which you choose. The creature can see and hear only itself, you, and the illusion. You must finish a short or long rest before you can use this feature again.');

-- The Celestial (ID: 173)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(173, 'Expanded Spell List', 1, 'The Celestial lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Celestial Expanded Spells: 1st level - Cure Wounds, Guiding Bolt; 2nd level - Flaming Sphere, Lesser Restoration; 3rd level - Daylight, Revivify; 4th level - Guardian of Faith, Wall of Fire; 5th level - Flame Strike, Greater Restoration.'),
(173, 'Bonus Cantrips', 1, 'At 1st level, you learn the Light and Sacred Flame cantrips. They count as warlock cantrips for you, but they don''t count against your number of cantrips known.'),
(173, 'Healing Light', 1, 'At 1st level, you gain the ability to channel celestial energy to heal wounds. You have a pool of d6s that you spend to fuel this healing. The number of dice in the pool equals 1 + your warlock level. As a bonus action, you can heal one creature you can see within 60 feet of you, spending dice from the pool. The maximum number of dice you can spend at once equals your Charisma modifier (minimum of one die). Roll the dice you spend, add them together, and restore a number of hit points equal to the total. Your pool regains all expended dice when you finish a long rest.'),
(173, 'Radiant Soul', 6, 'Starting at 6th level, your link to the Celestial allows you to serve as a conduit for radiant energy. You have resistance to radiant damage, and when you cast a spell that deals radiant or fire damage, you add your Charisma modifier to one radiant or fire damage roll of that spell against one of its targets.'),
(173, 'Celestial Resistance', 10, 'Starting at 10th level, you gain temporary hit points whenever you finish a long or short rest. These temporary hit points equal your warlock level + your Charisma modifier. Additionally, choose up to five creatures you can see at the end of the rest. Those creatures each gain temporary hit points equal to half your warlock level + your Charisma modifier.'),
(173, 'Searing Vengeance', 14, 'Starting at 14th level, the radiant energy you channel allows you to resist death. When you have to make a death saving throw at the start of your turn, you can instead spring back to your feet with a burst of radiant energy. You regain hit points equal to half your hit point maximum, and then you stand up if you so choose. Each creature of your choice that is within 30 feet of you takes radiant damage equal to 2d8 + your Charisma modifier, and is blinded until the end of the current turn. Once you use this feature, you can''t use it again until you finish a long rest.');

-- The Fathomless (ID: 174)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(174, 'Expanded Spell List', 1, 'The Fathomless lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Fathomless Expanded Spells: 1st level - Create or Destroy Water, Thunderwave; 2nd level - Gust of Wind, Silence; 3rd level - Lightning Bolt, Sleet Storm; 4th level - Control Water, Summon Elemental (Water only); 5th level - Bigby''s Hand (appears as a tentacle), Cone of Cold.'),
(174, 'Tentacle of the Deep', 1, 'At 1st level, you can magically summon a spectral tentacle that strikes at your foes. As a bonus action, you create a 10-foot-long tentacle at a point you can see within 60 feet of you. The tentacle lasts for 1 minute or until you use this feature to create another tentacle. When you create the tentacle, you can make a melee spell attack against one creature within 10 feet of it. On a hit, the target takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn. When you reach 10th level in this class, the damage increases to 2d8. As a bonus action on your turn, you can move the tentacle up to 30 feet and repeat the attack. You can summon the tentacle a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(174, 'Gift of the Sea', 1, 'Also at 1st level, you gain a swimming speed of 40 feet, and you can breathe underwater.'),
(174, 'Oceanic Soul', 6, 'At 6th level, you are now even more at home in the depths. You gain resistance to cold damage. In addition, when you are fully submerged, any creature that is also fully submerged can understand your speech, and you can understand theirs.'),
(174, 'Guardian Coil', 6, 'At 6th level, your Tentacle of the Deeps can defend you and others, interposing itself between them and harm. When you or a creature you can see takes damage while within 10 feet of the tentacle, you can use your reaction to choose one of those creatures and reduce the damage to that creature by 1d8. When you reach 10th level in this class, the damage reduced by the tentacle increases to 2d8.'),
(174, 'Fathomless Plunge', 14, 'When you reach 14th level, you can magically open temporary conduits to watery destinations. As an action, you can teleport yourself and up to five other willing creatures that you can see within 30 feet of you. Amid a whirl of tentacles, you all vanish and then reappear up to 1 mile away in a body of water you''ve seen (pond size or larger) or within 30 feet of it, each of you appearing in an unoccupied space within 30 feet of the others. Once you use this feature, you can''t use it again until you finish a short or long rest.');

-- The Fiend (ID: 175)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(175, 'Expanded Spell List', 1, 'The Fiend lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Fiend Expanded Spells: 1st level - Burning Hands, Command; 2nd level - Blindness/Deafness, Scorching Ray; 3rd level - Fireball, Stinking Cloud; 4th level - Fire Shield, Wall of Fire; 5th level - Flame Strike, Hallow.'),
(175, 'Dark One''s Blessing', 1, 'Starting at 1st level, when you reduce a hostile creature to 0 hit points, you gain temporary hit points equal to your Charisma modifier + your warlock level (minimum of 1).'),
(175, 'Dark One''s Own Luck', 6, 'Starting at 6th level, you can call on your patron to alter fate in your favor. When you make an ability check or a saving throw, you can use this feature to add a d10 to your roll. You can do so after seeing the initial roll but before any of the roll''s effects occur. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(175, 'Fiendish Resilience', 10, 'Starting at 10th level, you can choose one damage type when you finish a short or long rest. You gain resistance to that damage type until you choose a different one with this feature. Damage from magical weapons or silver weapons ignores this resistance.'),
(175, 'Hurl Through Hell', 14, 'Starting at 14th level, when you hit a creature with an attack, you can use this feature to instantly transport the target through the lower planes. The creature disappears and hurtles through a nightmare landscape. At the end of your next turn, the target returns to the space it previously occupied, or the nearest unoccupied space. If the target is not a fiend, it takes 10d10 psychic damage as it reels from its horrific experience. Once you use this feature, you can''t use it again until you finish a long rest.');

-- The Genie (ID: 176)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(176, 'Expanded Spell List', 1, 'At 1st level, the Genie lets you choose from an expanded list of spells when you learn a warlock spell. The Genie Expanded Spells table shows the genie spells that are added to the warlock spell list for you, along with the spells associated in the table with your patron''s kind: dao, djinni, efreeti, or marid. Genie Expanded Spells: 1st level - Detect Evil and Good (Dao: Sanctuary, Djinni: Thunderwave, Efreeti: Burning Hands, Marid: Fog Cloud); 2nd level - Phantasmal Force (Dao: Spike Growth, Djinni: Gust of Wind, Efreeti: Scorching Ray, Marid: Blur); 3rd level - Create Food and Water (Dao: Meld into Stone, Djinni: Wind Wall, Efreeti: Fireball, Marid: Sleet Storm); 4th level - Phantasmal Killer (Dao: Stone Shape, Djinni: Greater Invisibility, Efreeti: Fire Shield, Marid: Control Water); 5th level - Creation (Dao: Wall of Stone, Djinni: Seeming, Efreeti: Flame Strike, Marid: Cone of Cold); 9th level - Wish.'),
(176, 'Genie''s Vessel', 1, 'Also at 1st level, your patron gifts you a magical vessel that grants you a measure of the genie''s power. The vessel is a Tiny object, and you can use it as a spellcasting focus for your warlock spells. You decide what the object is, or you can determine what it is randomly by rolling on the Genie''s Vessel table. While you are touching the vessel, you can use it in the following ways: Bottled Respite: As an action, you can magically vanish and enter your vessel, which remains in the space you left. The interior of the vessel is an extradimensional space in the shape of a 20-foot-radius cylinder, 20 feet high, and resembles your vessel. The interior is appointed with cushions and low tables and is a comfortable temperature. While inside, you can hear the area around your vessel as if you were in its space. You can remain inside the vessel up to a number of hours equal to twice your proficiency bonus. You exit the vessel early if you use a bonus action to leave, if you die, or if the vessel is destroyed. When you exit the vessel, you appear in the unoccupied space closest to it. Any objects left in the vessel remain there until carried out, and if the vessel is destroyed, every object stored there harmlessly appears in the unoccupied spaces closest to the vessel''s former space. Once you enter the vessel, you can''t enter again until you finish a long rest. Genie''s Wrath: Once during each of your turns when you hit with an attack roll, you can deal extra damage to the target equal to your proficiency bonus. The type of this damage is determined by your patron: bludgeoning (dao), thunder (djinni), fire (efreeti), or cold (marid). The vessel''s AC equals your spell save DC. Its hit points equal your warlock level plus your proficiency bonus, and it is immune to poison and psychic damage. If the vessel is destroyed or you lose it, you can perform a 1-hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and the previous vessel is destroyed if it still exists. The vessel vanishes in a flare of elemental power when you die.'),
(176, 'Elemental Gift', 6, 'At 6th level, you begin to take on characteristics of your patron''s kind. You now have resistance to a damage type determined by your patron''s kind: bludgeoning (dao), thunder (djinni), fire (efreeti), or cold (marid). In addition, as a bonus action, you can give yourself a flying speed of 30 feet that lasts for 10 minutes, during which you can hover. You can use this bonus action a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(176, 'Sanctuary Vessel', 10, 'At 10th level, when you enter your Genie''s Vessel via the Bottled Respite feature, you can now choose up to five willing creatures that you can see at the end of the rest. Those creatures each gain temporary hit points equal to half your warlock level + your Charisma modifier.'),
(176, 'Limited Wish', 14, 'At 14th level, you entreat your patron to grant you a small wish. As an action, you can speak your desire to your Genie''s Vessel, requesting the effect of one spell that is 6th level or lower and has a casting time of 1 action. The spell can be from any class''s spell list, and you don''t need to meet the requirements in that spell, including costly components: the spell simply takes effect as part of this action. Once you use this feature, you can''t use it again until you finish 1d4 long rests.');

-- The Great Old One (ID: 177)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(177, 'Expanded Spell List', 1, 'The Great Old One lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Great Old One Expanded Spells: 1st level - Dissonant Whispers, Tasha''s Hideous Laughter; 2nd level - Detect Thoughts, Phantasmal Force; 3rd level - Clairvoyance, Sending; 4th level - Dominate Beast, Evard''s Black Tentacles; 5th level - Dominate Person, Telekinesis.'),
(177, 'Awakened Mind', 1, 'Starting at 1st level, your alien knowledge gives you the ability to touch the minds of other creatures. You can telepathically speak to any creature you can see within 30 feet of you. You don''t need to share a language with the creature for it to understand your telepathic utterances, but the creature must be able to understand at least one language.'),
(177, 'Entropic Ward', 6, 'At 6th level, you learn to magically ward yourself against attack and to turn an enemy''s failed strike into good luck for yourself. When a creature makes an attack roll against you, you can use your reaction to impose disadvantage on that roll. If the attack misses you, your next attack roll against the creature has advantage if you make it before the end of your next turn. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(177, 'Thought Shield', 10, 'Starting at 10th level, your thoughts can''t be read by telepathy or other means unless you allow it. You also have resistance to psychic damage, and whenever a creature deals psychic damage to you, that creature takes the same amount of damage that you do.'),
(177, 'Create Thrall', 14, 'At 14th level, you gain the ability to infect a humanoid''s mind with the alien magic of your patron. You can use your action to touch an incapacitated humanoid. That creature is then charmed by you until a Remove Curse spell is cast on it, the charmed condition is removed from it, or you use this feature again. You can communicate telepathically with the charmed creature as long as the two of you are on the same plane of existence.');

-- The Hexblade (ID: 178)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(178, 'Expanded Spell List', 1, 'The Hexblade lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Hexblade Expanded Spells: 1st level - Shield, Wrathful Smite; 2nd level - Blur, Branding Smite; 3rd level - Blink, Elemental Weapon; 4th level - Phantasmal Killer, Staggering Smite; 5th level - Banishing Smite, Cone of Cold.'),
(178, 'Hexblade''s Curse', 1, 'Starting at 1st level, you gain the ability to place a baleful curse on someone. As a bonus action, choose one creature you can see within 30 feet of you. The target is cursed for 1 minute. The curse ends early if the target dies, you die, or you are incapacitated. Until the curse ends, you gain the following benefits: You gain a bonus to damage rolls against the cursed target. The bonus equals your proficiency bonus. Any attack roll you make against the cursed target is a critical hit on a roll of 19 or 20 on the d20. If the cursed target dies, you regain hit points equal to your warlock level + your Charisma modifier. You can''t use this feature again until you finish a short or long rest.'),
(178, 'Hex Warrior', 1, 'At 1st level, you acquire the training necessary to effectively arm yourself for battle. You gain proficiency with medium armor, shields, and martial weapons. The influence of your patron also allows you to mystically channel your will through a particular weapon. Whenever you finish a long rest, you can touch one weapon that you are proficient with and that lacks the two-handed property. When you attack with that weapon, you can use your Charisma modifier, instead of Strength or Dexterity, for the attack and damage rolls. This benefit lasts until you finish a long rest. If you later gain the Pact of the Blade feature, this benefit extends to every pact weapon you conjure with that feature, no matter the weapon''s type.'),
(178, 'Accursed Specter', 6, 'Starting at 6th level, you can curse the soul of a person you slay, temporarily binding it in your service. When you slay a humanoid, you can cause its spirit to rise from its corpse as a specter, the statistics of which are in the Monster Manual. When the specter appears, it gains temporary hit points equal to half your warlock level. Roll initiative for the specter, which has its own turns. It obeys your verbal commands, and it gains a special bonus to its attack rolls equal to your Charisma modifier (minimum of +0). The specter remains in your service until the end of your next long rest, at which point it vanishes to the afterlife. Once you bind a specter with this feature, you can''t use the feature again until you finish a long rest.'),
(178, 'Armor of Hexes', 10, 'At 10th level, your hex grows more powerful. If the target cursed by your Hexblade''s Curse hits you with an attack roll, roll a d6. On a 4 or higher, the attack instead misses you.'),
(178, 'Master of Hexes', 14, 'Starting at 14th level, you can spread your Hexblade''s Curse from a slain creature to another creature. When the creature cursed by your Hexblade''s Curse dies, you can apply the curse to a different creature you can see within 30 feet of you, provided you aren''t incapacitated. When you apply the curse in this way, you don''t regain hit points from the death of the previously cursed creature.');

-- The Undead (ID: 179)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(179, 'Expanded Spell List', 1, 'The Undying lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Undying Expanded Spells: 1st level - False Life, Ray of Sickness; 2nd level - Blindness/Deafness, Silence; 3rd level - Feign Death, Speak with Dead; 4th level - Aura of Life, Death Ward; 5th level - Contagion, Legend Lore.'),
(179, 'Among the Dead', 1, 'Starting at 1st level, you learn the Spare the Dying cantrip, which counts as a warlock cantrip for you. You also have advantage on saving throws against any disease. Additionally, undead have difficulty harming you. If an undead targets you directly with an attack or a harmful spell, that creature must make a Wisdom saving throw against your spell save DC (an undead needn''t make the save when it includes you in an area effect, such as the explosion of Fireball). On a failed save, the creature must choose a new target or forfeit targeting someone instead of you, potentially wasting the attack or spell. On a successful save, the creature is immune to this effect for 24 hours. An undead is also immune to this effect for 24 hours if you target it with an attack or a harmful spell.'),
(179, 'Defy Death', 6, 'Starting at 6th level, you can give yourself vitality when you cheat death or when you help someone else cheat it. You can regain hit points equal to 1d8 + your Constitution modifier (minimum of 1 hit point) when you succeed on a death saving throw or when you stabilize a creature with Spare the Dying. Once you use this feature, you can''t use it again until you finish a long rest.'),
(179, 'Undying Nature', 10, 'Beginning at 10th level, you can hold your breath indefinitely, and you don''t require food, water, or sleep, although you still require rest to reduce exhaustion and still benefit from finishing short and long rests. In addition, you age at a slower rate. For every 10 years that pass, your body ages only 1 year, and you are immune to being magically aged.'),
(179, 'Indestructible Life', 14, 'When you reach 14th level, you partake of some of the true secrets of the Undying. On your turn, you can use a bonus action to regain hit points equal to 1d8 + your warlock level. Additionally, if you put a severed body part of yours back in place when you use this feature, the part reattaches. Once you use this feature, you can''t use it again until you finish a short or long rest.');

-- The Undying (ID: 180)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(180, 'Expanded Spell List', 1, 'The Undying lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Undying Expanded Spells: 1st level - False Life, Ray of Sickness; 2nd level - Blindness/Deafness, Silence; 3rd level - Feign Death, Speak with Dead; 4th level - Aura of Life, Death Ward; 5th level - Contagion, Legend Lore.'),
(180, 'Among the Dead', 1, 'Starting at 1st level, you learn the Spare the Dying cantrip, which counts as a warlock cantrip for you. You also have advantage on saving throws against any disease. Additionally, undead have difficulty harming you. If an undead targets you directly with an attack or a harmful spell, that creature must make a Wisdom saving throw against your spell save DC (an undead needn''t make the save when it includes you in an area effect, such as the explosion of Fireball). On a failed save, the creature must choose a new target or forfeit targeting someone instead of you, potentially wasting the attack or spell. On a successful save, the creature is immune to this effect for 24 hours. An undead is also immune to this effect for 24 hours if you target it with an attack or a harmful spell.'),
(180, 'Defy Death', 6, 'Starting at 6th level, you can give yourself vitality when you cheat death or when you help someone else cheat it. You can regain hit points equal to 1d8 + your Constitution modifier (minimum of 1 hit point) when you succeed on a death saving throw or when you stabilize a creature with Spare the Dying. Once you use this feature, you can''t use it again until you finish a long rest.'),
(180, 'Undying Nature', 10, 'Beginning at 10th level, you can hold your breath indefinitely, and you don''t require food, water, or sleep, although you still require rest to reduce exhaustion and still benefit from finishing short and long rests. In addition, you age at a slower rate. For every 10 years that pass, your body ages only 1 year, and you are immune to being magically aged.'),
(180, 'Indestructible Life', 14, 'When you reach 14th level, you partake of some of the true secrets of the Undying. On your turn, you can use a bonus action to regain hit points equal to 1d8 + your warlock level. Additionally, if you put a severed body part of yours back in place when you use this feature, the part reattaches. Once you use this feature, you can''t do it again until you finish a short or long rest.');

-- The Celestial (UA) (ID: 181)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(181, 'Expanded Spell List', 1, 'The Celestial lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Celestial Expanded Spells: 1st level - Burning Hands, Cure Wounds; 2nd level - Flaming Sphere, Lesser Restoration; 3rd level - Daylight, Revivify; 4th level - Guardian of Faith, Wall of Fire; 5th level - Flame Strike, Greater Restoration.'),
(181, 'Bonus Cantrips', 1, 'At 1st level, you learn the Light and Sacred Flame cantrips. They count as warlock cantrips for you, but they don''t count against your number of cantrips known.'),
(181, 'Healing Light', 1, 'At 1st level, you gain the ability to channel celestial energy to heal wounds. You have a pool of d6s that you spend to fuel this healing. The number of dice in the pool equals 1 + your warlock level. As a bonus action, you can touch a creature and heal it, spending dice from the pool. The maximum number of dice you can spend at once equals your Charisma modifier (minimum of one die). Roll the dice you spend, add them together, and restore a number of hit points equal to the total. Your pool regains all expended dice when you finish a long rest.'),
(181, 'Radiant Soul', 6, 'Starting at 6th level, your link to the Celestial allows you to serve as a conduit for radiant energy. You have resistance to radiant damage, and when you cast a spell that deals radiant or fire damage, you add your Charisma modifier to that damage against one target of your choice.'),
(181, 'Celestial Resistance', 10, 'Starting at 10th level, you gain temporary hit points whenever you finish a short or long rest. These temporary hit points equal your warlock level + your Charisma modifier. Additionally, choose up to five creatures you can see at the end of the rest. Those creatures each gain temporary hit points equal to half your warlock level + your Charisma modifier.'),
(181, 'Searing Vengeance', 14, 'Starting at 14th level, the radiant energy you channel allows you to overcome grievous injuries. When you have to make a death saving throw at the start of your turn, you can instead spring back to your feet with a burst of radiant energy. You regain hit points equal to half your hit point maximum, and then you stand up, if you so choose. Each creature of your choice that is within 30 feet of you takes radiant damage equal to 2d8 + your Charisma modifier, and it is blinded until the end of the current turn. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Genie (UA) (ID: 182)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(182, 'Expanded Spell List', 1, 'The Genie lets you choose from an expanded list of spells when you learn a warlock spell. The Genie Expanded Spells table shows the genie spells that are added to the warlock spell list for you, along with the spells associated in the table with your patron''s kind: dao, djinni, efreeti, or marid. Genie Expanded Spells Spell Level Genie Spells Dao Spells Djinni Spells Efreeti Spells Marid Spells 1st Detect Evil and Good Sanctuary Thunderwave Burning Hands Fog Cloud 2nd Phantasmal Force Spike Growth Gust of Wind Scorching Ray Blur 3rd Create Food and Water Meld into Stone Wind Wall Fireball Sleet Storm 4th Phantasmal Killer Stone Shape Greater Invisibility Fire Shield Control Water 5th Creation Wall of Stone Seeming Flame Strike Cone of Cold 9th Wish — — — —'),
(182, 'Genie''s Vessel', 1, 'At 1st level, your patron gifts you a magical vessel that grants you a measure of the genie''s power. The vessel is a Tiny object, and you can use it as a spellcasting focus for your warlock spells. You decide what the object is, or you can determine what it is randomly by rolling on the Genie''s Vessel table. Genie''s Vessel d6 Vessel 1 Oil lamp 2 Urn 3 Ring with a compartment 4 Stoppered bottle 5 Hollow statuette 6 Ornate lantern While you are touching the vessel, you can use it in the following ways: Bottled Respite: As an action, you can magically vanish and enter your vessel, which remains in the space you left. The interior of the vessel is an extradimensional space in the shape of a 20-foot-radius cylinder, 20 feet high, and resembles your vessel. The interior is comfortably appointed with cushions and low tables and is a comfortable temperature. While inside, you can hear the area around your vessel as if you were in its space. You can remain inside the vessel up to a number of hours equal to twice your proficiency bonus. You exit the vessel early if you use a bonus action to leave, if you die, or if the vessel is destroyed. When you exit the vessel, you appear in the unoccupied space closest to it. Any objects left in the vessel remain there until carried out, and if the vessel is destroyed, every object stored there harmlessly appears in the unoccupied spaces closest to the vessel''s former space. Once you enter the vessel, you can''t enter again until you finish a long rest. Genie''s Wrath: Once during each of your turns when you hit with an attack roll, you can deal extra damage to the target equal to your proficiency bonus. The type of this damage is determined by your patron: bludgeoning (dao), thunder (djinni), fire (efreeti), or cold (marid). The vessel''s AC equals your spell save DC. Its hit points equal your warlock level plus your proficiency bonus, and it is immune to poison and psychic damage. If the vessel is destroyed or you lose it, you can perform a 1-hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and the previous vessel is destroyed if it still exists. The vessel vanishes in a flare of elemental power when you die.'),
(182, 'Elemental Gift', 6, 'At 6th level, you begin to take on characteristics of your patron''s kind. You now have resistance to a damage type determined by your patron''s kind: bludgeoning (dao), thunder (djinni), fire (efreeti), or cold (marid). In addition, as a bonus action, you can give yourself a flying speed of 30 feet that lasts for 10 minutes, during which you can hover. You can use this bonus action a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(182, 'Sanctuary Vessel', 10, 'At 10th level, when you enter your Genie''s Vessel via the Bottled Respite feature, you can now choose up to five willing creatures that you can see within 30 feet of you, and the chosen creatures are drawn into the vessel with you. As a bonus action, you can eject any number of creatures from the vessel, and everyone is ejected if you leave or the vessel is destroyed. In addition, anyone (including you) who remains within the vessel for at least 10 minutes gains the benefit of finishing a short rest, and anyone can add your proficiency bonus to the number of hit points they regain if they spend any Hit Dice as part of a short rest there.'),
(182, 'Limited Wish', 14, 'At 14th level, you can entreat your patron to grant you a small wish. As an action, you can speak your desire to your Genie''s Vessel, requesting the effect of one spell that is 6th level or lower and has a casting time of 1 action. The spell can be from any class''s spell list, and you don''t need to meet the requirements in that spell, including costly components; the spell simply takes effect as part of this action. Once you use this feature, you can''t use it again until you finish 1d4 long rests.');

-- Ghost In The Machine (UA) (ID: 183)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(183, 'Expanded Spell List', 1, 'The Ghost in the Machine lets you choose from an expanded list of spells when you learn a warlock spell. You gain the On/Off* cantrip, and the following new spells are added to the warlock spell list for you. Spells marked with an asterisk can be found in Unearthed Arcana: Modern Magic. Ghost in the Machine Expanded Spells: 1st level - Infallible Relay*, Remote Access*; 2nd level - Arcane Hacking*, Digital Phantom*; 3rd level - Haywire*, Invisibility to Cameras*; 4th level - Conjure Knowbot*, System Backdoor*; 5th level - Shutdown*, Synchronicity*.'),
(183, 'Information Surge', 1, 'At 1st level, you gain the ability to temporarily render computerized devices inoperable. As an action, you can target a computerized device within 30 feet of you. If the targeted device is held or otherwise actively used by a living creature, that creature must make an Intelligence saving throw against your spell save DC. On a failed save, the targeted device ceases to function until the end of your next turn. If the targeted device is not held or used by a creature, the DM makes a special saving throw for the device with disadvantage and a +0 modifier. Certain shielded devices might negate the disadvantage, at the DM''s determination. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(183, 'Wire Walk', 6, 'Starting at 6th level, you gain the ability to travel short distances over electrical wires, data lines, or telephone cables. As a bonus action, you can touch a device or socket connected to a hardwired network and teleport along this network to another device or socket within your line of sight. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(183, 'Personal Encryption', 10, 'Beginning at 10th level, you have learned to apply your innate knowledge of encryption to your thoughts, memories, and presence. You have advantage on saving throws against scrying, thought detection, or any other method of magically learning your whereabouts or reading your thoughts. For any such effect that does not grant you a saving throw but which requires the creature targeting you to make an ability check, the check is made with disadvantage.'),
(183, 'Technovirus', 14, 'At 14th level, you gain the ability to infect a humanoid''s body with living circuitry. You can use an action to make a melee attack against a humanoid creature using your spell attack modifier. The target must make a Constitution saving throw against your spell save DC as a techno-organic virus quickly spreads through its body. On a failed save, the target takes 8d10 psychic damage, or half as much damage on a successful one. Additionally, if the target fails the saving throw, you can use an action to issue it a single command, as if you were casting the Command spell. The target makes its saving throw against your command with disadvantage. You can issue this command at any time while the target remains infected. Once you use this feature, you can''t use it again until you finish a long rest, at which point the target is cured of the technovirus. The infection can also be removed with a Lesser Restoration spell.');

-- Hexblade (UA) (ID: 184)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(184, 'Expanded Spell List', 1, 'The Hexblade lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Hexblade Expanded Spells Spell Level Spells 1st Shield , Wrathful Smite 2nd Branding Smite , Magic Weapon 3rd Blink , Elemental Weapon 4th Phantasmal Killer , Staggering Smite 5th Cone of Cold , Destructive Wave'),
(184, 'Hex Warrior', 1, 'At 1st level, you gain proficiency with medium armor, shields, and martial weapons. In addition, when attacking with a melee weapon that you are proficient with and that lacks the two-handed property, you can use your Charisma modifier, instead of Strength or Dexterity, for the attack and damage rolls.'),
(184, 'Hexblade''s Curse', 1, 'Starting at 1st level, you gain the ability to place a baleful curse on someone. As a bonus action, choose one creature you can see within 30 feet of you. The target is cursed for 1 minute. The curse ends early if the target dies, you die, or you are incapacitated. Until the curse ends, you gain the following benefits: You gain a bonus to damage rolls against the cursed target. The bonus equals your proficiency bonus. Any attack roll you make against the cursed target is a critical hit on a roll of 19 or 20 on the d20. If the cursed target dies, you regain hit points equal to your warlock level + your Charisma modifier. You can''t use this feature again until you finish a short or long rest.'),
(184, 'Accursed Specter', 6, 'Starting at 6th level, you can curse the soul of a person you slay, temporarily binding it in your service. When you slay a humanoid, you can cause its spirit to rise from its corpse as a specter, the statistics of which are in the Monster Manual. When the specter appears, it gains temporary hit points equal to half your warlock level. Roll initiative for the specter, which has its own turns. It obeys your verbal commands, and it gains a special bonus to its attack rolls equal to your Charisma modifier (minimum of +0). The specter remains in your service until the end of your next long rest, at which point it vanishes to the afterlife. Once you bind a specter with this feature, you can''t use the feature again until you finish a long rest.'),
(184, 'Armor of Hexes', 10, 'At 10th level, your hex grows more powerful. If the target cursed by your Hexblade''s Curse hits you with an attack roll, roll a d6. On a 4 or higher, the attack instead misses you.'),
(184, 'Master of Hexes', 14, 'Starting at 14th level, you can use your Hexblade''s Curse again without resting, but when you apply it to a new target, the curse immediately ends on the previous target.');

-- Lurker in the Deep (UA) (ID: 185)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(185, 'Expanded Spell List', 1, 'The Lurker in the Deep lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Lurker Expanded Spells: 1st level - Create or Destroy Water, Thunderwave; 2nd level - Gust of Wind, Shatter; 3rd level - Lightning Bolt, Sleet Storm; 4th level - Control Water, Evard''s Black Tentacles; 5th level - Commune with Nature, Cone of Cold.'),
(185, 'Grasp of the Deep', 1, 'At 1st level, you gain the ability to magically summon a spectral tentacle that strikes at your foes. As a bonus action, you create a 10-foot-long tentacle at a point you can see within 60 feet of you. The tentacle lasts for 1 minute or until you use this feature to create another tentacle. When you create the tentacle, you can make a melee spell attack against a creature within 10 feet of it. On a hit, the target takes 1d8 cold or lightning damage (your choice when it takes the damage) and its speed is reduced by 10 feet until the start of your next turn. When you reach 10th level in this class, the damage dealt by the tentacle increases to 2d8. As a bonus action on your turn, you can move the tentacle up to 30 feet and repeat the attack. You can summon the tentacle a number of times equal to your Charisma modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(185, 'Scion of the Deep', 1, 'At 1st level, your patron accepts you into its inner court of servitors. You can telepathically communicate with any aberration, beast, elemental, or monstrosity that has an innate swimming speed, while it is within 120 feet of you. The creature can understand you and can respond telepathically.'),
(185, 'Fathomless Soul', 6, 'At 6th level, your patron grants you greater abilities. You gain the following benefits: You can breathe both air and water. You gain a swimming speed equal to your walking speed. You gain resistance to cold damage.'),
(185, 'Guardian Grasp', 6, 'At 6th level, the tentacle you create with Grasp of the Deep can defend you and others. When you or a creature you can see takes damage while within 10 feet of the tentacle, you can use your reaction to choose one of those creatures and reduce the damage to the chosen creature by half. After doing so, the tentacle vanishes.'),
(185, 'Devouring Maw', 10, 'Starting at 10th level, you can magically draw forth a manifestation of your patron''s insatiable hunger. As an action, choose a point you can see within 60 feet of you. For 1 minute, a translucent maw manifests in a 10-foot radius centered on that point. Each creature in that area when the maw appears must succeed on a Strength saving throw against your spell save DC or be restrained. Any creature that starts its turn in the maw''s area takes 3d6 cold or lightning damage (your choice when it takes the damage). As an action, a restrained creature can repeat the saving throw, ending the restraint on a success. At the start of your turn, if there is a creature in the maw''s area, you gain temporary hit points equal to your warlock level. Once you use this feature, you can''t do so again until you finish a short or long rest.'),
(185, 'Unleash the Depths', 14, 'Starting at 14th level, you gain the ability to call upon your patron for aid. As an action, you choose a point within 30 feet of you where your patron tears through reality, manifesting a measure of its thalassic grandeur. Choose one of the following effects to issue from this manifestation point. Once you use either effect, you can''t use this feature again until you finish a long rest. Transport: You and up to five willing creatures of your choice that you can see within 30 feet of the manifestation point are grasped by spectral tentacles and yanked through your patron''s realm. The tentacles teleport you and the chosen creatures to a point of your choice within 100 miles that you have visited within the past 24 hours. The tentacles then vanish. Fury: You can direct a barrage of spectral tentacles to issue forth and strike up to five creatures you can see within 30 feet of the manifestation point. Each target must make a Dexterity saving throw against your spell save DC. On a failed save, the creature takes 6d10 cold or lightning damage (your choice) and is knocked prone. On a successful save, it takes half as much damage and is not knocked prone. The tentacles then vanish.');

-- The Noble Genie (UA) (ID: 186) 
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(186, 'Expanded Spell List', 1, 'The Noble Genie lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Noble Genie Expanded Spells: 1st level - Fog Cloud, Sleep; 2nd level - Enlarge/Reduce, Phantasmal Force; 3rd level - Create Food and Water, Protection from Energy; 4th level - Polymorph, Phantasmal Killer; 5th level - Bigby''s Hand, Creation.'),
(186, 'Collector''s Vessel', 1, 'At 1st level, your patron gives you a magical vessel with which you can bind a creature to you and to your patron''s menagerie. The vessel is a Tiny object, and it is a spellcasting focus for you. If you lose your vessel, you can perform a 1-hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and it destroys the previous vessel. The vessel vanishes in a flare of elemental power when you die. As an action while you are holding the vessel, you target a willing creature you can see within 100 feet of you and create a tether of wispy elemental material that links the target to you. The tether lasts for 1 hour, until you use this feature to create another tether, until the bound target is reduced to 0 hit points, or until the target ends its turn more than 100 feet from you. While you are tethered to a creature, you gain the following benefits: You gain a bonus to your Wisdom (Perception) checks equal to your Charisma modifier (minimum of +1). When you can cast a spell, you can deliver the spell from your space or the bound creature''s space. You can create the tether a number of times equal to your Charisma modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(186, 'Elemental Resistance', 6, 'Starting at 6th level, your patron grants you protection from an element. Whenever you finish a long rest, you gain resistance to acid, cold, fire, or lightning damage (your choice) until the end of your next long rest. While the tether of your Collector''s Vessel is active, the tethered creature gains resistance to the damage type you chose.'),
(186, 'Protective Wish', 10, 'Beginning at 10th level, you''re now able to use your Collector''s Vessel to wish for protection for yourself or your tethered creature. If you or the tethered creature is hit by an attack, you can use your reaction to teleport, swapping places with the creature and switching which one of you is hit by the attack.'),
(186, 'Genie''s Entertainment', 10, 'Starting at 10th level, as an action, you can attempt to send a creature you can see within 90 feet to your patron''s court. The target must succeed on a Charisma saving throw against your warlock spell save DC or be magically drawn into your vessel and teleported to your patron''s court in the Elemental Planes. While there, the target is stunned and your patron marvels at the target with amusement but brings no harm to it. The target can repeat the saving throw at the end of each of its turns, reappearing in the space it left or in the nearest unoccupied space if that space is occupied on a success. Once you use this feature, you can''t use it again until you finish a long rest. If the target remains in your patron''s court for 1 minute, the genie sends the target back at the end of its turn as if it successfully saved, and you regain the use of this feature.'),
(186, 'Collector''s Call', 14, 'At 14th level, in exchange for extending your patron''s influence over the multiverse, you can call on more of their power. As an action, you can implore your patron for aid by making a Charisma (Persuasion) check against your warlock spell save DC. If the check succeeds, you can choose one of the following effects: A creature you can see within 60 feet of you regains 8d6 hit points and ends one disease or condition afflicting it: blinded, charmed, deafened, frightened, paralyzed, or poisoned. A creature you can see within 60 feet of you has disadvantage on attack rolls and saving throws until the start of your next turn. You cast the Legend Lore spell without material components. Whether the check succeeds or fails, you can''t use this feature again until you finish a long rest. Alternatively, you can regain the use of this feature by sacrificing nonmagical treasure worth at least 500 gp to your patron. This sacrifice requires the treasure to be within 10 feet of you for at least 1 minute, at the end of which you use an action to teleport the treasure to your patron''s realm, provided you have the vessel of your Collector''s Vessel in hand.');

-- The Raven Queen (UA) (ID: 187)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(187, 'Sentinel Raven', 1, 'Starting at 1st level, you gain the service of a spirit sent by the Raven Queen to watch over you. The spirit assumes the form and game statistics of a raven, and it always obeys your commands, which you can give telepathically while it is within 100 feet of you. While the raven is perched on your shoulder, you gain darkvision with a range of 30 feet and a bonus to your passive Wisdom (Perception) score and to Wisdom (Perception) checks. The bonus equals your Charisma modifier. While perched on your shoulder, the raven can''t be targeted by any attack or other harmful effect; only you can cast spells on it; it can''t take damage; and it is incapacitated. You can see through the raven''s eyes and hear what it hears while it is within 100 feet of you. In combat, you roll initiative for the raven and control how it acts. If it is slain by a creature, you gain advantage on all attack rolls against the killer for the next 24 hours. The raven doesn''t require sleep. While it is within 100 feet of you, it can awaken you from sleep as a bonus action. The raven vanishes when it dies, if you die, or if the two of you are separated by more than 5 miles. At the end of a short or long rest, you can call the raven back to you—no matter where it is or whether it died—and it reappears within 5 feet of you.'),
(187, 'Soul of the Raven', 6, 'At 6th level, you gain the ability to merge with your raven spirit. As a bonus action when your raven is perched on your shoulder, your body merges with your raven''s form. While merged, you become Tiny, you replace your speed with the raven''s, and you can use your action only to Dash, Disengage, Dodge, Help, Hide, or Search. During this time, you gain the benefits of your raven being perched on your shoulder. As an action, you and the raven return to normal.'),
(187, 'Raven''s Shield', 10, 'At 10th level, the Raven Queen grants you a protective blessing. You gain advantage on death saving throws, immunity to the frightened condition, and resistance to necrotic damage.'),
(187, 'Queen''s Right Hand', 14, 'Starting at 14th level, you can channel the Raven Queen''s power to slay a creature. You can cast Finger of Death. After you cast the spell with this feature, you can''t do so again until you finish a long rest.');

-- The Seeker (UA) (ID: 188) 
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(188, 'Genie''s Vessel', 1, 'At 1st level, your patron gives you a magical vessel that you can use as a spellcasting focus for your warlock spells. If you lose your vessel, you can perform a 1-hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and it destroys the previous vessel. The vessel vanishes in a flare of elemental power when you die. The vessel takes the form of an object appropriate to your patron''s element, such as a lamp for a Dao, a bottle for a Djinni, an urn for a Efreeti, or a box for a Marid. Your DM might allow other appropriate objects as well.'),
(188, 'Expanded Spell List', 1, 'The Seeker lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Seeker Expanded Spells: 1st level - Feather Fall, Jump; 2nd level - Levitate, Locate Object; 3rd level - Clairvoyance, Sending; 4th level - Arcane Eye, Locate Creature; 5th level - Legend Lore, Passwall.'),
(188, 'Shielding Aurora', 1, 'Starting at 1st level, you can invoke the Seeker''s power to protect you from harm. As a bonus action, you create a whirling aurora of brilliant energy that swirls around you. Until the end of your next turn, you gain resistance to all damage, and if a hostile creature ends its turn within 10 feet of you, it takes radiant damage equal to your warlock level + your Charisma modifier. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(188, 'Pact Boon: Pact of the Star Chain', 3, 'At 3rd level, a character dedicated to the Seeker can select this option instead of one of the warlock''s existing Pact Boon options. The Seeker grants you a chain forged from starlight, decorated with seven gleaming motes of brightness. While the chain is on your person, you know the augury spell and can cast it as a ritual. The spell doesn''t count against your number of spells known. Additionally, you can invoke the Seeker''s power to gain advantage on an Intelligence check while you carry this item. Once you use this ability, you cannot use it again until you complete a short or long rest. If you lose your Star Chain, you can perform a 1-hour ceremony to receive a replacement from the Seeker. The ceremony can be performed during a short or long rest, and it destroys the previous chain. The chain disappears in a flash of light when you die. The exact form of this item might be different depending on your patron. The Star Chain is inspired by the Greyhawk deity Celestian.'),
(188, 'Astral Refuge', 6, 'At 6th level, you gain the ability to step into an astral refuge. As an action, you disappear from the world for a brief moment and enter the Astral Plane, taking advantage of its timeless nature. While in your astral refuge, you can take two actions to cast spells that target only you. After using those two actions, you return to the space you occupied and your turn ends.'),
(188, 'Far Wanderer', 10, 'At 10th level, you no longer need to breathe, and you gain resistance to fire damage and cold damage.'),
(188, 'Astral Sequestration', 14, 'Starting at 14th level, you gain the ability to sequester yourself and your allies on the Astral Plane. By performing a special ritual over the course of 5 minutes, you shift yourself and up to ten willing creatures you can see to the Astral Plane. You and those creatures gain the benefits of a short rest while sequestered on the Astral Plane. You then return to the spaces you all occupied when you used this ability, with no time having passed in the world. During this short rest, you and the creatures you sequester can make use of any options available during a rest that affect only you and the creatures you sequester. Once you use this ability, you cannot use it again until you complete a long rest.');

-- The Undead (UA) (ID: 189) 
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(189, 'Form of Dread', 1, 'At 1st level, you manifest an aspect of your patron''s dreadful power. As a bonus action, you transform for 1 minute. You gain the following benefits while transformed: You gain temporary hit points equal to 1d10 + your warlock level. Once during each of your turns, when you hit a creature with an attack, you can force it to make a Wisdom saving throw, and if the saving throw fails, the target is frightened of you until the end of your next turn. You are immune to the frightened condition. You can transform a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest. The appearance of your Form of Dread reflects some aspect of your patron. For example, your form could be a shroud of shadows forming the crown and robes of your lich patron, or your face might transform into bat-like features due to your vampire patron.'),
(189, 'Grave Touched', 6, 'At 6th level, your patron''s powers have a profound effect on your body and magic. You don''t need to eat, drink, or breathe. In addition, when you hit a creature with an attack and roll damage against the creature, you can replace the damage type with necrotic damage. While you are using your Form of Dread, you can roll one additional damage die when determining the necrotic damage the target takes.'),
(189, 'Mortal Husk', 10, 'At 10th level, Your connection to undeath and necrotic energy now saturates your body. You have resistance to necrotic damage. If you are transformed using your Form of Dread, you instead become immune to necrotic damage. In addition, when you are reduced to 0 hit points, you can cause your body to explode. Each creature within 30 feet of you takes necrotic damage equal to 2d10 + your warlock level. You then revive with 1 hit point in your previous space, along with your gear, and you gain 1 level of exhaustion. Once you revive this way, you can''t do so again until you finish 1d4 long rests.'),
(189, 'Spirit Projection', 14, 'At 14th level, your body is now simply a vessel for your spirit. As an action, you can project your spirit from your body. The body you leave behind is unconscious and in a state of suspended animation. Your spirit can remain outside your body for up to 1 hour or until your concentration is broken (as if concentrating on a spell). When your projection ends, your spirit returns to your body or your body magically teleports to your spirit''s space (your choice). While projecting your spirit, you gain the following benefits: Your spirit and body gain resistance to bludgeoning, piercing, and slashing damage. When you cast a spell of the conjuration or necromancy school, the spell doesn''t require verbal, somatic, or material components that lack a gold cost. You have a flying speed equal to your walking speed and can hover. You can move through creatures and objects as if they were difficult terrain, but you take 1d10 force damage if you end your turn inside a creature or an object. While you are using your Form of Dread, once during each of your turns when you deal necrotic damage to a creature, you regain hit points equal to half the amount of necrotic damage dealt. Once you use this feature, you can''t do so again until you finish a long rest.');

-- The Undying Light (UA) (ID: 190) 
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(190, 'Expanded Spell List', 1, 'The Undying Light lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you. Undying Light Expanded Spells: 1st level - Burning Hands; 2nd level - Flaming Sphere; 3rd level - Daylight; 4th level - Fire Shield; 5th level - Flame Strike.'),
(190, 'Radiant Soul', 1, 'Starting at 1st level, your link to the Positive Plane allows you to serve as a conduit for radiant energy. You have resistance to radiant damage, and when you cast a spell that deals radiant damage or fire damage, you add your Charisma modifier to that damage. Additionally, you know the Light and Sacred Flame cantrips and can cast them at will. They don''t count against your number of cantrips known.'),
(190, 'Searing Vengeance', 6, 'Starting at 6th level, the radiant energy you channel allows you to overcome grievous injuries. When you would make a death saving throw, you can instead spring back to your feet with a burst of radiant energy. You immediately stand up (if you so choose), and you regain hit points equal to half your hit point maximum. All hostile creatures within 30 feet of you take 10 + your Charisma modifier radiant damage and are blinded until the end of your turn. Once you use this feature, you can''t use it again until you finish a long rest.'),
(190, 'Radiant Resistance', 10, 'Starting at 10th level, you gain temporary hit points whenever you finish a long or short rest. These temporary hit points equal your warlock level + your Charisma modifier. Additionally, choose up to five creatures you can see at the end of your rest. Those creatures gain temporary hit points equal to half your warlock level + your Charisma modifier.'),
(190, 'Healing Light', 14, 'At 14th level, you gain the ability to channel the Undying Light to heal yourself and other creatures. As a bonus action, you can touch a creature and heal it. With each touch, a creature regains from 1d6 to 5d6 hit points (your choice). You have a total pool of 15d6 you can expend. Subtract the dice you use with each touch from that total. You regain all expended dice from your pool when you finish a long rest.');

-- Mage of Lorehold (UA) (ID: 191) 
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(191, 'Lorehold Primer', 2, 'At 2nd level, you gain proficiency in the History skill, if you don''t already have it. Additionally, you learn the comprehend languages and identify spells, which don''t count against the number of wizard spells you know.'),
(191, 'Lorehold Manifestation', 2, 'Starting at 2nd level, you can channel the power of ancient knowledge to manifest a spectral tome. As a bonus action, you can cause a spectral tome to appear in your hand. The tome has the following properties: The tome contains a number of pages equal to your wizard level. As an action, you can expend 1 page to cast a wizard cantrip that you know. The tome vanishes if you are incapacitated or if you dismiss it as a bonus action. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(191, 'Archivist''s Insight', 6, 'Beginning at 6th level, you can draw on the knowledge of ancient archivists. When you make an Intelligence check to recall lore about a person, place, or thing, you can add your proficiency bonus to the check even if you''re not proficient in the skill used. Additionally, when you cast a spell that deals damage, you can expend 1 page from your Lorehold Manifestation to deal an extra 1d6 force damage to one target of the spell.'),
(191, 'Lorehold Legacy', 10, 'Starting at 10th level, you can tap into the legacy of Lorehold to empower your spells. When you cast a spell, you can expend 1 page from your Lorehold Manifestation to cast the spell as if it were cast using a spell slot one level higher. Additionally, you can use your action to cause the spectral tome to unleash a burst of knowledge. Each creature of your choice within 30 feet of you must make an Intelligence saving throw against your spell save DC. A creature takes 2d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(191, 'Archmage of Lorehold', 14, 'At 14th level, your connection to the ancient knowledge of Lorehold allows you to manifest powerful effects. When you cast a spell, you can expend 2 pages from your Lorehold Manifestation to cause the spell to affect an additional target. Additionally, you can use your action to cause the spectral tome to unleash a wave of knowledge. Each creature in a 30-foot cone must make an Intelligence saving throw against your spell save DC. A creature takes 4d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- Mage of Silverquill (UA) (ID: 192)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(192, 'Silverquill Primer', 2, 'At 2nd level, you gain proficiency in the Persuasion skill, if you don''t already have it. Additionally, you learn the vicious mockery and friends cantrips, which don''t count against the number of wizard cantrips you know.'),
(192, 'Silverquill Manifestation', 2, 'Starting at 2nd level, you can channel the power of words to manifest a silverquill quill. As a bonus action, you can cause a silverquill quill to appear in your hand. The quill has the following properties: The quill has 10 charges. When you hit with a spell attack, you can expend 1 charge to deal an extra 1d6 psychic damage. As an action, you can expend 1 charge to cast a wizard cantrip that you know. The quill vanishes if you are incapacitated or if you dismiss it as a bonus action. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(192, 'Rhetorical Flourish', 6, 'Beginning at 6th level, you can use your words to enhance your spells. When you cast a spell that requires a saving throw, you can add your Intelligence modifier to the spell''s save DC. Additionally, when you cast a spell that deals damage, you can expend 1 charge from your Silverquill Manifestation to deal an extra 1d6 psychic damage to one target of the spell. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(192, 'Silverquill Legacy', 10, 'Starting at 10th level, you can tap into the legacy of Silverquill to empower your spells. When you cast a spell, you can expend 1 charge from your Silverquill Manifestation to cast the spell as if it were cast using a spell slot one level higher. Additionally, you can use your action to cause the silverquill quill to unleash a burst of words. Each creature of your choice within 30 feet of you must make a Charisma saving throw against your spell save DC. A creature takes 2d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(192, 'Archmage of Silverquill', 14, 'At 14th level, your connection to the eloquent words of Silverquill allows you to manifest powerful effects. When you cast a spell, you can expend 2 charges from your Silverquill Manifestation to cause the spell to affect an additional target. Additionally, you can use your action to cause the silverquill quill to unleash a wave of words. Each creature in a 30-foot cone must make a Charisma saving throw against your spell save DC. A creature takes 4d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- Mage of Witherbloom (UA) (ID: 193)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(193, 'Witherbloom Spells', 1, 'You learn the cantrip Spare the Dying and the 1st level spells Cure Wounds and Inflict Wounds. You learn additional spells when you reach certain levels in this class.'),
(193, 'Essence Tap', 1, 'As a bonus action, you can draw on a reservoir of life essence to empower yourself for 1 minute, choosing between Overgrowth and Withering Strike.'),
(193, 'Witherbloom Brew', 6, 'You gain proficiency with herbalism kits. When you finish a long rest, you can create magical brews with various effects.'),
(193, 'Witherbloom Adept', 10, 'Once per turn when you deal necrotic damage or restore hit points using a spell, one target of the spell takes additional damage or regains additional hit points equal to your proficiency bonus.'),
(193, 'Withering Vortex', 14, 'When you cast a spell using a spell slot that deals necrotic damage, you can drain life energy from one of the targets to heal another creature.');
