-- =============================================================================
-- WIZARD SUBCLASSES
-- =============================================================================

-- School of Abjuration (ID: 194)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(194, 'Arcane Ward', 2, 'Starting at 2nd level, you can weave magic around yourself for protection. When you cast an abjuration spell of 1st level or higher, you can simultaneously use a strand of the spell''s magic to create a magical ward on yourself that lasts until you finish a long rest. The ward has hit points equal to twice your wizard level + your Intelligence modifier. Whenever you take damage, the ward takes the damage instead. If this damage reduces the ward to 0 hit points, you take any remaining damage. While the ward has 0 hit points, it can''t absorb damage, but its magic remains. Whenever you cast an abjuration spell of 1st level or higher, the ward regains a number of hit points equal to twice the level of the spell. Once you create the ward, you can''t create it again until you finish a long rest.'),
(194, 'Projected Ward', 6, 'Starting at 6th level, when a creature that you can see within 30 feet of you takes damage, you can use your reaction to cause your Arcane Ward to absorb that damage. If this damage reduces the ward to 0 hit points, the warded creature takes any remaining damage.'),
(194, 'Improved Abjuration', 10, 'Beginning at 10th level, when you cast an abjuration spell that requires you to make an ability check as a part of casting that spell (as in Counterspell and Dispel Magic), you add your proficiency bonus to that ability check.'),
(194, 'Spell Resistance', 14, 'Starting at 14th level, you have advantage on saving throws against spells. Furthermore, you have resistance against the damage of spells.');

-- Bladesinging (ID: 195)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(195, 'Bladesong', 2, 'Starting at 2nd level, you can invoke a Bladesong as a bonus action. It lasts for 1 minute. It ends early if you are incapacitated, if you don medium or heavy armor or a shield, or if you use two hands to make an attack with a weapon. You can also dismiss the Bladesong at any time (no action required). While your Bladesong is active, you gain the following benefits: You gain a bonus to your AC equal to your Intelligence modifier (minimum of +1). Your walking speed increases by 10 feet. You have advantage on Dexterity (Acrobatics) checks. You gain a bonus to any Constitution saving throw you make to maintain your concentration on a spell. The bonus equals your Intelligence modifier (minimum of +1). You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses of it when you finish a long rest.'),
(195, 'Extra Attack', 6, 'Starting at 6th level, you can attack twice, instead of once, whenever you take the Attack action on your turn while your Bladesong is active.'),
(195, 'Song of Defense', 10, 'Beginning at 10th level, you can direct your magic to absorb damage while your Bladesong is active. When you are hit by an attack, you can use your reaction to expend one spell slot and reduce the damage by an amount equal to five times the spell slot''s level.'),
(195, 'Song of Victory', 14, 'Starting at 14th level, you add your Intelligence modifier (minimum of +1) to the damage of your melee weapon attacks while your Bladesong is active.');

-- Chronurgy Magic (ID: 196)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(196, 'Chronal Shift', 2, 'Starting at 2nd level, you can magically exert limited control over the flow of time around a creature. As a reaction, which you take when a creature you can see within 30 feet of you makes an attack roll, a saving throw, or an ability check, you can force the creature to reroll that roll. You make this decision after you see the roll but before any effects of the roll (including Advantage and Disadvantage) are applied. The target must use the result of the second roll. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(196, 'Temporal Awareness', 2, 'At 2nd level, you can add your Intelligence modifier to your initiative rolls.'),
(196, 'Momentary Stasis', 6, 'Starting at 6th level, as an action, you can magically force a Large or smaller creature you can see within 60 feet of you to make a Constitution saving throw against your spell save DC. On a failed save, the creature is encased in a field of magical force until the start of your next turn or until the creature takes any damage. While encased, the creature is incapacitated, can''t move or speak, and is unaware of its surroundings. The field is opaque. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(196, 'Arcane Abeyance', 10, 'When you reach 10th level, when you cast a spell using a spell slot of 4th level or lower, you can condense the spell''s magic into a mote. The spell is frozen in time at the moment of casting and held within a gray bead for 1 hour. This bead is a Tiny object with AC 15 and 1 hit point, and it is immune to poison and psychic damage. When the duration ends, or if the bead is destroyed, it vanishes in a flash of light, and the spell is lost. A creature holding the bead can use its action to release the spell within, whereupon the bead vanishes. The spell uses your spellcasting ability and save DC. You can have only one bead active at a time.'),
(196, 'Convergent Future', 14, 'Starting at 14th level, you can peer through possible futures and magically pull one of them into events around you, ensuring a particular outcome. When you or a creature you can see within 60 feet of you makes an attack roll, an ability check, or a saving throw, you can use your reaction to ignore the die roll and decide whether the number rolled is the minimum needed to succeed or one less than that number (your choice). You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- School of Conjuration (ID: 197)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(197, 'Conjuration Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a conjuration spell into your spellbook is halved.'),
(197, 'Minor Conjuration', 2, 'Starting at 2nd level, you can use your action to conjure up an inanimate object in your hand or on the ground in an unoccupied space that you can see within 10 feet of you. This object can''t be larger than 3 feet on a side and must be of a form and material that you have seen before. The object is visibly magical, radiating dim light out to 5 feet. The object disappears after 1 hour, when you use this feature again, or if it takes any damage.'),
(197, 'Benign Transposition', 6, 'Starting at 6th level, you can use your action to teleport up to 30 feet to an unoccupied space that you can see. Alternatively, you can choose a space within range that is occupied by a Small or Medium creature. If that creature is willing, you both teleport, swapping places. Once you use this feature, you can''t use it again until you finish a long rest or you cast a conjuration spell of 1st level or higher.'),
(197, 'Focused Conjuration', 10, 'Beginning at 10th level, while you are concentrating on a conjuration spell, your concentration can''t be broken as a result of taking damage.'),
(197, 'Durable Summons', 14, 'Starting at 14th level, any creature that you summon or create with a conjuration spell has 30 temporary hit points.');

-- School of Divination (ID: 198)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(198, 'Divination Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a divination spell into your spellbook is halved.'),
(198, 'Portent', 2, 'Starting at 2nd level, glimpses of the future begin to press in on your awareness. When you finish a long rest, roll two d20s and record the numbers rolled. You can replace any attack roll, saving throw, or ability check made by you or a creature that you can see with one of these foretelling rolls. You must choose to do so before the roll, and you can replace a roll in this way only once per turn. Each foretelling roll can be used only once. When you finish a long rest, you lose any unused Portents.'),
(198, 'Expert Divination', 6, 'Beginning at 6th level, casting divination spells comes so easily to you that it expends only half the normal number of spell slots (round up).'),
(198, 'The Third Eye', 10, 'Starting at 10th level, you can use your action to increase your awareness. When you do so, choose one of the following benefits, which lasts until you are incapacitated or you take a short or long rest. You can see normally in darkness, both magical and nonmagical, to a distance of 120 feet. You can see the true form of any shapechanger or creature concealed by illusion or transmutation magic while the creature is within 120 feet of you and within line of sight. You can see into the Ethereal Plane within 120 feet of you. You can see invisible creatures and objects within 120 feet of you that are within line of sight. To use this feature, you must expend one Portent die.'),
(198, 'Greater Portent', 14, 'Starting at 14th level, the visions in your dreams intensify and paint a more accurate picture in your mind of what is to come. You roll three d20s for your Portent feature, rather than two.');

-- School of Enchantment (ID: 199)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(199, 'Enchantment Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an enchantment spell into your spellbook is halved.'),
(199, 'Hypnotic Gaze', 2, 'Starting at 2nd level, your soft words and enchanting gaze can magically enthrall another creature. As an action, choose one creature that you can see within 5 feet of you. If the target can see or hear you, it must succeed on a Wisdom saving throw against your wizard spell save DC or be charmed by you until the end of your next turn. If the target''s Wisdom modifier is higher than your Charisma modifier, the DC is instead 8 + your proficiency bonus + your Wisdom modifier. The charmed creature has disadvantage on attack rolls against creatures other than you. Any attack roll against the charmed creature has advantage. You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain expended uses when you finish a long rest.'),
(199, 'Instinctive Charm', 6, 'Beginning at 6th level, when a creature attempts to charm you, you can use your reaction to turn the charm back on that creature. The creature must succeed on a Wisdom saving throw against your wizard spell save DC or be charmed by you for 1 minute or until the creature takes any damage.'),
(199, 'Split Enchantment', 10, 'Starting at 10th level, when you cast an enchantment spell of 1st level or higher that targets only one creature, and that spell would normally target only one creature, you can have it target a second creature.'),
(199, 'Alter Memories', 14, 'At 14th level, you gain the ability to make a creature unaware of your magical influence on it. When you cast an enchantment spell to charm one or more creatures, you can alter one creature''s understanding so that it remains unaware of being charmed. Additionally, once before the spell expires, you can use your action to try to make the chosen creature forget some of the time it spent charmed. The creature must succeed on an Intelligence saving throw against your wizard spell save DC or lose a number of hours of its memories equal to 1d6 + your Charisma modifier (minimum 1). You can make the creature forget less time, and the amount of time can''t exceed the duration of your enchantment spell.');

-- School of Evocation (ID: 200)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(200, 'Evocation Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an evocation spell into your spellbook is halved.'),
(200, 'Sculpt Spells', 2, 'Beginning at 2nd level, you can create pockets of relative safety within the effects of your evocation spells. When you cast an evocation spell that affects other creatures that you can see, you can protect a number of those creatures equal to 1 + the spell''s level. The chosen creatures automatically succeed on their saving throws against the spell, and they take no damage if they would normally take half damage on a successful save.'),
(200, 'Potent Cantrip', 6, 'Starting at 6th level, your damaging cantrips affect even creatures that avoid the brunt of the effect. When a creature succeeds on a saving throw against your cantrip, the creature takes half the cantrip''s damage (if any) but suffers no additional effect from the cantrip.'),
(200, 'Empowered Evocation', 10, 'Beginning at 10th level, you can add your Intelligence modifier to the damage roll of any wizard evocation spell you cast.'),
(200, 'Overchannel', 14, 'Starting at 14th level, you can increase the power of your simpler spells. When you cast a wizard spell of 1st through 5th level that deals damage, you can deal maximum damage with that spell. The first time you do so, you suffer no adverse effect. If you use this feature again before you finish a long rest, you take 2d12 necrotic damage for each level of the spell, immediately after you cast it. Each time you use this feature again before finishing a long rest, the necrotic damage per spell level increases by 1d12. This damage ignores resistance and immunity.');

-- Graviturgy Magic (ID: 201)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(201, 'Adjust Density', 2, 'At 2nd level, as an action, you can magically alter the weight of one object or creature you can see within 30 feet of you. The object or creature must be Large or smaller. The target''s weight is halved or doubled for up to 1 minute or until your concentration ends (as if you were concentrating on a spell). While the weight is halved, the target has disadvantage on Strength checks and Strength saving throws, and its speed is doubled. While the weight is doubled, the target has advantage on Strength checks and Strength saving throws, and its speed is halved. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(201, 'Gravity Well', 6, 'Starting at 6th level, when you cast a spell on a creature, you can move the target 5 feet to an unoccupied space of your choice if the target is willing to move, the spell hits it with an attack, or it fails its saving throw against the spell.'),
(201, 'Violent Attraction', 10, 'Starting at 10th level, when another creature that you can see within 60 feet of you hits with a weapon attack, you can use your reaction to increase the attack''s velocity, causing the attack to deal an extra 1d10 damage of the weapon''s type to the target. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(201, 'Event Horizon', 14, 'Starting at 14th level, as an action, you can magically emit a powerful field of gravitational energy that tugs at other creatures for 1 minute or until your concentration ends (as if you were concentrating on a spell). For the duration, whenever a creature hostile to you starts its turn within 30 feet of you, it must make a Strength saving throw against your spell save DC. On a failed save, it takes 2d10 force damage, and its speed becomes 0 until the start of its next turn. On a successful save, it takes half as much damage, and its speed is halved until the start of its next turn. Once you use this feature, you can''t use it again until you finish a long rest or you expend a 3rd-level or higher spell slot to use it again (no action required).');

-- School of Illusion (ID: 202)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(202, 'Illusion Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an illusion spell into your spellbook is halved.'),
(202, 'Improved Minor Illusion', 2, 'When you choose this school at 2nd level, you learn the minor illusion cantrip. If you already know this cantrip, you learn a different wizard cantrip of your choice. The cantrip doesn''t count against your number of cantrips known. When you cast minor illusion, you can create both a sound and an image with a single casting of the spell.'),
(202, 'Malleable Illusions', 6, 'Starting at 6th level, when you cast an illusion spell that has a duration of 1 minute or longer, you can use your action to change the nature of that illusion (using the spell''s normal parameters for the illusion), provided that you can see the illusion.'),
(202, 'Illusory Self', 10, 'Beginning at 10th level, you can create an illusory duplicate of yourself as an instant, almost instinctual reaction to danger. When a creature makes an attack roll against you, you can use your reaction to interpose the illusory duplicate between the attacker and yourself. The attack automatically misses you, then the illusion dissipates. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(202, 'Illusory Reality', 14, 'By 14th level, you have learned the secret of weaving shadow magic into your illusions to give them a semi-reality. When you cast an illusion spell of 1st level or higher, you can choose one inanimate, nonmagical object that is part of the illusion and make that object real. You can do this on your turn as an action while the spell lasts. The object remains real for 1 minute. For example, you can create an illusion of a bridge over a chasm and then make it real long enough for your allies to cross. The object can''t deal damage or otherwise directly harm anyone.');

-- School of Necromancy (ID: 203)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(203, 'Necromancy Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a necromancy spell into your spellbook is halved.'),
(203, 'Grim Harvest', 2, 'At 2nd level, you gain the ability to reap life energy from creatures you kill with your spells. Once per turn when you kill one or more creatures with a spell of 1st level or higher, you regain hit points equal to twice the spell''s level, or three times its level if the spell belongs to the School of Necromancy. You don''t gain this benefit for killing constructs or undead.'),
(203, 'Undead Thralls', 6, 'At 6th level, you add the animate dead spell to your spellbook if it is not there already. When you cast animate dead, you can target one additional corpse or pile of bones. Additionally, your undead creatures gain bonus hit points equal to your wizard level. The undead remain animated until you use this feature again.'),
(203, 'Inured to Undeath', 10, 'Beginning at 10th level, you have resistance to necrotic damage, and your hit point maximum can''t be reduced.'),
(203, 'Command Undead', 14, 'Starting at 14th level, you can use magic to bring undead under your control, even those created by other wizards. As an action, you can target one undead creature you can see within 60 feet of you. That creature must make a Wisdom saving throw against your wizard spell save DC. If it succeeds, you can''t use this feature on it again. If it fails, it becomes friendly to you and obeys your commands until you use this feature again. Intelligent undead are harder to control in this way. If the target has an Intelligence of 8 or higher, it has advantage on the saving throw. If it fails the saving throw and has an Intelligence of 12 or higher, it can repeat the saving throw at the end of every hour until it succeeds and breaks free.');

-- Order of Scribes (ID: 204)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(204, 'Wizardly Quill', 2, 'At 2nd level, as a bonus action, you can magically create a Tiny construct in the shape of a quill that hovers at your side. The construct lasts for 1 hour. For the duration, you can use it to write with your bonus action. The quill doesn''t require ink, and it never runs out. If you lose concentration on the spell, the quill disappears, but any writing it created remains. If you cast this spell while the quill is active, the spell fails.'),
(204, 'Awakened Spellbook', 2, 'Starting at 2nd level, you have infused extra magic into your spellbook, turning it into Awakened Spellbook. When you cast a wizard spell as a ritual, you can use the spell''s normal casting time, rather than adding 10 minutes to it. As an action, you can send the book up to 5 feet away from you. If you are within 5 feet of the book, you can touch it and cause it to open to a page of your choice. Additionally, the book can send you emotional signals if it is within 1,000 feet of you. These signals are a mix of emotions from the book, such as hunger, curiosity, or fear. You can interpret these signals intuitively. If the book takes damage while within 1,000 feet of you, you take the damage instead. The book has AC 15, 1 hit point, and immunity to poison and psychic damage. If the book is destroyed, you can perform a 1-hour ceremony to infuse a new book with the same magic. The ceremony destroys the previous book.'),
(204, 'Manifest Mind', 6, 'At 6th level, you can conjure forth the mind of your Awakened Spellbook. As a bonus action while your Awakened Spellbook is on the same plane of existence, you can cause a spectral manifestation of the book''s consciousness to appear in an unoccupied space within 60 feet of you or the book. The manifestation is a Tiny spectral object that is intangible and doesn''t occupy its space. The manifestation looks like a ghostly tome, a cascade of text, or a scholar from the past (your choice). For the next minute, the manifestation hovers in the air. If another creature uses its action to touch the manifestation, the creature takes 2d6 psychic damage. As a bonus action, you can move the manifestation up to 30 feet. If you have the manifestation move into a space occupied by a creature, you can have the creature make a Wisdom saving throw against your spell save DC. On a failed save, the creature takes 2d6 psychic damage. On a successful save, the manifestation can''t move through the creature''s space for 1 minute. The manifestation vanishes if it is reduced to 0 hit points, if you lose consciousness, or if you dismiss it as a bonus action. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(204, 'Master Scrivener', 10, 'Starting at 10th level, your Awakened Spellbook becomes animated by the magic of your words. When you cast a spell that requires a spellcasting focus, you can use your Awakened Spellbook as the focus instead of any material component. Additionally, if you have your Awakened Spellbook with you, you can cast any spell you have written in it without using a spell slot. Once you cast a spell from the book in this way, you can''t do so again until you finish a long rest. If you lose your Awakened Spellbook, you lose the benefits of this feature until you perform a 1-hour ceremony to infuse a new book with the same magic.'),
(204, 'One with the Word', 14, 'At 14th level, your connection to your Awakened Spellbook has become so profound that your soul has become linked to it. While the book is on the same plane of existence as you, you can communicate with it telepathically. Additionally, the book''s awareness expands. It knows everything you know and can see everything you see. If you are unconscious, blinded, deafened, or otherwise cut off from your senses, your Awakened Spellbook can see and hear for you. In addition, while you are within 1,000 feet of your Awakened Spellbook, you can take any action as a bonus action if that action only involves the book (such as reading it or writing in it).');

-- School of Transmutation (ID: 205)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(205, 'Transmutation Savant', 2, 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a Transmutation spell into your spellbook is halved.'),
(205, 'Minor Alchemy', 2, 'Starting at 2nd level when you select this school, you can temporarily alter the physical properties of one nonmagical object, changing it from one substance into another. You perform a special alchemical procedure on one object composed entirely of wood, stone (but not a gemstone), iron, copper, or silver, transforming it into a different one of those materials. For each 10 minutes you spend performing the procedure, you can transform up to 1 cubic foot of material. After 1 hour, or until you lose your concentration (as if you were concentrating on a spell), the material reverts to its original substance.'),
(205, 'Transmuter''s Stone', 6, 'Starting at 6th level, you can spend 8 hours creating a transmuter''s stone that stores transmutation magic. You can benefit from the stone yourself or give it to another creature. A creature gains a benefit of your choice as long as the stone is in the creature''s possession. When you create the stone, choose the benefit from the following options: Darkvision: You have darkvision out to a range of 60 feet. If you already have darkvision, its range increases by 60 feet. Maximize Ability Score: Your proficiency bonus is doubled for any ability check you make that uses the chosen score. Resistance: You have resistance to the damage types associated with the chosen damage type (acid, cold, fire, lightning, or poison). Restore Ability Score: Your proficiency bonus is doubled for any ability check you make to recover from the chosen condition (blinded, deafened, paralyzed, or poisoned). Toughness: Your hit point maximum increases by an amount equal to your level, and it increases by 1 every time you gain a level. If you create a new transmuter''s stone, the previous one ceases to function.'),
(205, 'Shapechanger', 10, 'At 10th level, you add the Polymorph spell to your spellbook, if it is not there already. You can cast Polymorph without expending a spell slot. When you do so, you can target only yourself and transform into a beast whose challenge rating is 1 or lower. Once you cast Polymorph in this way, you can''t do so again until you finish a short or long rest, though you can still cast it normally using an available spell slot.'),
(205, 'Master Transmuter', 14, 'Starting at 14th level, you can use your action to consume the reserve of transmutation magic stored within your transmuter''s stone in a single burst. When you do so, choose one of the following effects. Your transmuter''s stone is destroyed and can''t be remade until you finish a long rest. Major Transformation: You can transmute one nonmagical object â€“ no larger than a 5-foot cube â€“ into another nonmagical object of similar size and mass and of equal or lesser value. You must spend 10 minutes handling the object to transform it. Panacea: You remove all curses, diseases, and poisons affecting a creature that you touch with the transmuter''s stone. The creature also regains all its hit points. Restore Life: You cast the Raise Dead spell on a creature you touch with the transmuter''s stone, without expending a spell slot or needing to have the spell in your spellbook. Restore Youth: You touch the transmuter''s stone to a willing creature, and that creature''s apparent age is reduced by 3d10 years, to a minimum of 13 years. This effect doesn''t extend the creature''s lifespan.');

-- War Magic (ID: 206)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(206, 'Arcane Deflection', 2, 'At 2nd level, you have learned to weave your magic to fortify yourself against harm. When you are hit by an attack or you fail a saving throw, you can use your reaction to gain a +2 bonus to your AC against that attack or a +4 bonus to that saving throw. When you use this feature, you can''t cast spells other than cantrips until the end of your next turn.'),
(206, 'Tactical Wit', 2, 'Starting at 2nd level, your keen ability to assess tactical situations allows you to act quickly in battle. You can give yourself a bonus to your initiative rolls equal to your Intelligence modifier.'),
(206, 'Power Surge', 6, 'Starting at 6th level, you can store magical energy within yourself to later empower your damaging spells. You can store a maximum number of power surges equal to your Intelligence modifier (minimum of one). Whenever you finish a long rest, your number of power surges resets to one. Whenever you successfully end a spell with Dispel Magic or Counterspell, you gain one power surge, as you steal magic from the spell you foiled. If you end a short rest with no power surges, you gain one power surge. Once per turn when you deal damage to a creature or object with a wizard spell, you can spend one power surge to deal extra force damage to that target. The extra damage equals half your wizard level.'),
(206, 'Durable Magic', 10, 'Beginning at 10th level, the magic you channel helps ward off harm. While you maintain concentration on a spell, you have a +2 bonus to AC and all saving throws.'),
(206, 'Deflecting Shroud', 14, 'At 14th level, your Arcane Deflection becomes infused with deadly magic. When you use your Arcane Deflection feature, you can cause magical energy to arc from you. Up to three creatures of your choice within 60 feet of you each take force damage equal to half your wizard level.');

-- Runecrafter (UA) (ID: 207)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(207, 'Runic Magic', 2, 'At 2nd level, you learn to infuse runes with magic. You learn two runes of your choice from the Rune Options table. Each rune has a name, a level requirement, and a description. You can use a rune by casting it as a bonus action. You can use each rune a number of times equal to your Intelligence modifier (minimum of one). You regain all expended uses when you finish a long rest. Rune Options: Rune of Absorption (2nd level): As a reaction when you take damage, you can use this rune to absorb some of the damage. Reduce the damage you take by 1d6 + your Intelligence modifier. Rune of Aegis (2nd level): As a bonus action, you can activate this rune to gain a +2 bonus to AC for 1 minute. Rune of Alarm (2nd level): As an action, you can cast alarm using this rune. Rune of Comprehension (2nd level): As an action, you can cast comprehend languages using this rune. Rune of Destruction (2nd level): As an action, you can cast fireball using this rune, but the spell deals force damage instead of fire damage. Rune of Enhancement (2nd level): As a bonus action, you can activate this rune to gain advantage on Strength checks for 1 minute. Rune of Force (2nd level): As an action, you can cast magic missile using this rune. Rune of Haste (6th level): As a bonus action, you can activate this rune to gain the effects of haste for 1 minute. Rune of Healing (6th level): As an action, you can cast cure wounds using this rune. Rune of Power (6th level): As a bonus action, you can activate this rune to regain one expended spell slot of 3rd level or lower. Rune of Protection (6th level): As a reaction when you are hit by an attack, you can use this rune to gain resistance to all damage from that attack. Rune of Speed (6th level): As a bonus action, you can activate this rune to gain a +20 feet bonus to your speed for 1 minute. Rune of Teleportation (10th level): As an action, you can cast dimension door using this rune. Rune of Truth (10th level): As an action, you can cast zone of truth using this rune. Rune of Warding (10th level): As an action, you can cast glyph of warding using this rune.'),
(207, 'Runic Discovery', 6, 'At 6th level, you learn two additional runes of your choice from the Rune Options table.'),
(207, 'Runic Mastery', 10, 'Starting at 10th level, you can use runes without expending uses. Additionally, you learn two more runes of your choice from the Rune Options table.'),
(207, 'Runic Supremacy', 14, 'At 14th level, you gain the ability to empower your runes. When you use a rune, you can spend a spell slot to increase its potency. The spell slot level determines the bonus effect: 1st level: The rune''s effect lasts for an additional 1 minute. 2nd level: The rune''s damage or healing increases by 1d6. 3rd level: The rune''s range increases by 30 feet. 4th level: The rune''s area of effect increases by 10 feet. 5th level: The rune grants an additional effect of your choice from the Rune Options table.');

-- Artificer (UA) (ID: 208)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(208, 'Magical Tinkering', 2, 'At 2nd level, you learn how to invest a spark of magic into mundane objects. To use this ability, you must have thieves'' tools or artisan''s tools in hand. You can take a bonus action to touch a Tiny nonmagical object as an action and give it one of the following magical properties of your choice: The object sheds bright light in a 5-foot radius and dim light for an additional 5 feet. Whenever tapped by a creature, the object emits a recorded message that can be heard up to 10 feet away. You utter the message when you bestow this property on the object, and the recording can be no more than 6 seconds long. The object continuously emits your choice of an odor or a nonverbal sound (wind, waves, chirping, or the like). The flavor, color, or texture of the object changes. The object''s property lasts indefinitely. As an action, you can touch the object and end the property early. You can bestow magic on multiple objects, touching one object each time you use this feature, and a single object can have only one property at a time. The maximum number of objects you can have magic at once is equal to your Intelligence modifier (minimum of one). If you try to exceed your maximum, the oldest property immediately ends, and then the new property applies.'),
(208, 'Spellcasting', 2, 'When you reach 2nd level, you have learned to infuse a spark of magic into your handiwork. You can cast spells using your artificer spellcasting ability. To cast a spell, you must expend a spell slot of the spell''s level or higher, and you must provide the spell''s material components. You regain all expended spell slots when you finish a long rest. You know the following artificer spells, which don''t count against the number of wizard spells you know: 1st level: identify, shield; 2nd level: continual flame, heat metal; 3rd level: elemental weapon, protection from energy; 4th level: fabricate, stone shape; 5th level: creation, wall of sand.'),
(208, 'Infuse Item', 2, 'At 2nd level, you gain the ability to channel your artificer magic into objects. To use this feature, you must have thieves'' tools or artisan''s tools in hand. You can take an action to touch a nonmagical object and give it one of the following enhancements of your choice. Some enhancements require the object to be a weapon. The enhancement lasts indefinitely, but it might end early (see the description). You can enhance multiple objects, touching one object each time you use this feature, though a single object can only bear one enhancement at a time. The maximum number of objects you can enhance at once is equal to your Intelligence modifier (minimum of one). If you try to exceed your maximum, the oldest enhancement immediately ends, and then the new enhancement applies. Enhanced Weapon: This magic weapon grants a +1 bonus to attack and damage rolls made with it. The bonus increases to +2 when you reach 10th level in this class. Enhanced Defense: This suit of armor or shield grants a +1 bonus to AC. The bonus increases to +2 when you reach 10th level in this class. Enhanced Arcane Focus: While holding this tool, you gain a +1 bonus to spell attack rolls. The bonus increases to +2 when you reach 10th level in this class. Repulsion Shield: This shield grants you the ability to push back attackers. When a creature makes a successful melee attack against a target within 5 feet of you, you can use your reaction to push the attacker up to 15 feet away from the target. Spellwrought Tattoo: This tattoo contains a spell of 1st or 2nd level that you know. As an action, you can cause the tattoo to cast the spell using your spellcasting ability. Once used, the spell can''t be used again until you finish a long rest. Returning Weapon: This magic weapon grants a +1 bonus to attack and damage rolls made with it. The bonus increases to +2 when you reach 10th level in this class. When you hit with a ranged attack using this weapon, it returns to your hand immediately after the attack.'),
(208, 'Tool Expertise', 6, 'Starting at 6th level, your proficiency bonus is doubled for any ability check you make that uses your proficiency with a tool.'),
(208, 'Flash of Genius', 10, 'Starting at 10th level, you gain the ability to come up with solutions under pressure. When you or another creature you can see within 30 feet of you makes an ability check or a saving throw, you can use your reaction to add your Intelligence modifier to the roll. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(208, 'Magic Item Adept', 14, 'When you reach 14th level, you achieve a profound understanding of how to use and make magic items: You can attune to up to four magic items at once. If you craft a magic item with a rarity of common or uncommon, it takes you a quarter of the normal time, and it costs you half as much of the usual gold.'),
(208, 'Spell Storing Item', 14, 'At 14th level, you learn how to store spells in objects. Whenever you finish a long rest, you can touch one nonmagical object and store a spell in it of 1st or 2nd level from your artificer spell list. Any creature holding the object can take an action to release the spell with your spellcasting ability and without using a spell slot. If the spell requires concentration, the creature must concentrate. The spell stays in the object until it''s been used a number of times equal to twice your Intelligence modifier (minimum of twice) or until you use this feature again to store a different spell in the object.');

-- School of Invention (UA) (ID: 209)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(209, 'Arcanomechanical Armor', 2, 'At 2nd level, you don a suit of arcanomechanical armor. The armor is made of flexible metal plates and leather straps, and it''s covered in tiny gears, pistons, and vents. While wearing the armor, you gain the following benefits: The armor attaches to you and can''t be removed against your will. It replaces any armor you are wearing, and any AC bonus from the replaced armor no longer applies. You can don or doff the armor as an action. The armor has 20 hit points. If the armor is reduced to 0 hit points, it is destroyed. You can repair the armor over the course of a short rest with thieves'' tools or tinker''s tools, restoring 1 hit point for every 10 minutes you spend repairing it. While wearing the armor, you have a +1 bonus to AC, and you have advantage on saving throws against being poisoned. The armor includes a helmet with a thin slit for vision. While wearing the helmet, you have disadvantage on Wisdom (Perception) checks that rely on sight, but you are immune to the frightened condition. The armor has a small device on one forearm that allows you to cast mending at will. The armor has built-in compartments for storing items, increasing your carrying capacity by 20 pounds. The armor is magical and counts as a spellcasting focus for your wizard spells.'),
(209, 'Reckless Casting', 2, 'Starting at 2nd level, when you cast a spell with a casting time of 1 action, you can spend 1 sorcery point to change the casting time to 1 bonus action for this casting.'),
(209, 'Alchemical Casting', 6, 'Beginning at 6th level, you learn to channel magic through alchemical processes. When you cast a spell, you can expend one use of alchemist''s supplies as an additional cost to alter the spell''s damage type to acid, cold, fire, lightning, or poison. Additionally, you can expend one use of alchemist''s supplies to cast a spell as if you were using a 1st-level spell slot, without expending a spell slot. You can''t use this benefit again until you finish a short or long rest.'),
(209, 'Prodigious Invention', 10, 'At 10th level, you have created a prodigious invention. Choose one of the following options: Arcanomechanical Armor Upgrade: Your Arcanomechanical Armor gains an additional +1 bonus to AC. Additionally, you can use a bonus action to cause the armor to grant you a flying speed of 30 feet for 1 minute. Once you use this feature, you can''t use it again until you finish a long rest. Spell-Storing Item: You create a spell-storing item. This item can store up to 5 levels of spells. As an action, you can cast a spell into the item, using a spell slot as normal. The spell is stored in the item. As an action, any creature holding the item can release the spell, using your spellcasting ability. The spell uses your spell save DC. Once the item has stored spells totaling 5 levels, it can''t store more spells until it is recharged during a long rest. Wand Prototype: You create a wand prototype. As an action, you can use the wand to cast a cantrip that you know. The wand has 10 charges. When you cast a cantrip using the wand, expend 1 charge. The wand regains 1d6 + 4 charges daily at dawn. If you expend the wand''s last charge, roll a d20. On a 1, the wand crumbles into ash and is destroyed.'),
(209, 'Controlled Chaos', 14, 'Starting at 14th level, you have learned to control the chaotic nature of wild magic. When you roll on a Wild Magic Surge table, you can reroll the die and must use the new roll, even if it is another wild magic surge.');

-- Lore Mastery (UA) (ID: 210)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(210, 'Alchemical Casting', 2, 'At 2nd level, you learn to channel magic through alchemical processes. When you cast a spell, you can expend one use of alchemist''s supplies as an additional cost to alter the spell''s damage type to acid, cold, fire, lightning, or poison. Additionally, you can expend one use of alchemist''s supplies to cast a spell as if you were using a 1st-level spell slot, without expending a spell slot. You can''t use this benefit again until you finish a short or long rest.'),
(210, 'Spell Secrets', 2, 'Starting at 2nd level, you master the secrets of spellcasting, gaining the following benefits: Arcane Tradition: You gain proficiency in the Arcana skill, if you don''t already have it. Spell Knowledge: Choose two spells from any class''s spell list. The chosen spells count as wizard spells for you, but they don''t count against the number of wizard spells you know. Whenever you gain a level in this class, you can choose one of the spells you selected with this feature and replace it with another spell from any class''s spell list. Spell Versatility: When you cast a spell that deals damage, you can change the damage type to one of the following: acid, cold, fire, lightning, or poison.'),
(210, 'Alchemical Artillerist', 6, 'Beginning at 6th level, you learn to create alchemical items that can be used in combat. You can spend 1 hour and 50 gp to create one of the following items: Alchemist''s Fire (flask): As an action, a creature can throw this flask up to 20 feet, where it shatters on impact. Each creature in a 5-foot radius must make a Dexterity saving throw, taking 2d4 fire damage on a failed save, or half as much on a successful one. Acid (vial): As an action, a creature can throw this vial up to 20 feet, where it shatters on impact. Each creature in a 5-foot radius must make a Dexterity saving throw, taking 2d4 acid damage on a failed save, or half as much on a successful one. Antitoxin (vial): A creature can drink this vial as an action to remove the poisoned condition. Holy Water (flask): As an action, a creature can throw this flask up to 20 feet, where it shatters on impact. Each creature in a 5-foot radius must make a Dexterity saving throw, taking 2d4 radiant damage on a failed save, or half as much on a successful one. You can create a number of these items equal to your Intelligence modifier (minimum of one). You can''t create the same item more than once per long rest.'),
(210, 'Alchemical Adept', 10, 'At 10th level, your alchemical knowledge has deepened. You can now create more powerful alchemical items. You can spend 1 hour and 100 gp to create one of the following items: Bomb (grenade): As an action, a creature can throw this grenade up to 60 feet. Each creature in a 10-foot radius must make a Dexterity saving throw, taking 4d6 fire damage on a failed save, or half as much on a successful one. Healing Potion: A creature can drink this potion as an action to regain 2d4 + 2 hit points. Smoke Bomb: As an action, a creature can throw this bomb up to 20 feet, where it explodes in a 20-foot radius cloud of smoke. The cloud lasts for 1 minute or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it. Creatures in the cloud are blinded. You can create a number of these items equal to your Intelligence modifier (minimum of one). You can''t create the same item more than once per long rest.'),
(210, 'Alchemical Savant', 14, 'Starting at 14th level, you have mastered the art of alchemy. You can create alchemical items without spending gold or time. Additionally, you can create any alchemical item you know how to make, even if you don''t have the necessary materials. The item lasts for 24 hours before becoming inert.');

-- Onomancy (UA) (ID: 211)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(211, 'Explosive Echoes', 2, 'Starting at 2nd level, when you cast a spell with a spell slot, you can spend 1 sorcery point to cause any leftover energy from the spell to explode outward in a 10-foot radius from the spell''s point of origin. Each creature in the area, including you, must make a Dexterity saving throw against your spell save DC, taking 1d6 force damage on a failed save, or half as much on a successful one. The damage increases to 2d6 at 5th level, 3d6 at 11th level, and 4d6 at 17th level.'),
(211, 'Fortissimo', 2, 'At 2nd level, you can use your bonus action to empower your voice with magic. For 1 minute, any spell you cast that has a verbal component can be cast as if you were using a spell slot 1 level higher than the slot you expend. You can use this feature a number of times equal to your Charisma modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(211, 'Resonance', 6, 'Starting at 6th level, when you cast a spell with a verbal component, you can cause the spell to resonate with magical energy. Choose a number of creatures equal to your Charisma modifier (minimum of one) within 30 feet of you. Each chosen creature gains temporary hit points equal to your wizard level. These temporary hit points last for 1 hour.'),
(211, 'Crescendo', 10, 'Beginning at 10th level, when you cast a spell with a verbal component using a spell slot, you can cause the spell to crescendo, increasing its power. The spell''s range increases by 30 feet, and if the spell deals damage, it deals an extra 1d6 damage of the same type. You can use this feature a number of times equal to your Charisma modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(211, 'Symphony of Sound', 14, 'At 14th level, you can weave a symphony of sound around you. As an action, you create a 30-foot radius sphere of magical sound centered on you. For 1 minute, any creature that starts its turn in the sphere must succeed on a Constitution saving throw against your spell save DC or take 2d6 thunder damage and be deafened until the start of its next turn. Additionally, you and your allies in the sphere have advantage on saving throws against being deafened. Once you use this feature, you can''t use it again until you finish a long or long rest.');

-- Order Of Scribes (UA) (ID: 212)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(212, 'Wizardly Quill', 2, 'At 2nd level, as a bonus action, you can magically create a Tiny construct in the shape of a quill that hovers at your side. The construct lasts for 1 hour. For the duration, you can use it to write with your bonus action. The quill doesn''t require ink, and it never runs out. If you lose concentration on the spell, the quill disappears, but any writing it created remains. If you cast this spell while the quill is active, the spell fails.'),
(212, 'Awakened Spellbook', 2, 'Starting at 2nd level, you have infused extra magic into your spellbook, turning it into Awakened Spellbook. When you cast a wizard spell as a ritual, you can use the spell''s normal casting time, rather than adding 10 minutes to it. As an action, you can send the book up to 5 feet away from you. If you are within 5 feet of the book, you can touch it and cause it to open to a page of your choice. Additionally, the book can send you emotional signals if it is within 1,000 feet of you. These signals are a mix of emotions from the book, such as hunger, curiosity, or fear. You can interpret these signals intuitively. If the book takes damage while within 1,000 feet of you, you take the damage instead. The book has AC 15, 1 hit point, and immunity to poison and psychic damage. If the book is destroyed, you can perform a 1-hour ceremony to infuse a new book with the same magic. The ceremony destroys the previous book.'),
(212, 'Manifest Mind', 6, 'At 6th level, you can conjure forth the mind of your Awakened Spellbook. As a bonus action while your Awakened Spellbook is on the same plane of existence, you can cause a spectral manifestation of the book''s consciousness to appear in an unoccupied space within 60 feet of you or the book. The manifestation is a Tiny spectral object that is intangible and doesn''t occupy its space. The manifestation looks like a ghostly tome, a cascade of text, or a scholar from the past (your choice). For the next minute, the manifestation hovers in the air. If another creature uses its action to touch the manifestation, the creature takes 2d6 psychic damage. As a bonus action, you can move the manifestation up to 30 feet. If you have the manifestation move into a space occupied by a creature, you can have the creature make a Wisdom saving throw against your spell save DC. On a failed save, the creature takes 2d6 psychic damage. On a successful save, the manifestation can''t move through the creature''s space for 1 minute. The manifestation vanishes if it is reduced to 0 hit points, if you lose consciousness, or if you dismiss it as a bonus action. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(212, 'Master Scrivener', 10, 'Starting at 10th level, your Awakened Spellbook becomes animated by the magic of your words. When you cast a spell that requires a spellcasting focus, you can use your Awakened Spellbook as the focus instead of any material component. Additionally, if you have your Awakened Spellbook with you, you can cast any spell you have written in it without using a spell slot. Once you cast a spell from the book in this way, you can''t do so again until you finish a long rest. If you lose your Awakened Spellbook, you lose the benefits of this feature until you perform a 1-hour ceremony to infuse a new book with the same magic.'),
(212, 'One with the Word', 14, 'At 14th level, your connection to your Awakened Spellbook has become so profound that your soul has become linked to it. While the book is on the same plane of existence as you, you can communicate with it telepathically. Additionally, the book''s awareness expands. It knows everything you know and can see everything you see. If you are unconscious, blinded, deafened, or otherwise cut off from your senses, your Awakened Spellbook can see and hear for you. In addition, while you are within 1,000 feet of your Awakened Spellbook, you can take any action as a bonus action if that action only involves the book (such as reading it or writing in it).');

-- Psionics (UA) (ID: 213)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(213, 'Psionic Talent', 2, 'Starting at 2nd level, you harbor a wellspring of psionic energy within yourself. This energy is represented by your Psionic Energy dice, which are each a d6. The number of Psionic Energy dice you have is equal to your Intelligence modifier (minimum of one). You regain all expended Psionic Energy dice when you finish a long rest. Some of your features require a target to make a saving throw to resist the feature''s effects. The saving throw DC is calculated as follows: Psionic save DC = 8 + your proficiency bonus + your Intelligence modifier. You can use your Psionic Energy dice to fuel various psionic powers. Whenever you spend a Psionic Energy die, it is unavailable until you finish a long rest. You can spend your Psionic Energy dice on the following options: Psi-Bolstered Knack: When your proficiency bonus applies to a check, you can spend 1 Psionic Energy die, roll the die, and add the number rolled to the check. Psi-Powered Leap: As a bonus action, you can spend 1 Psionic Energy die to increase your jump distance by 10 feet per die spent. Psi-Enhanced Strength: As a bonus action, you can spend 1 Psionic Energy die to gain advantage on your next Strength (Athletics) check. Telekinetic Bolt: As an action, you can spend 1 Psionic Energy die to hurl a bolt of telekinetic force at a creature within 60 feet of you. Make a ranged spell attack. On a hit, the target takes 1d6 force damage per Psionic Energy die spent. Telekinetic Thrust: As an action, you can spend 1 Psionic Energy die to telekinetically move a creature or object within 30 feet of you. If the target is a creature, it must succeed on a Strength saving throw or be moved 10 feet in any direction of your choice. If the target is an object that weighs 200 pounds or less, you can move it 30 feet in any direction. If the object is being worn or carried by a creature, the creature must succeed on a Strength saving throw to prevent the movement.'),
(213, 'Telekinetic Hand', 6, 'At 6th level, you gain the ability to manipulate creatures and objects with your mind. As an action, you can attempt to shove a creature within 30 feet of you using your telekinetic ability. When you do so, the target must succeed on a Strength saving throw or be pushed 10 feet away from you. Additionally, you can use your action to create a spectral hand that can manipulate objects. The hand has a reach of 30 feet and can perform simple tasks such as opening doors, picking up objects, or retrieving items from containers. The hand can''t attack, cast spells, or activate magic items.'),
(213, 'Psionic Surge', 10, 'Starting at 10th level, you can overload yourself with psionic energy. As a bonus action, you can spend 1 Psionic Energy die to gain a surge of psionic power. For 1 minute, you gain the following benefits: You have resistance to psychic damage. When you hit a creature with a weapon attack, you can deal an extra 1d6 psychic damage to the target. You can teleport up to 30 feet as a bonus action. Once you use this feature, you can''t use it again until you finish a short or long rest.'),
(213, 'Psychic Crush', 14, 'At 14th level, you can crush a creature''s mind with your psionic power. As an action, you can target a creature within 60 feet of you. The target must make an Intelligence saving throw. On a failed save, the target takes 4d6 psychic damage and is stunned until the start of your next turn. On a successful save, the target takes half damage and isn''t stunned. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- Technomancy (UA) (ID: 214)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(214, 'Technological Savant', 2, 'At 2nd level, you gain proficiency with two of the following tools: alchemist''s supplies, artificer''s tools, smith''s tools, tinker''s tools, or vehicles (land). Additionally, you learn the mending cantrip if you don''t already know it.'),
(214, 'Spellcasting', 2, 'When you reach 2nd level, you have learned to infuse a spark of magic into your handiwork. You can cast spells using your artificer spellcasting ability. To cast a spell, you must expend a spell slot of the spell''s level or higher, and you must provide the spell''s material components. You regain all expended spell slots when you finish a long rest. You know the following artificer spells, which don''t count against the number of wizard spells you know: 1st level: identify, shield; 2nd level: continual flame, heat metal; 3rd level: elemental weapon, protection from energy; 4th level: fabricate, stone shape; 5th level: creation, wall of sand.'),
(214, 'Infuse Item', 2, 'At 2nd level, you gain the ability to channel your artificer magic into objects. To use this feature, you must have thieves'' tools or artisan''s tools in hand. You can take an action to touch a nonmagical object and give it one of the following enhancements of your choice. Some enhancements require the object to be a weapon. The enhancement lasts indefinitely, but it might end early (see the description). You can enhance multiple objects, touching one object each time you use this feature, though a single object can only bear one enhancement at a time. The maximum number of objects you can enhance at once is equal to your Intelligence modifier (minimum of one). If you try to exceed your maximum, the oldest enhancement immediately ends, and then the new enhancement applies. Enhanced Weapon: This magic weapon grants a +1 bonus to attack and damage rolls made with it. The bonus increases to +2 when you reach 10th level in this class. Enhanced Defense: This suit of armor or shield grants a +1 bonus to AC. The bonus increases to +2 when you reach 10th level in this class. Enhanced Arcane Focus: While holding this tool, you gain a +1 bonus to spell attack rolls. The bonus increases to +2 when you reach 10th level in this class. Repulsion Shield: This shield grants you the ability to push back attackers. When a creature makes a successful melee attack against a target within 5 feet of you, you can use your reaction to push the attacker up to 15 feet away from the target. Spellwrought Tattoo: This tattoo contains a spell of 1st or 2nd level that you know. As an action, you can cause the tattoo to cast the spell using your spellcasting ability. Once used, the spell can''t be used again until you finish a long rest. Returning Weapon: This magic weapon grants a +1 bonus to attack and damage rolls made with it. The bonus increases to +2 when you reach 10th level in this class. When you hit with a ranged attack using this weapon, it returns to your hand immediately after the attack.'),
(214, 'Experimental Elixir', 6, 'Beginning at 6th level, whenever you finish a short or long rest, you can magically produce an experimental elixir in an empty flask you touch. Roll on the Experimental Elixir table to determine the elixir''s effect. The elixir lasts for 1 hour or until you drink it. You can create a number of elixirs equal to your Intelligence modifier (minimum of one). Experimental Elixir: 1 - Healing: When you drink the elixir, you regain 2d4 + 2 hit points. 2 - Swiftness: When you drink the elixir, you gain a +10 feet bonus to your speed for 1 hour. 3 - Resilience: When you drink the elixir, you gain resistance to poison damage for 1 hour. 4 - Boldness: When you drink the elixir, you gain advantage on saving throws against being frightened for 1 hour. 5 - Flight: When you drink the elixir, you gain a flying speed of 30 feet for 1 hour. 6 - Transformation: When you drink the elixir, you can polymorph into a beast of CR 1 or lower for 1 hour.'),
(214, 'Alchemical Fire', 10, 'At 10th level, you learn how to produce alchemical fire. As an action, you can produce a vial of alchemist''s fire. You can use this vial as a weapon. As an action, a creature can throw the vial up to 20 feet, where it shatters on impact. Make a ranged attack roll against a target within 5 feet of the point of impact. On a hit, the target takes 2d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 13 Dexterity check to extinguish the flames. You can create a number of vials equal to your Intelligence modifier (minimum of one). You regain all expended vials when you finish a long rest.'),
(214, 'Restorative Reagents', 14, 'Starting at 14th level, you can produce restorative reagents. As an action, you can produce a vial of restorative reagent. You can use this vial to cast lesser restoration without expending a spell slot. You can create a number of vials equal to your Intelligence modifier (minimum of one). You regain all expended vials when you finish a long rest.');

-- Theurgy (UA) (ID: 215)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(215, 'Divine Inspiration', 2, 'At 2nd level, your connection to the divine allows you to learn spells normally associated with the cleric class. When your Spellcasting feature lets you learn a wizard cantrip or a wizard spell of 1st level or higher, you can choose the new spell from the cleric spell list, in addition to the wizard spell list. You must otherwise obey all the restrictions for selecting the spell, and it becomes a wizard spell for you. Additionally, you learn the toll the dead cantrip.'),
(215, 'Arcane Initiate', 2, 'When you reach 2nd level, you can channel divine energy to cast spells. You have a pool of divine energy represented by d6s equal to your Intelligence modifier (minimum of one). You regain all expended dice when you finish a long rest. As a bonus action, you can expend one divine energy die to cast a cleric cantrip that you know. The cantrip uses your spellcasting ability. Additionally, when you cast a spell using a spell slot, you can expend one divine energy die to change the spell''s damage type to radiant or necrotic.'),
(215, 'Channel Arcane', 6, 'Starting at 6th level, you can channel arcane energy through your divine connection. As a bonus action, you can expend one divine energy die to gain advantage on your next spell attack roll or to give one creature within 30 feet of you disadvantage on its next saving throw against a spell you cast. Additionally, when you cast a spell that deals damage, you can expend one divine energy die to deal maximum damage with that spell against one target.'),
(215, 'Arcane Priest', 10, 'Beginning at 10th level, your divine and arcane powers merge. When you cast a spell using a spell slot, you can expend one divine energy die to cast it as if it were cast using a spell slot one level higher. Additionally, you can use your Channel Divinity feature to cast spells. When you use your Channel Divinity, you can choose to cast a cleric spell that you know instead of using the normal effect of your Channel Divinity.'),
(215, 'Arcane High Priest', 14, 'At 14th level, your mastery of divine and arcane magic reaches its peak. You can cast any cleric spell you know without expending a spell slot. Once you cast a cleric spell in this way, you can''t do so again until you finish a long rest. Additionally, when you cast a spell that deals damage, you can expend one divine energy die to deal an extra 1d6 radiant or necrotic damage (your choice) to each target.');

-- Mage of Lorehold (UA) (ID: 216)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(216, 'Lorehold Primer', 2, 'At 2nd level, you gain proficiency in the History skill, if you don''t already have it. Additionally, you learn the comprehend languages and identify spells, which don''t count against the number of wizard spells you know.'),
(216, 'Lorehold Manifestation', 2, 'Starting at 2nd level, you can channel the power of ancient knowledge to manifest a spectral tome. As a bonus action, you can cause a spectral tome to appear in your hand. The tome has the following properties: The tome contains a number of pages equal to your wizard level. As an action, you can expend 1 page to cast a wizard cantrip that you know. The tome vanishes if you are incapacitated or if you dismiss it as a bonus action. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(216, 'Archivist''s Insight', 6, 'Beginning at 6th level, you can draw on the knowledge of ancient archivists. When you make an Intelligence check to recall lore about a person, place, or thing, you can add your proficiency bonus to the check even if you''re not proficient in the skill used. Additionally, when you cast a spell that deals damage, you can expend 1 page from your Lorehold Manifestation to deal an extra 1d6 force damage to one target of the spell.'),
(216, 'Lorehold Legacy', 10, 'Starting at 10th level, you can tap into the legacy of Lorehold to empower your spells. When you cast a spell, you can expend 1 page from your Lorehold Manifestation to cast the spell as if it were cast using a spell slot one level higher. Additionally, you can use your action to cause the spectral tome to unleash a burst of knowledge. Each creature of your choice within 30 feet of you must make an Intelligence saving throw against your spell save DC. A creature takes 2d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(216, 'Archmage of Lorehold', 14, 'At 14th level, your connection to the ancient knowledge of Lorehold allows you to manifest powerful effects. When you cast a spell, you can expend 2 pages from your Lorehold Manifestation to cause the spell to affect an additional target. Additionally, you can use your action to cause the spectral tome to unleash a wave of knowledge. Each creature in a 30-foot cone must make an Intelligence saving throw against your spell save DC. A creature takes 4d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- Mage of Prismari (UA) (ID: 217)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(217, 'Elemental Affinity', 2, 'At 2nd level, you gain an affinity for one of the four elements: fire, water, air, or earth. Choose one of these elements. You learn a cantrip based on your chosen element: Fire: fire bolt; Water: shape water; Air: gust; Earth: mold earth. Additionally, when you cast a spell that deals damage of your chosen element, you can add your Intelligence modifier to one damage roll of that spell.'),
(217, 'Prismatic Flourish', 2, 'Starting at 2nd level, you can infuse your spells with prismatic energy. When you cast a spell that deals damage, you can spend 1 sorcery point to change the damage type to one of the following: acid, cold, fire, lightning, or poison. Additionally, you can use your bonus action to create a prismatic barrier. For 1 minute, you have resistance to damage of one type of your choice: acid, cold, fire, lightning, or poison.'),
(217, 'Elemental Eruption', 6, 'Beginning at 6th level, when you cast a spell that deals damage of your chosen element, you can cause elemental energy to erupt from the target. Each creature within 5 feet of the target must make a Dexterity saving throw against your spell save DC, taking 1d6 damage of your chosen element on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(217, 'Prismatic Shield', 10, 'Starting at 10th level, you can create a prismatic shield to protect yourself. As a reaction when you take damage, you can spend 1 sorcery point to reduce the damage by an amount equal to your wizard level + your Intelligence modifier. Additionally, you can use your action to create a prismatic dome. For 1 minute, you and creatures of your choice within 10 feet of you have resistance to damage from spells.'),
(217, 'Prismatic Burst', 14, 'At 14th level, you can unleash a burst of prismatic energy. As an action, you can spend 3 sorcery points to create a 20-foot radius sphere of prismatic energy centered on a point within 120 feet of you. Each creature in the sphere must make a Dexterity saving throw against your spell save DC. A creature takes 4d6 damage of a random type (acid, cold, fire, lightning, or poison) on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- Mage of Quandrix (UA) (ID: 218)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(218, 'Quandrix Initiate', 2, 'At 2nd level, you learn the druidcraft and mold earth cantrips, which don''t count against the number of wizard cantrips you know. Additionally, you gain proficiency in the Nature skill, if you don''t already have it.'),
(218, 'Quandrix Manifestation', 2, 'Starting at 2nd level, you can channel the power of mathematics to manifest a quandrix fractal. As a bonus action, you can cause a quandrix fractal to appear in an unoccupied space within 30 feet of you. The fractal is a Medium object with AC 15, 10 hit points, and immunity to poison and psychic damage. The fractal lasts for 1 minute or until you dismiss it as a bonus action. While the fractal exists, you can use your action to cause it to move up to 30 feet to an unoccupied space within 30 feet of you. Additionally, when you cast a spell that deals damage, you can cause the fractal to erupt, dealing 1d6 force damage to each creature within 5 feet of it. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(218, 'Quandrix Computation', 6, 'Beginning at 6th level, you can use your knowledge of mathematics to enhance your spells. When you cast a spell that requires a saving throw, you can add your Intelligence modifier to the spell''s save DC. Additionally, when you cast a spell that deals damage, you can add your Intelligence modifier to one damage roll of that spell. You can use each benefit a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(218, 'Fractal Bloom', 10, 'Starting at 10th level, you can cause your quandrix fractal to bloom with mathematical energy. As an action, you can cause the fractal to bloom, creating a 20-foot radius sphere of mathematical energy centered on the fractal. Each creature in the sphere must make an Intelligence saving throw against your spell save DC. A creature takes 2d6 psychic damage on a failed save, or half as much on a successful one. Additionally, you can teleport to an unoccupied space within 30 feet of the fractal. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(218, 'Infinite Equation', 14, 'At 14th level, your mastery of quandrix mathematics allows you to manipulate reality. When you cast a spell, you can change the spell''s range to any range of your choice, up to the spell''s normal range. Additionally, you can use your action to cause your quandrix fractal to unleash infinite equations. Each creature within 30 feet of the fractal must make an Intelligence saving throw against your spell save DC. A creature takes 4d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');

-- Mage of Silverquill (UA) (ID: 219)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(219, 'Silverquill Primer', 2, 'At 2nd level, you gain proficiency in the Persuasion skill, if you don''t already have it. Additionally, you learn the vicious mockery and friends cantrips, which don''t count against the number of wizard cantrips you know.'),
(219, 'Silverquill Manifestation', 2, 'Starting at 2nd level, you can channel the power of words to manifest a silverquill quill. As a bonus action, you can cause a silverquill quill to appear in your hand. The quill has the following properties: The quill has 10 charges. When you hit with a spell attack, you can expend 1 charge to deal an extra 1d6 psychic damage. As an action, you can expend 1 charge to cast a wizard cantrip that you know. The quill vanishes if you are incapacitated or if you dismiss it as a bonus action. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(219, 'Rhetorical Flourish', 6, 'Beginning at 6th level, you can use your words to enhance your spells. When you cast a spell that requires a saving throw, you can add your Intelligence modifier to the spell''s save DC. Additionally, when you cast a spell that deals damage, you can expend 1 charge from your Silverquill Manifestation to deal an extra 1d6 psychic damage to one target of the spell. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(219, 'Silverquill Legacy', 10, 'Starting at 10th level, you can tap into the legacy of Silverquill to empower your spells. When you cast a spell, you can expend 1 charge from your Silverquill Manifestation to cast the spell as if it were cast using a spell slot one level higher. Additionally, you can use your action to cause the silverquill quill to unleash a burst of words. Each creature of your choice within 30 feet of you must make a Charisma saving throw against your spell save DC. A creature takes 2d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(219, 'Archmage of Silverquill', 14, 'At 14th level, your connection to the eloquent words of Silverquill allows you to manifest powerful effects. When you cast a spell, you can expend 2 charges from your Silverquill Manifestation to cause the spell to affect an additional target. Additionally, you can use your action to cause the silverquill quill to unleash a wave of words. Each creature in a 30-foot cone must make a Charisma saving throw against your spell save DC. A creature takes 4d6 psychic damage on a failed save, or half as much on a successful one. You can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.');
