-- =============================================================================
-- PALADIN SUBCLASSES 
-- =============================================================================

-- Oath of the Ancients (ID 110)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(110, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of the Ancients Spells Paladin Level Spells 3rd Ensnaring Strike, Speak with Animals 5th Moonbeam, Misty Step 9th Plant Growth, Protection from Energy 13th Ice Storm, Stoneskin 17th Commune with Nature, Tree Stride'),
(110, 'Channel Divinity', 3, 'When you take this oath at 3rd level, you gain the following two Channel Divinity options. Nature''s Wrath. You can use your Channel Divinity to invoke primeval forces to ensnare a foe. As an action, you can cause spectral vines to spring up and reach for a creature within 10 feet of you that you can see. The creature must succeed on a Strength or Dexterity saving throw (its choice) or be restrained. While restrained by the vines, the creature repeats the saving throw at the end of each of its turns. On a success, it frees itself and the vines vanish. Turn the Faithless. You can use your Channel Divinity to utter ancient words that are painful for fey and fiends to hear. As an action, you present your holy symbol, and each fey or fiend within 30 feet of you that can hear you must make a Wisdom saving throw. On a failed save, the creature is turned for 1 minute or until it takes damage. A turned creature must spend its turns trying to move as far away from you as it can, and it can''t willingly move to a space within 30 feet of you. It also can''t take reactions. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If there''s nowhere to move, the creature can use the Dodge action. If the creature''s true form is concealed by an illusion, shapeshifting, or other effect, that form is revealed while it is turned.'),
(110, 'Aura of Warding', 7, 'Beginning at 7th level, ancient magic lies so heavily upon you that it forms an eldritch ward. You and friendly creatures within 10 feet of you have resistance to damage from spells. At 18th level, the range of this aura increases to 30 feet.'),
(110, 'Undying Sentinel', 15, 'Starting at 15th level, when you are reduced to 0 hit points and are not killed outright, you can choose to drop to 1 hit point instead. Once you use this ability, you can''t use it again until you finish a long rest. Additionally, you suffer none of the drawbacks of old age, and you can''t be aged magically.'),
(110, 'Elder Champion', 20, 'At 20th level, you can assume the form of an ancient force of nature, taking on an appearance you choose. For example, your skin might turn green or take on a bark-like texture, your hair might become leafy or moss-like, or you might sprout antlers or a lion-like mane. Using your action, you undergo a transformation. For 1 minute, you gain the following benefits: At the start of each of your turns, you regain 10 hit points. Whenever you cast a paladin spell that has a casting time of 1 action, you can cast it using a bonus action instead. Enemy creatures within 10 feet of you have disadvantage on saving throws against your paladin spells and Channel Divinity options.');

-- Oath of Conquest (ID 111)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(111, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Conquest Spells Paladin Level Spells 3rd Armor of Agathys, Command 5th Hold Person, Spiritual Weapon 9th Bestow Curse, Fear 13th Dominate Beast, Stoneskin 17th Cloudkill, Dominate Person'),
(111, 'Channel Divinity', 3, 'When you take this oath at 3rd level, you gain the following two Channel Divinity options. Conquering Presence. You can use your Channel Divinity to exude a terrifying presence. As an action, you force each creature of your choice that you can see within 30 feet of you to make a Wisdom saving throw. On a failed save, a creature becomes frightened of you for 1 minute. The frightened creature can repeat this saving throw at the end of each of its turns, ending the effect on itself on a success. Guided Strike. You can use your Channel Divinity to strike with supernatural accuracy. When you make an attack roll, you can use your Channel Divinity to gain a +10 bonus to the roll. You make this choice after you see the roll, but before the DM says whether the attack hits or misses.'),
(111, 'Aura of Conquest', 7, 'You constantly emanate a menacing aura while you''re not incapacitated. The aura extends 10 feet from you in every direction, but not through total cover. If a creature is frightened of you, its speed is reduced to 0 while in the aura, and that creature takes psychic damage equal to half your paladin level if it starts its turn there. At 18th level, the range of this aura increases to 30 feet.'),
(111, 'Scornful Rebuke', 15, 'Those who dare to strike you are psychically punished for their audacity. Whenever a creature hits you with an attack, that creature takes psychic damage equal to your Charisma modifier (minimum of 1) if you''re not incapacitated.'),
(111, 'Invincible Conqueror', 20, 'You gain the ability to harness extraordinary martial prowess. As an action, you can magically become an avatar of conquest, gaining the following benefits for 1 minute: You have resistance to all damage. When you take the Attack action on your turn, you can make one additional attack as part of that action. Your melee weapon attacks score a critical hit on a roll of 19 or 20 on the d20. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Oath of the Crown (ID 112)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(112, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of the Crown Spells Paladin Level Spells 3rd Command, Compelled Duel 5th Warding Bond, Zone of Truth 9th Aura of Vitality, Spirit Guardians 13th Banishment, Guardian of Faith 17th Circle of Power, Geas'),
(112, 'Channel Divinity', 3, 'When you take this oath at 3rd level, you gain the following two Channel Divinity options. Champion Challenge. As a bonus action, you issue a challenge that compels other creatures to do battle with you. Each creature of your choice that you can see within 30 feet of you must make a Wisdom saving throw. On a failed save, a creature can''t willingly move more than 30 feet away from you. This effect ends on the creature if you are incapacitated or die or if the creature is more than 30 feet away from you. Turn the Tide. As a bonus action, you can bolster injured creatures with your Channel Divinity. Each creature of your choice that can hear you within 30 feet of you regains hit points equal to 1d6 + your Charisma modifier (minimum of 1) if it has no more than half of its hit points.'),
(112, 'Divine Allegiance', 7, 'When a creature within 5 feet of you takes damage, you can use your reaction to magically substitute your own health for that of the target creature, causing that creature not to take the damage. Instead, you take the damage. This damage to you can''t be reduced or prevented in any way.'),
(112, 'Unyielding Saint', 15, 'You have advantage on saving throws to avoid becoming paralyzed or stunned.'),
(112, 'Exalted Champion', 20, 'Your presence on the field of battle is an inspiration to those dedicated to your cause. You can use your action to gain the following benefits for 1 hour: You have resistance to bludgeoning, piercing, and slashing damage from nonmagical weapons. Your allies have advantage on death saving throws while within 30 feet of you. You have advantage on Wisdom saving throws, as do your allies within 30 feet of you. This effect ends early if you are incapacitated or die. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Oath of Devotion (ID 113)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(113, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Devotion Spells Paladin Level Spells 3rd Protection from Evil and Good, Sanctuary 5th Lesser Restoration, Zone of Truth 9th Beacon of Hope, Dispel Magic 13th Freedom of Movement, Guardian of Faith 17th Commune, Flame Strike'),
(113, 'Sacred Weapon', 3, 'As an action, you can imbue one weapon that you are holding with positive energy, using your Channel Divinity. For 1 minute, you add your Charisma modifier to attack rolls made with that weapon (with a minimum bonus of +1). The weapon also emits bright light in a 20-foot radius and dim light 20 feet beyond that. If the weapon is not already magical, it becomes magical for the duration. You can end this effect on your turn as part of any other action. If you are no longer holding or carrying this weapon, or if you fall unconscious, this effect ends.'),
(113, 'Turn the Unholy', 3, 'As an action, you present your holy symbol and speak a prayer censuring fiends and undead, using your Channel Divinity. Each fiend or undead that can see or hear you within 30 feet of you must make a Wisdom saving throw. If the creature fails its saving throw, it is turned for 1 minute or until it takes damage. A turned creature must spend its turns trying to move as far away from you as it can, and it can''t willingly move to a space within 30 feet of you. It also can''t take reactions. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If there''s nowhere to move, the creature can use the Dodge action.'),
(113, 'Aura of Devotion', 7, 'You and friendly creatures within 10 feet of you can''t be charmed while you are conscious. At 18th level, the range of this aura increases to 30 feet.'),
(113, 'Purity of Spirit', 15, 'You are always under the effects of a Protection from Evil and Good spell.'),
(113, 'Holy Nimbus', 20, 'As an action, you can emanate an aura of sunlight. For 1 minute, bright light shines from you in a 30-foot radius, and dim light shines 30 feet beyond that. Whenever an enemy creature starts its turn in the bright light, the creature takes 10 radiant damage. In addition, for the duration, you have advantage on saving throws against spells cast by fiends or undead. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Oath of Glory (ID 114)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(114, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Glory Spells Paladin Level Spells 3rd Guiding Bolt, Heroism 5th Enhance Ability, Magic Weapon 9th Haste, Protection From Energy 13th Compulsion, Freedom Of Movement 17th Commune, Flame Strike'),
(114, 'Peerless Athlete', 3, 'As a bonus action, you can use your Channel Divinity to augment your athleticism. For the next 10 minutes, you have advantage on Strength (Athletics) and Dexterity (Acrobatics) checks; you can carry, push, drag, and lift twice as much weight as normal; and the distance of your long and high jumps increases by 10 feet (this extra distance costs movement as normal).'),
(114, 'Inspiring Smite', 3, 'Immediately after you deal damage to a creature with your Divine Smite feature, you can use your Channel Divinity as a bonus action and distribute temporary hit points to creatures of your choice within 30 feet of you, which can include you. The total number of temporary hit points equals 2d8 + your level in this class, divided among the chosen creatures however you like.'),
(114, 'Aura of Alacrity', 7, 'You emanate an aura that fills you and your companions with supernatural speed, allowing you to race across a battlefield in formation. Your walking speed increases by 10 feet. In addition, if you aren''t incapacitated, the walking speed of any ally who starts their turn within 5 feet of you increases by 10 feet until the end of that turn. At 18th level, the range of your Aura of Alacrity increases to 10 feet.'),
(114, 'Glorious Defense', 15, 'You can turn defense into a sudden strike. When you or another creature you can see within 10 feet of you is hit by an attack roll, you can use your reaction to grant a bonus to the target''s AC against that attack, potentially causing it to miss. The bonus equals your Charisma modifier (minimum of +1). If the attack misses, you can make one weapon attack against the attacker as part of this reaction, provided the attacker is within your weapon''s range. You can use this feature a number of times equal to your Charisma modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(114, 'Living Legend', 20, 'You can empower yourself with the legends — whether true or exaggerated — of your great deeds. As a bonus action, you gain the following benefits for 1 minute: You are blessed with an otherworldly presence, gaining advantage on all Charisma checks. Once on each of your turns when you make a weapon attack and miss, you can cause that attack to hit instead. If you fail a saving throw, you can use your reaction to reroll it. You must use this new roll. Once you use this feature, you can''t use it again until you finish a long rest, unless you expend a 5th-level spell slot to use it again.');

-- Oath of Redemption (ID 115)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(115, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Redemption Spells Paladin Level Spells 3rd Sanctuary, Sleep 5th Calm Emotions, Hold Person 9th Counterspell, Hypnotic Pattern 13th Otiluke''s Resilient Sphere, Stoneskin 17th Hold Monster, Wall of Force'),
(115, 'Emissary of Peace', 3, 'You can use your Channel Divinity to augment your presence with divine power. As a bonus action, you grant yourself a +5 bonus to Charisma (Persuasion) checks for the next 10 minutes.'),
(115, 'Rebuke the Violent', 3, 'You can use your Channel Divinity to rebuke those who use violence. Immediately after an attacker within 30 feet of you deals damage with an attack against a creature other than you, you can use your reaction to force the attacker to make a Wisdom saving throw. On a failed save, the attacker takes radiant damage equal to the damage it just dealt. On a successful save, it takes half as much damage.'),
(115, 'Aura of the Guardian', 7, 'You can shield your allies from harm at the cost of your own health. When a creature within 10 feet of you takes damage, you can use your reaction to magically take that damage, instead of that creature taking it. This feature doesn''t transfer any other effects that might accompany the damage, and this damage can''t be reduced in any way. At 18th level, the range of your Aura of the Guardian increases to 30 feet.'),
(115, 'Protective Spirit', 15, 'A holy presence mends your wounds in combat. You regain hit points equal to 1d6 + half your paladin level if you end your turn in combat with fewer than half of your hit points remaining and you aren''t incapacitated.'),
(115, 'Emissary of Redemption', 20, 'You become an avatar of peace, which gives you two benefits: You have resistance to all damage dealt by other creatures (their attacks, spells, and other effects). Whenever a creature hits you with an attack, it takes radiant damage equal to half the damage you take from the attack. If you attack a creature, cast a spell on it, or deal damage to it by any means but this feature, neither benefit works against that creature until you finish a long rest.');

-- Oath of Vengeance (ID 116)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(116, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Vengeance Spells Paladin Level Spells 3rd Bane, Hunter''s Mark 5th Hold Person, Misty Step 9th Haste, Protection from Energy 13th Banishment, Dimension Door 17th Hold Monster, Scrying'),
(116, 'Abjure Enemy', 3, 'As an action, you present your holy symbol and speak a prayer of denunciation, using your Channel Divinity. Choose one creature within 60 feet of you that you can see. That creature must make a Wisdom saving throw, unless it is immune to being frightened. Fiends and undead have disadvantage on this saving throw. On a failed save, the creature is frightened for 1 minute or until it takes any damage. While frightened, the creature''s speed is 0, and it can''t benefit from any bonus to its speed. On a successful save, the creature''s speed is halved for 1 minute or until the creature takes any damage.'),
(116, 'Vow of Enmity', 3, 'As a bonus action, you can utter a vow of enmity against a creature you can see within 10 feet of you, using your Channel Divinity. You gain advantage on attack rolls against the creature for 1 minute or until it drops to 0 hit points or falls unconscious.'),
(116, 'Relentless Avenger', 7, 'Your supernatural focus helps you close off a foe''s retreat. When you hit a creature with an opportunity attack, you can move up to half your speed immediately after the attack and as part of the same reaction. This movement doesn''t provoke opportunity attacks.'),
(116, 'Soul of Vengeance', 15, 'The authority with which you speak your Vow of Enmity gives you greater power over your foe. When a creature under the effect of your Vow of Enmity makes an attack, you can use your reaction to make a melee weapon attack against that creature if it is within range.'),
(116, 'Avenging Angel', 20, 'You can assume the form of an angelic avenger. Using your action, you undergo a transformation. For 1 hour, you gain the following benefits: Wings sprout from your back and grant you a flying speed of 60 feet. You emanate an aura of menace in a 30-foot radius. The first time any enemy creature enters the aura or starts its turn there during a battle, the creature must succeed on a Wisdom saving throw or become frightened of you for 1 minute or until it takes any damage. Attack rolls against the frightened creature have advantage. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Oath of the Watchers (ID 117)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(117, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of the Watchers Spells Paladin Level Spells 3rd Alarm, Detect Magic 5th Moonbeam, See Invisibility 9th Counterspell, Nondetection 13th Aura of Purity, Banishment 17th Hold Monster, Scrying'),
(117, 'Watcher''s Will', 3, 'You can use your Channel Divinity to invest your presence with the warding power of your faith. As an action, you can choose a number of creatures you can see within 30 feet of you, up to a number equal to your Charisma modifier (minimum of one creature). For 1 minute, you and the chosen creatures have advantage on Intelligence, Wisdom, and Charisma saving throws.'),
(117, 'Abjure the Extraplanar', 3, 'You can use your Channel Divinity to castigate unworldly beings. As an action, you present your holy symbol and each aberration, celestial, elemental, fey, or fiend within 30 feet of you that can hear you must make a Wisdom saving throw. On a failed save, the creature is turned for 1 minute or until it takes damage. A turned creature must spend its turns trying to move as far away from you as it can, and it can''t willingly end its move in a space within 30 feet of you. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If there''s nowhere to move, the creature can take the Dodge action.'),
(117, 'Aura of the Sentinel', 7, 'You emit an aura of alertness while you aren''t incapacitated. When you and any creatures of your choice within 10 feet of you roll initiative, you all gain a bonus to initiative equal to your proficiency bonus. At 18th level, the range of your Aura of the Sentinel increases to 30 feet.'),
(117, 'Vigilant Rebuke', 15, 'You''ve learned how to chastise anyone who dares wield beguilements against you and your wards. Whenever you or a creature you can see within 30 feet of you succeeds on an Intelligence, a Wisdom, or a Charisma saving throw, you can use your reaction to deal 2d8 + your Charisma modifier force damage to the creature that forced the saving throw.'),
(117, 'Mortal Bulwark', 20, 'You manifest a spark of divine power in defense of the mortal realms. As a bonus action, you gain the following benefits for 1 minute: You gain truesight with a range of 120 feet. You have advantage on attack rolls against aberrations, celestials, elementals, fey, and fiends. When you hit a creature with an attack roll and deal damage to it, you can also force it to make a Charisma saving throw against your spell save DC. On a failed save, the creature is magically banished to its native plane of existence if it''s currently not there. On a successful save, the creature can''t be banished by this feature for 24 hours. Once you use this bonus action, you can''t use it again until you finish a long rest, unless you expend a 5th-level spell slot to use it again.');

-- Oathbreaker (ID 118)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(118, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oathbreaker Spells Paladin Level Spells 3rd Hellish Rebuke, Inflict Wounds 5th Crown of Madness, Darkness 9th Animate Dead, Bestow Curse 13th Blight, Confusion 17th Contagion, Dominate Person'),
(118, 'Control Undead', 3, 'As an action, you target one undead creature you can see within 30 feet of you. The target must make a Wisdom saving throw. On a failed save, the target must obey your commands for the next 24 hours, or until you use this Channel Divinity option again. An undead whose challenge rating is equal to or greater than your paladin level is immune to this effect.'),
(118, 'Dreadful Aspect', 3, 'As an action, you channel the darkest emotions and focus them into a burst of magical menace. Each creature of your choice within 30 feet of you that can see you must make a Wisdom saving throw if it can see you. On a failed save, the target is frightened of you for 1 minute. If a creature frightened by this effect ends its turn more than 30 feet away from you, it can attempt another Wisdom saving throw to end the effect on it.'),
(118, 'Aura of Hate', 7, 'You, as well any fiends and undead within 10 feet of you, gain a bonus to melee weapon damage rolls equal to your Charisma modifier (minimum of +1). A creature can benefit from this feature from only one paladin at a time. At 18th level, the range of this aura increases to 30 feet.'),
(118, 'Supernatural Resistance', 15, 'You gain resistance to bludgeoning, piercing, and slashing damage from nonmagical weapons.'),
(118, 'Dread Lord', 20, 'You can, as an action, surround yourself with an aura of gloom that lasts for 1 minute. The aura reduces any bright light in a 30-foot radius around you to dim light. Whenever an enemy that is frightened by you starts its turn in the aura, it takes 4d10 psychic damage. Additionally, you and any creatures of your choosing in the aura are draped in deeper shadow. Creatures that rely on sight have disadvantage on attack rolls against creatures draped in this shadow. While the aura lasts, you can use a bonus action on your turn to cause the shadows in the aura to attack one creature. Make a melee spell attack against the target. If the attack hits, the target takes necrotic damage equal to 3d10 + your Charisma modifier. After activating the aura, you can''t do so again until you finish a long rest.');

-- Oath of Treachery (UA) (ID 119)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(119, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Treachery Spells Paladin Level Spells 3rd Charm Person, Expeditious Retreat 5th Invisibility, Mirror Image 9th Gaseous Form, Haste 13th Confusion, Greater Invisibility 17th Dominate Person, Passwall'),
(119, 'Conjure Duplicate', 3, 'As an action, you create a visual illusion of yourself that lasts for 1 minute, or until you lose your concentration (as if you were concentrating on a spell). The illusion appears in an unoccupied space of your choice that you can see within 30 feet of you. The illusion looks exactly like you; it is silent; it is your size, is insubstantial, and doesn''t occupy its space; and it is unaffected by attacks and damage. As a bonus action on your turn, you can move the illusion up to 30 feet to a space you can see, but the illusion must remain within 120 feet of you. For the duration, you can cast spells as though you were in the illusion''s space, but you must use your own senses. Additionally, when both you and your illusion are within 5 feet of a creature that can see the illusion, you have advantage on attack rolls against that creature, given how uncanny the illusion is.'),
(119, 'Poison Strike', 3, 'You can use your Channel Divinity to make a weapon deadlier. As a bonus action, you touch one weapon or piece of ammunition and conjure a special poison on it. The poison lasts for 1 minute. The next time you hit a target with an attack using that weapon or ammunition, the target takes poison damage immediately after the attack. The poison damage equals 2d10 + your paladin level, or 20 + your paladin level if you had advantage on the attack roll.'),
(119, 'Aura of Treachery', 7, 'You emanate an aura of discord, which gives you the following benefits. Cull the Herd: You have advantage on melee attack rolls against any creature that has one or more of its allies within 5 feet of it. Treacherous Strike: If a creature within 5 feet of you misses you with a melee attack, you can use your reaction to force the attacker to reroll that attack against a creature of your choice that is also within 5 feet of the attacker. The ability fails and is wasted if the attacker is immune to being charmed. You can use this ability three times, and regain expended uses of it when you finish a short or long rest.'),
(119, 'Blackguard''s Escape', 15, 'You have the ability to slip away from your foes. Immediately after you are hit by an attack, you can use your reaction to turn invisible and teleport up to 60 feet to a spot you can see. You remain invisible until the end of your next turn or until you attack, deal damage, or force a creature to make a saving throw. Once you use this feature, you must finish a short or long rest before you can use it again.'),
(119, 'Icon of Deceit', 20, 'You gain the ability to emanate feelings of treachery. As an action, you can magically become an avatar of deceit, gaining the following benefits for 1 minute: You are invisible. If a creature damages you on its turn, it must succeed on a Wisdom saving throw (DC equal to your spell save DC) or you control its next action, provided that you aren''t incapacitated when it takes the action. A creature automatically succeeds on the save if the creature is immune to being charmed. If you have advantage on an attack roll, you gain a bonus to its damage roll equal to your paladin level.');

-- Oath of Redemption (UA) (ID 120)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(120, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Redemption Spells Paladin Level Spells 3rd Shield, Sleep 5th Hold Person, Ray of Enfeeblement 9th Counterspell, Hypnotic Pattern 13th Otiluke''s Resilient Sphere, Stoneskin 17th Hold Monster, Wall of Force'),
(120, 'Armor of Peace', 3, 'Your commitment to peace allows you to walk into the most dangerous situations unarmored. While you aren''t wearing armor or wielding a shield, your base AC is 16 + your Dexterity modifier.'),
(120, 'Warrior of Reconciliation', 3, 'You foreswear the weapons of war in favor of simple tools. While wielding a simple weapon that deals bludgeoning damage, you gain a special benefit if you reduce a creature to 0 hit points with that weapon and decide to spare the creature''s life. Instead of falling unconscious, the creature is charmed by you for 1 minute. During that time, the charmed creature is peaceful and docile, refusing to move or to take actions or reactions, unless you command it to. You can''t order the creature to attack, force someone to make a saving throw, or cause damage to itself or others. This charmed effect ends early if you are incapacitated or if you or your companions attack the creature, deal damage to it, or force it to make a saving throw. When the effect ends, the creature falls unconscious if it still has 0 hit points.'),
(120, 'Emissary of Peace', 3, 'You can use your Channel Divinity to augment your presence with divine power. As a bonus action, you grant yourself a +5 bonus to the next Charisma (Persuasion) check you make within the next minute.'),
(120, 'Rebuke the Violent', 3, 'You can use your Channel Divinity to rebuke those who use violence. As a reaction when an enemy within 10 feet of you deals damage with a melee attack against one creature other than you, you force that attacker to make a Wisdom saving throw. On a failed save, the attacker takes radiant damage equal to the damage it just dealt. On a successful save, it takes half as much damage.'),
(120, 'Aura of the Guardian', 7, 'You can shield your allies from harm at the cost of your own health. As a reaction when an ally within 10 feet of you takes damage, you instead magically take that damage. This feature doesn''t transfer any other effects that might accompany the damage.'),
(120, 'Protective Spirit', 15, 'A holy presence mends your wounds in combat. You regain hit points equal to 1d6 + half your paladin level if you end your turn in combat with fewer than half of your hit points remaining and you aren''t incapacitated.'),
(120, 'Emissary of Redemption', 20, 'You become an avatar of peace, which gives you two benefits: You have resistance to all damage dealt by other creatures (their attacks, spells, and other effects). Whenever a creature damages you, it takes damage equal to half the amount it dealt to you. If you attack a creature, deal damage to it, or force it to make a saving throw, neither benefit works against that creature until you finish a long rest.');

-- Oath of the Watchers (UA) (ID 121)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(121, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of the Watchers Spells Paladin Level Spells 3rd Alarm, Chromatic Orb 5th Augury, Moonbeam 9th Counterspell, Nondetection 13th Aura of Purity, Banishment 17th Hallow, Hold Monster'),
(121, 'Abjure the Extraplanar', 3, 'You can use your Channel Divinity to castigate unwordly beings. As an action, you present your holy symbol and each elemental, fey, fiend, or aberration within 30 feet of you that can hear you must make a Wisdom saving throw. On a failed save, the creature is turned for 1 minute or until it takes damage. A turned creature must spend its turns trying to move as far away from you as it can, and it can''t willingly move to a space within 30 feet of you. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If there''s nowhere to move, the creature can take the Dodge action.'),
(121, 'Watcher''s Will', 3, 'You can use your Channel Divinity to invest your presence with the warding power of your faith. As an action, you can choose a number of creatures you can see within 30 feet of you, up a number equal to your Charisma modifier (minimum of one creature). For 1 minute, all the chosen creatures have advantage on Intelligence, Wisdom, and Charisma saving throws.'),
(121, 'Aura of the Sentinel', 7, 'You emit an aura of alertness while you aren''t incapacitated. When you and any creature of your choice within 10 feet of you rolls initiative, you each gain a bonus to initiative equal to your Charisma modifier (minimum of +1). At 18th level, the range of your Aura of the Sentinel increases to 30 feet.'),
(121, 'Vigilant Rebuke', 15, 'You''ve learned how to magically chastise anyone who dares cast unwanted spells at you and your wards. Whenever you or a creature you can see within 30 feet of you succeeds on a saving throw against a spell, you can use your reaction to deal 2d8 + your Charisma modifier force damage to the spellcaster.'),
(121, 'Mortal Bulwark', 20, 'You manifest a spark of your diety''s power in defense of your sacred oath. As a bonus action, you gain the following benefits for 1 minute: You gain truesight in a 120-foot radius. You have advantage on attack rolls against elementals, fey, fiends, and aberrations. When you hit a creature with an attack and deal damage to it, you can also force it to make a Charisma saving throw. On a failed save, the creature is magically banished to its native plane of existence if it''s currently not there. On a successful save, the creature can''t be banished by this feature for 24 hours. Once you use this bonus action, you can''t use it again until you finish a long rest.');

-- Oath of Heroism (UA) (ID 122)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(122, 'Oath Spells', 3, 'You gain oath spells at the paladin levels listed. Oath of Heroism Spells Paladin Level Spells 3rd Expeditious Retreat, Guiding Bolt 5th Enhance Ability, Enthrall 9th Haste, Protection from Energy 13th Compulsion, Freedom of Movement 17th Commune, Conjure Volley'),
(122, 'Legendary Strike', 3, 'You can use your Channel Divinity as a bonus action to guide your attacks: for 1 minute, your weapon attacks score a critical hit on a roll of 19 or 20 on the d20.'),
(122, 'Peerless Athlete', 3, 'You can use your Channel Divinity to augment your athleticism with divine favor. As a bonus action, you gain advantage on all Strength (Athletics) and Dexterity (Acrobatics) checks for the next 10 minutes.'),
(122, 'Mighty Deed', 7, 'Your actions on the battlefield can supernaturally bolster your allies and demoralize your enemies. Whenever you score a critical hit or reduce a creature to 0 hit points, you can choose one or more creatures that you can see within 30 feet of you, up to a number equal to your Charisma modifier (minimum of one creature). All the chosen creatures are affected by one of the following effects of your choice. The creature gains temporary hit points equal to 1d6 + your Charisma modifier (minimum of 1 temporary hit point). The creature must succeed on a Wisdom saving throw against your spell save DC or be frightened of you until the start of your next turn. Once you use this feature you can''t use it again until the start of your next turn.'),
(122, 'Glorious Defense', 15, 'Your blessed glory on the battlefield can misdirect an attack. When a creature you can see hits you with an attack roll, you can use your reaction to gain a bonus to AC against that attack, potentially causing it to miss you. The bonus equals your Charisma modifier (minimum of +1). If the attack misses, you can make one weapon attack against the attacker as part of this reaction.'),
(122, 'Living Myth', 20, 'You can now empower yourself with the legends - whether true or exaggerated - told of your great deeds. As a bonus action, you gain the following benefits for 10 minutes. You are blessed with otherworldly comeliness, gaining advantage on all Charisma checks. Once on each of your turns when you make a weapon attack and miss, you can cause that attack to hit instead. If you fail a saving throw, you can use your reaction to succeed instead.');
