-- =============================================================================
-- ROGUE SUBCLASSES
-- =============================================================================

-- Subclasse: Arcane Trickster (ID: 137) -- antes 130
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(137, 'Spellcasting', 3, 'When you reach 3rd level, you augment your martial prowess with the ability to cast spells. Cantrips: You learn three cantrips: Mage Hand and two other cantrips of your choice from the wizard spell list. You learn another wizard cantrip of your choice at 10th level. Spell Slots: The Arcane Trickster Spellcasting table shows how many spell slots you have to cast your wizard spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell''s level or higher. You regain all expended spell slots when you finish a long rest. Spells Known of 1st Level and Higher: You know three 1st-level wizard spells of your choice, two of which you must choose from the enchantment and illusion spells on the wizard spell list. The Spells Known column of the Arcane Trickster Spellcasting table shows when you learn more wizard spells of 1st level or higher. Each of these spells must be an enchantment or illusion spell of your choice, and must be of a level for which you have spell slots. The spells you learn at 8th, 14th, and 20th level can come from any school of magic. Spellcasting Ability: Intelligence is your spellcasting ability for your wizard spells, since you learn your spells through dedicated study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability. Spell save DC = 8 + your proficiency bonus + your Intelligence modifier. Spell attack modifier = your proficiency bonus + your Intelligence modifier.'),
(137, 'Mage Hand Legerdemain', 3, 'Starting at 3rd level, when you cast Mage Hand, you can make the spectral hand invisible, and you can perform the following additional tasks with it: You can stow one object the hand is holding in a container worn or carried by another creature. You can retrieve an object in a container worn or carried by another creature. You can use thieves'' tools to pick locks and disarm traps at range. You can perform one of these tasks without being noticed by a creature if you succeed on a Dexterity (Sleight of Hand) check contested by the creature''s Wisdom (Perception) check. In addition, you can use the bonus action granted by your Cunning Action to control the hand.'),
(137, 'Magical Ambush', 9, 'Starting at 9th level, if you are hidden from a creature when you cast a spell on it, the creature has disadvantage on any saving throw it makes against the spell this turn.'),
(137, 'Versatile Trickster', 13, 'At 13th level, you gain the ability to distract targets with your Mage Hand. As a bonus action on your turn, you can designate a creature within 5 feet of the spectral hand created by the spell. Doing so gives you advantage on attack rolls against that creature until the end of the turn.'),
(137, 'Spell Thief', 17, 'At 17th level, you gain the ability to magically steal the knowledge of how to cast a spell from another spellcaster. Immediately after a creature casts a spell that targets you or includes you in its area of effect, you can use your reaction to force the creature to make a saving throw with its spellcasting ability modifier. The DC equals your spell save DC. On a failed save, you negate the spell''s effect against you, and you steal the knowledge of the spell if it is at least 1st level and of a level you can cast (it doesn''t need to be a wizard spell). For the next 8 hours, you know the spell and can cast it using your spell slots. The creature can''t cast that spell until the 8 hours have passed. Once you use this feature, you can''t use it again until you finish a long rest.')

-- Subclasse: Assassin (ID: 138) -- antes 131
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(138, 'Bonus Proficiencies', 3, 'When you choose this archetype at 3rd level, you gain proficiency with the disguise kit and the poisoner''s kit.'),
(138, 'Assassinate', 3, 'Starting at 3rd level, you are at your deadliest when you get the drop on your enemies. You have advantage on attack rolls against any creature that hasn''t taken a turn in the combat yet. In addition, any hit you score against a creature that is surprised is a critical hit.'),
(138, 'Infiltration Expertise', 9, 'Starting at 9th level, you can unfailingly create false identities for yourself. You must spend seven days and 25 gp to establish the history, profession, and affiliations for an identity. You can''t establish an identity that belongs to someone else. For example, you might acquire appropriate clothing, letters of introduction, and official-looking certification to establish yourself as a member of a trading house from a remote city so you can insinuate yourself into the company of other wealthy merchants. Thereafter, if you adopt the new identity as a disguise, other creatures believe you to be that person until given an obvious reason not to.'),
(138, 'Impostor', 13, 'At 13th level, you gain the ability to unerringly mimic another person''s speech, writing, and behavior. You must spend at least three hours studying these three components of the person''s behavior, listening to speech, examining handwriting, and observing mannerisms. Your ruse is indiscernible to the casual observer. If a wary creature suspects something is amiss, you have advantage on any Charisma (Deception) check you make to avoid detection.'),
(138, 'Death Strike', 17, 'Starting at 17th level, you become a master of instant death. When you attack and hit a creature that is surprised, it must make a Constitution saving throw (DC 8 + your Dexterity modifier + your proficiency bonus). On a failed save, double the damage of your attack against the creature.')

-- Subclasse: Inquisitive (ID: 139) -- antes 132
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(139, 'Ear for Deceit', 3, 'When you choose this archetype at 3rd level, you develop a keen ear for picking out lies. Whenever you make a Wisdom (Insight) check to determine whether a creature is lying, treat a roll of 7 or lower on the d20 as an 8.'),
(139, 'Eye for Detail', 3, 'Starting at 3rd level, you can use a bonus action to make a Wisdom (Perception) check to spot a hidden creature or object or to make an Intelligence (Investigation) check to uncover or decipher clues.'),
(139, 'Insightful Fighting', 3, 'At 3rd level, you gain the ability to decipher an opponent''s tactics and develop a counter to them. As a bonus action, you make a Wisdom (Insight) check against a creature you can see that isn''t incapacitated, contested by the target''s Charisma (Deception) check. If you succeed, you can use your Sneak Attack against that target even if you don''t have advantage on the attack roll, but not if you have disadvantage on it. This benefit lasts for 1 minute or until you successfully use this feature against a different target.'),
(139, 'Steady Eye', 9, 'At 9th level, you gain advantage on any Wisdom (Perception) or Intelligence (Investigation) check if you move no more than half your speed on the same turn.'),
(139, 'Unerring Eye', 13, 'At 13th level, your senses are almost impossible to foil. As an action, you sense the presence of illusions, shapechangers not in their original form, and other magic designed to deceive the senses within 30 feet of you, provided you aren''t blinded or deafened. You sense that an effect is attempting to trick you, but you gain no insight into what is hidden or into its true nature. You can use this feature a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses of it when you finish a long rest.'),
(139, 'Eye for Weakness', 17, 'At 17th level, you learn to exploit a creature''s weaknesses by carefully studying its tactics and movement. While your Insightful Fighting feature applies to a creature, your Sneak Attack damage against that creature increases by 3d6.')

-- Subclasse: Mastermind (ID: 140) -- antes 133
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(140, 'Master of Intrigue', 3, 'When you choose this archetype at 3rd level, you gain proficiency with the disguise kit, the forgery kit, and one gaming set of your choice. You also learn two languages of your choice. Additionally, you can unerringly mimic the speech patterns and accent of a creature that you hear speak for at least 1 minute, enabling you to pass yourself off as a native speaker of a particular land, provided that you know the language.'),
(140, 'Master of Tactics', 3, 'Starting at 3rd level, you can use the Help action as a bonus action. Additionally, when you use the Help action to aid an ally in attacking a creature, the target of that attack can be within 30 feet of you, rather than 5 feet of you, if the target can see or hear you.'),
(140, 'Insightful Manipulator', 9, 'Starting at 9th level, if you spend at least 1 minute observing or interacting with another creature outside combat, you can learn certain information about its capabilities compared to your own. The DM tells you if the creature is your equal, superior, or inferior in regard to two of the following characteristics of your choice: Intelligence score, Wisdom score, Charisma score, Class levels (if any). At the DM''s option, you might also realize you know a piece of the creature''s history or one of its personality traits, if it has any.'),
(140, 'Misdirection', 13, 'Beginning at 13th level, you can sometimes cause another creature to suffer an attack meant for you. When you are targeted by an attack while a creature within 5 feet of you is granting you cover against that attack, you can use your reaction to have the attack target that creature instead of you.'),
(140, 'Soul of Deceit', 17, 'Starting at 17th level, your thoughts can''t be read by telepathy or other means, unless you allow it. You can present false thoughts by making a Charisma (Deception) check contested by the mind reader''s Wisdom (Insight) check. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates you are being truthful if you so choose, and you can''t be compelled to tell the truth by magic.')

-- Subclasse: Phantom (ID: 141) -- antes 134
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(141, 'Whispers of the Dead', 3, 'When you choose this archetype at 3rd level, echoes of those who have died cling to you. Whenever you finish a short or long rest, you can gain one skill or tool proficiency of your choice, as a ghostly presence shares its knowledge with you. You lose this proficiency when you use this feature to choose a different proficiency that you lack.'),
(141, 'Wails from the Grave', 3, 'At 3rd level, as you nudge someone closer to the grave, you can channel the power of death to harm someone else as well. Immediately after you deal your Sneak Attack damage to a creature on your turn, you can target a second creature that you can see within 30 feet of the first creature. Roll half the number of Sneak Attack dice for your level (round up), and the second creature takes necrotic damage equal to the roll''s total, as wails of the dead sound around them for a moment. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(141, 'Tokens of the Departed', 9, 'At 9th level, when a life ends in your presence, you''re able to snatch a token from the departing soul, a sliver of its life essence that takes physical form: as a reaction when a creature you can see dies within 30 feet of you, you can open your free hand and cause a Tiny trinket to appear there, a soul trinket. The DM determines the trinket''s form or has you roll on the Trinkets table in the Player''s Handbook to generate it. You can have a maximum number of soul trinkets equal to your proficiency bonus, and you can''t create one while at your maximum. You can use soul trinkets in the following ways: While a soul trinket is on your person, you have advantage on death saving throws and Constitution saving throws, for your vitality is enhanced by the life essence within the object. When you deal Sneak Attack damage on your turn, you can destroy one of your soul trinkets that''s on your person and then immediately use Wails from the Grave, without expending a use of that feature. As an action, you can destroy one of your soul trinkets, no matter where it''s located. When you do so, you can ask the spirit associated with the trinket one question. The spirit appears to you and answers in a language it knew in life. It''s under no obligation to be truthful, and it answers as concisely as possible, eager to be free. The spirit knows only what it knew in life, as determined by the DM.'),
(141, 'Ghost Walk', 13, 'At 13th level, you can phase partially into the realm of the dead, becoming like a ghost. As a bonus action, you assume a spectral form. While in this form, you have a flying speed of 10 feet, you can hover, and attack rolls have disadvantage against you. You can also move through creatures and objects as if they were difficult terrain, but you take 1d10 force damage if you end your turn inside a creature or an object. You stay in this form for 10 minutes or until you end it as a bonus action. To use this feature again, you must finish a long rest or destroy one of your soul trinkets as part of the bonus action you use to activate Ghost Walk.'),
(141, 'Death''s Friend', 17, 'At 17th level, your association with death has become so close that you gain the following benefits: When you use your Wails from the Grave, you can now deal the necrotic damage to both the first and the second creature. At the end of a long rest, a soul trinket appears in your hand if you don''t have any soul trinkets, as the spirits of the dead are drawn to you.')

-- Subclasse: Scout (ID: 142) -- antes 135
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(142, 'Skirmisher', 3, 'Starting at 3rd level, you are difficult to pin down during a fight. You can move up to half your speed as a reaction when an enemy ends its turn within 5 feet of you. This movement doesn''t provoke opportunity attacks.'),
(142, 'Survivalist', 3, 'When you choose this archetype at 3rd level, you gain proficiency in the Nature and Survival skills if you don''t already have it. Your proficiency bonus is doubled for any ability check you make that uses either of those proficiencies.'),
(142, 'Superior Mobility', 9, 'At 9th level, your walking speed increases by 10 feet. If you have a climbing or swimming speed, this increase applies to that speed as well.'),
(142, 'Ambush Master', 13, 'Starting at 13th level, you excel at leading ambushes and acting first in a fight. You have advantage on initiative rolls. In addition, the first creature you hit during the first round of a combat becomes easier for you and others to strike; attack rolls against that target have advantage until the start of your next turn.'),
(142, 'Sudden Strike', 17, 'Starting at 17th level, you can strike with deadly speed. If you take the Attack action on your turn, you can make one additional attack as a bonus action. This attack can benefit from your Sneak Attack even if you have already used it this turn, but you can''t use your Sneak Attack against the same target more than once in a turn.')

-- Subclasse: Soulknife (UA) (ID: 148)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(148, 'Psychic Blade', 3, 'Starting at 3rd level, as a bonus action, you can create a magical blade of shimmering psychic power from one or both of your hands. While one of your hands is manifesting a blade, you can''t hold anything in that hand. You can dismiss one or both blades at any time (no action required), and they disappear if you''re incapacitated. The blade is a simple melee weapon with the finesse, light, and thrown properties. It has a normal range of 30 feet and a long range of 60 feet, and it deals 1d6 psychic damage on a hit. If you throw the blade as part of an attack, it vanishes immediately after it hits or misses its target. The blade otherwise disappears the instant it leaves your hand.'),
(148, 'Psionic Enhancement', 3, 'Starting at 3rd level, you can focus your psionic power to give yourself an extraordinary ability. When you finish a long rest, you gain one of the following benefits of your choice, which lasts until you finish a long rest: You can communicate telepathically with any creature you can see within 30 feet of you. If a creature can speak at least one language, it can respond to you telepathically. Increase your walking speed by 5 feet. Your hit point maximum and your current hit points increase by an amount equal to your Intelligence modifier plus your Rogue level.'),
(148, 'Terrifying Blade', 9, 'Starting at 9th level, your Psychic Blades can now stoke terror within a target: When you damage a creature with your Psychic Blade, you can force the target to make a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Intelligence modifier). On a failed save, the creature is frightened of you until the start of your next turn. On a successful save, the creature isn''t frightened and is immune to your Terrifying Blade for 24 hours.'),
(148, 'Psychic Veil', 13, 'Starting at 13th level, you can weave a veil of psionic static to mask your physical presence. As an action, you can magically become invisible, along with anything you are wearing or carrying, for 10 minutes. This invisibility ends if you make an attack or if you force a creature to make a saving throw. You can use this feature a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(148, 'Rend Mind', 17, 'Starting at 17th level, you can sweep your Psychic Blade directly through a creature''s mind. As an action while you have at least one Psychic Blade manifested, you can force a creature you can see within 30 feet of you to make an Intelligence saving throw (DC equal to 10 + your proficiency bonus + your Intelligence modifier). If you are hidden from the target, it has disadvantage on the save. On a failed save, the target takes 12d6 psychic damage, and it is stunned until the start of your next turn. On a successful save, the target takes half as much damage and isn''t stunned. One of your Psychic Blades vanishes after using this feature. You can use this feature a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.');

-- Subclasse: Soulknife Revisited (UA) (ID: 149)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(149, 'Psionic Talent', 3, 'Starting at 3rd level, you harbor a wellspring of psionic power within yourself, an energy that ebbs and flows as you channel it in various ways. This power is represented by your Psionic Talent die, the starting size of which is a d6. Changing the Die’s Size. If you roll the highest number on your Psionic Talent die, it decreases by one die size after the roll. This represents you burning through your psionic energy. For example, if the die is a d6 and you roll a 6, it becomes a d4. If it’s a d4 and you roll a 4, it becomes unusable until you finish a long rest. Conversely, if you roll a 1 on your Psionic Talent die, it increases by one die size after the roll, up to its starting size. This represents you conserving psionic energy for later use. For example, if you roll a 1 on a d4, the die then becomes a d6. Whenever you finish a long rest, your Psionic Talent die resets to its starting size. When you reach certain levels in this class, the starting size of your Psionic Talent die increases: at 5th level (d8), 11th level (d10), and 17th level (d12). You can use your Psionic Talent die in the following ways: Psi-Bolstered Knack. When your non-psionic training fails you, you can tap into your psionic power to help: if you fail an ability check using a skill or tool with which you have proficiency, you can roll your Psionic Talent die and add the number rolled to the check, potentially turning failure into success. Psychic Whispers. You can use your psychic abilities to establish telepathic communication between yourself and others—perfect for quiet infiltration. As an action, you give yourself and at least one other creature the ability to speak telepathically with each other. When you do so, roll your Psionic Talent die, and choose creatures you can see, up to a number of creatures equal to the number rolled. For 1 hour, the chosen creatures can speak telepathically with you, and you can speak telepathically with them. To send or receive a message (no action required), you and the other creature must be within 1 mile of each other. A creature can’t use this telepathy if it can’t speak any languages, and a creature can end the telepathic connection at any time (no action required). You and the creature don’t need to speak a common language to understand each other.'),
(149, 'Psi Replenishment.', 3, 'Starting at 3rd level, as a bonus action, you can calm your mind for a moment and restore your Psionic Talent die to its starting size. You then can’t use Psi Replenishment again until you finish a long rest.'),
(149, 'Psychic Blades', 3, 'At 3rd level when you adopt this archetype, you can manifest your psionic power as shimmering blades of psychic energy. When you are about to make a melee or ranged weapon attack against a creature, you can manifest a psychic blade from your free hand and make the attack with that blade. This magic blade is a simple melee weapon with the finesse and thrown properties. It has a normal range of 60 feet and no long range, and on a hit, it deals psychic damage equal to 1d6 plus the ability modifier you used for the attack roll. The blade vanishes immediately after it hits or misses its target, and it leaves no mark on its target if it deals damage. After you attack with the blade, you can make a melee or ranged weapon attack with a second psychic blade as a bonus action on the same turn, provided your other hand is free to create it. The damage die of this bonus attack is 1d4, instead of 1d6.'),
(149, 'Soul Blades', 9, 'At 9th-level, your Psychic Blades are now an expression of your psi-suffused soul, giving you finer control over them in the following ways: Homing Strikes. If you make an attack roll with your Psychic Blades and miss the target, you can roll your Psionic Talent die and add the number rolled to the attack roll. If this causes the attack to hit, your Psionic Talent die decreases by one die size, regardless of the number rolled. Psychic Teleportation. If your Psionic Talent die is available, you can hurl your Psychic Blades to magically transport yourself to another location. As a bonus action, you manifest one of your Psychic Blades and throw it at an unoccupied space you can see, up to a number of feet away equal to 5 times the highest number on your Psionic Talent die.You then teleport to that space, the blade vanishes, and your Psionic Talent die decreases by one die size.'),
(149, 'Psionic Veil', 13, 'When you reach 13th-level, you can weave a veil of psychic static to mask yourself. As an action, you can magically become invisible, along with anything you are wearing or carrying, for 10 minutes or until you dismiss this effect (no action required). This invisibility ends if you deal damage to a creature or if you force a creature to make a saving throw. Once you use this feature, you can’t do so again until you finish a long rest, unless you decrease your Psionic Talent die by one die size to use this feature again.'),
(149, 'Rend Mind', 17, 'By 17th-level, you can sweep your Psychic Blades directly through a creature’s mind. When you use your Psychic Blades to deal Sneak Attack damage to a creature, you can force that target to make a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Dexterity modifier). Unless the save succeeds, the target is stunned until the end of your next turn. Once you use this feature, you can’t do so again until you finish a long rest, unless you decrease your Psionic Talent die by one die size to use this feature again.');

-- Subclasse: Swashbuckler (ID: 144) -- antes 137
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(144, 'Fancy Footwork', 3, 'When you choose this archetype at 3rd level, you learn how to land a strike and then slip away without reprisal. During your turn, if you make a melee attack against a creature, that creature can''t make opportunity attacks against you for the rest of your turn.'),
(144, 'Rakish Audacity', 3, 'Starting at 3rd level, your confidence propels you into battle. You can give yourself a bonus to your initiative rolls equal to your Charisma modifier. You also gain an additional way to use your Sneak Attack; you don''t need advantage on the attack roll to use your Sneak Attack against a creature if you are within 5 feet of it, no other creatures are within 5 feet of you, and you don''t have disadvantage on the attack roll. All the other rules for Sneak Attack still apply to you.'),
(144, 'Panache', 9, 'At 9th level, your charm becomes extraordinarily beguiling. As an action, you can make a Charisma (Persuasion) check contested by a creature''s Wisdom (Insight) check. The creature must be able to hear you, and the two of you must share a language. If you succeed on the check and the creature is hostile to you, it has disadvantage on attack rolls against targets other than you and can''t make opportunity attacks against targets other than you. This effect lasts for 1 minute, until one of your companions attacks the target or affects it with a spell, or until you and the target are more than 60 feet apart. If you succeed on the check and the creature isn''t hostile to you, it is charmed by you for 1 minute. While charmed, it regards you as a friendly acquaintance. This effect ends immediately if you or your companions do anything harmful to it.'),
(144, 'Elegant Maneuver', 13, 'Starting at 13th level, you can use a bonus action on your turn to gain advantage on the next Dexterity (Acrobatics) or Strength (Athletics) check you make during the same turn.'),
(144, 'Master Duelist', 17, 'Beginning at 17th level, your mastery of the blade lets you turn failure into success in combat. If you miss with an attack roll, you can roll it again with advantage. Once you do so, you can''t use this feature again until you finish a short or long rest.')

-- Subclasse: Thief (ID: 145) -- antes 138
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(145, 'Fast Hands', 3, 'Starting at 3rd level, you can use the bonus action granted by your Cunning Action to make a Dexterity (Sleight of Hand) check, use your thieves'' tools to disarm a trap or open a lock, or take the Use an Object action.'),
(145, 'Second-Story Work', 3, 'When you choose this archetype at 3rd level, you gain the ability to climb faster than normal; climbing no longer costs you extra movement. In addition, when you make a running jump, the distance you cover increases by a number of feet equal to your Dexterity modifier.'),
(145, 'Supreme Sneak', 9, 'Starting at 9th level, you have advantage on a Dexterity (Stealth) check if you move no more than half your speed on the same turn.'),
(145, 'Use Magic Device', 13, 'By 13th level, you have learned enough about the workings of magic that you can improvise the use of items even when they are not intended for you. You ignore all class, race, and level requirements on the use of magic items.'),
(145, 'Thief''s Reflexes', 17, 'When you reach 17th level, you have become adept at laying ambushes and quickly escaping danger. You can take two turns during the first round of any combat. You take your first turn at your normal initiative and your second turn at your initiative minus 10. You can''t use this feature when you are surprised.')

-- Subclasse: Phantom (UA) (ID: 146)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(146, 'Whispers of the Dead', 3, 'At 3rd level, echoes of those who have died begin to cling to you. Whenever you finish a short or long rest, you can gain one skill or tool proficiency of your choice, as a ghostly presence shares its knowledge with you. This proficiency lasts until you use this feature again.'),
(146, 'Wails from the Grave', 3, 'At 3rd level, as you nudge someone closer to the grave, you can cause deathly wails to be heard near them. Immediately after you deal your Sneak Attack damage to a creature on your turn, you can target a second creature that you can see within 30 feet of the first creature. Roll half the number of Sneak Attack dice for your level (round up), and the second creature takes psychic damage equal to the roll’s total, as wails of the dead sound around them for a moment. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(146, 'Tokens of the Departed', 9, 'At 9th level, when a life ends in your presence, you’re able to snatch a token from the departing soul, a sliver of its life essence that takes physical form: as a reaction when a creature you can see dies within 30 feet of you, you open your free hand and a Tiny trinket appears there, a soul trinket. The DM chooses the trinket’s form or has you roll on the Trinkets table in the Player’s Handbook to determine it. While the soul trinket is on your person, you have advantage on death saving throws and Constitution saving throws, as your vitality is enhanced by the life essence within the object. You can have a maximum number of soul trinkets equal to your proficiency bonus, and you can’t create one while at your maximum. As an action, you can destroy one of your soul trinkets, no matter where it’s located. When you do so, you can ask the spirit associated with the trinket one question. The spirit appears to you and answers in a language it knew in life. It’s under no obligation to be truthful, and it answers as concisely as possible, eager to be free.'),
(146, 'Ghost Walk', 13, 'At 13th level, you can now phase partially into the realm of the dead, becoming like a ghost. As a bonus action, you assume a spectral form. While in this form, you have a flying speed of 10 feet, you can hover, and attack rolls have disadvantage against you. You can also move through creatures and objects as if they were difficult terrain, but you take 1d10 force damage if you end your turn inside a creature or an object. You stay in this form for 10 minutes or until you end it as a bonus action. To use this feature again, you must finish a long rest or destroy one of your soul trinkets as part of the bonus action you use to activate Ghost Walk.'),
(146, 'Death Knell', 17, 'At 17th level, when you use your Wails from the Grave feature, you can now deal the psychic damage to both the first and the second creature.');

-- Subclasse: Revived (UA) (ID: 147)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(147, 'Tokens of Past Lives', 3, 'Starting at 3rd level, you remember talents you had in your previous life. When you finish a long rest, you gain one skill or tool proficiency of your choice. You can replace this proficiency with another when you finish a long rest.'),
(147, 'Revived Nature', 3, 'When you choose this archetype at 3rd level, your newfound connection to death gives you the following benefits: You have advantage on saving throws against disease and being poisoned, and you have resistance to poison damage. You don''t need to eat, drink, or breathe. You don''t need to sleep. When you take a long rest, you must spend at least four hours in an inactive, motionless state, rather than sleeping. In this state, you remain semiconscious, and you can hear as normal.'),
(147, 'Bolts from the Grave', 3, 'Starting at 3rd level, you have learned to unleash bolts of necrotic energy from within your revived body. Immediately after you use your Cunning Action, you can make a ranged spell attack against a creature within 30 feet of you, provided you haven''t used your Sneak Attack this turn. You are proficient with it, and you add your Dexterity modifier to its attack and damage rolls. A creature hit by this attack takes necrotic damage equal to your Sneak Attack. This uses your Sneak Attack for the turn.'),
(147, 'Connect with the Dead', 9, 'At 9th level, you can create a link with a spirit through their corpse. When you do so, you cast the Speak with Dead spell, without using a spell slot or material components. Intelligence is your spellcasting ability for this spell. Speaking with the dead in this way temporarily gives you a capability from a past life-you''re unsure whether its from your past life or the spirit''s. When the spell ends, you gain one random benefit from the Revived Capabilities table. These benefits last until you finish a short or long rest. Revived Capabilities: 1 - You learn how to speak, read, and write one language of your choice. 2 - You gain one skill or tool proficiency of your choice. 3 - You gain proficiency with one saving throw of your choice. After you cast the spell with this feature, you can''t do so again until you finish a short or long rest.'),
(147, 'Audience with Death', 13, 'By 13th level, when at death''s door, you can converse with the powers of death. You have advantage on death saving throws, and whenever you make a death saving throw, your spirit can ask an entity of death a question that can be answered with "yes," "no," or "unknown." The entity answers truthfully, using the knowledge of all those who have died. In addition, whenever you have 0 hit points and are healed or stabilized, you can change any of your personal characteristics: personality trait, ideal, bond, or flaw.'),
(147, 'Ethereal Jaunt', 17, 'When you reach 17th level, like a ghost, you have the ability to slip in and out of the Ethereal Plane. You can now use your Cunning Action to teleport to an unoccupied space within 30 feet of you. You don''t need to see that space to teleport to it, but your teleportation fails, wasting your bonus action, if you attempt to teleport through magical force that is Medium or larger, such as a wall of force. If you appear in a space occupied by another creature or filled by an object, you are immediately shunted to the nearest unoccupied space that you can occupy and take force damage equal to twice the number of feet you are shunted.');

-- Subclasse: Soulknife (UA) (ID: 148)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(148, 'Psychic Blade', 3, 'Starting at 3rd level, as a bonus action, you can create a magical blade of shimmering psychic power from one or both of your hands. While one of your hands is manifesting a blade, you can''t hold anything in that hand. You can dismiss one or both blades at any time (no action required), and they disappear if you''re incapacitated. The blade is a simple melee weapon with the finesse, light, and thrown properties. It has a normal range of 30 feet and a long range of 60 feet, and it deals 1d6 psychic damage on a hit. If you throw the blade as part of an attack, it vanishes immediately after it hits or misses its target. The blade otherwise disappears the instant it leaves your hand.'),
(148, 'Psionic Enhancement', 3, 'Starting at 3rd level, you can focus your psionic power to give yourself an extraordinary ability. When you finish a long rest, you gain one of the following benefits of your choice, which lasts until you finish a long rest: You can communicate telepathically with any creature you can see within 30 feet of you. If a creature can speak at least one language, it can respond to you telepathically. Increase your walking speed by 5 feet. Your hit point maximum and your current hit points increase by an amount equal to your Intelligence modifier plus your Rogue level.'),
(148, 'Terrifying Blade', 9, 'Starting at 9th level, your Psychic Blades can now stoke terror within a target: When you damage a creature with your Psychic Blade, you can force the target to make a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Intelligence modifier). On a failed save, the creature is frightened of you until the start of your next turn. On a successful save, the creature isn''t frightened and is immune to your Terrifying Blade for 24 hours.'),
(148, 'Psychic Veil', 13, 'Starting at 13th level, you can weave a veil of psionic static to mask your physical presence. As an action, you can magically become invisible, along with anything you are wearing or carrying, for 10 minutes. This invisibility ends if you make an attack or if you force a creature to make a saving throw. You can use this feature a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(148, 'Rend Mind', 17, 'Starting at 17th level, you can sweep your Psychic Blade directly through a creature''s mind. As an action while you have at least one Psychic Blade manifested, you can force a creature you can see within 30 feet of you to make an Intelligence saving throw (DC equal to 10 + your proficiency bonus + your Intelligence modifier). If you are hidden from the target, it has disadvantage on the save. On a failed save, the target takes 12d6 psychic damage, and it is stunned until the start of your next turn. On a successful save, the target takes half as much damage and isn''t stunned. One of your Psychic Blades vanishes after using this feature. You can use this feature a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.');

-- Subclasse: Soulknife Revisited (UA) (ID: 149)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(149, 'Psionic Talent', 3, 'Starting at 3rd level, you harbor a wellspring of psionic power within yourself, an energy that ebbs and flows as you channel it in various ways. This power is represented by your Psionic Talent die, the starting size of which is a d6. Changing the Die’s Size. If you roll the highest number on your Psionic Talent die, it decreases by one die size after the roll. This represents you burning through your psionic energy. For example, if the die is a d6 and you roll a 6, it becomes a d4. If it’s a d4 and you roll a 4, it becomes unusable until you finish a long rest. Conversely, if you roll a 1 on your Psionic Talent die, it increases by one die size after the roll, up to its starting size. This represents you conserving psionic energy for later use. For example, if you roll a 1 on a d4, the die then becomes a d6. Whenever you finish a long rest, your Psionic Talent die resets to its starting size. When you reach certain levels in this class, the starting size of your Psionic Talent die increases: at 5th level (d8), 11th level (d10), and 17th level (d12). You can use your Psionic Talent die in the following ways: Psi-Bolstered Knack. When your non-psionic training fails you, you can tap into your psionic power to help: if you fail an ability check using a skill or tool with which you have proficiency, you can roll your Psionic Talent die and add the number rolled to the check, potentially turning failure into success. Psychic Whispers. You can use your psychic abilities to establish telepathic communication between yourself and others—perfect for quiet infiltration. As an action, you give yourself and at least one other creature the ability to speak telepathically with each other. When you do so, roll your Psionic Talent die, and choose creatures you can see, up to a number of creatures equal to the number rolled. For 1 hour, the chosen creatures can speak telepathically with you, and you can speak telepathically with them. To send or receive a message (no action required), you and the other creature must be within 1 mile of each other. A creature can’t use this telepathy if it can’t speak any languages, and a creature can end the telepathic connection at any time (no action required). You and the creature don’t need to speak a common language to understand each other.'),
(149, 'Psi Replenishment.', 3, 'Starting at 3rd level, as a bonus action, you can calm your mind for a moment and restore your Psionic Talent die to its starting size. You then can’t use Psi Replenishment again until you finish a long rest.'),
(149, 'Psychic Blades', 3, 'At 3rd level when you adopt this archetype, you can manifest your psionic power as shimmering blades of psychic energy. When you are about to make a melee or ranged weapon attack against a creature, you can manifest a psychic blade from your free hand and make the attack with that blade. This magic blade is a simple melee weapon with the finesse and thrown properties. It has a normal range of 60 feet and no long range, and on a hit, it deals psychic damage equal to 1d6 plus the ability modifier you used for the attack roll. The blade vanishes immediately after it hits or misses its target, and it leaves no mark on its target if it deals damage. After you attack with the blade, you can make a melee or ranged weapon attack with a second psychic blade as a bonus action on the same turn, provided your other hand is free to create it. The damage die of this bonus attack is 1d4, instead of 1d6.'),
(149, 'Soul Blades', 9, 'At 9th-level, your Psychic Blades are now an expression of your psi-suffused soul, giving you finer control over them in the following ways: Homing Strikes. If you make an attack roll with your Psychic Blades and miss the target, you can roll your Psionic Talent die and add the number rolled to the attack roll. If this causes the attack to hit, your Psionic Talent die decreases by one die size, regardless of the number rolled. Psychic Teleportation. If your Psionic Talent die is available, you can hurl your Psychic Blades to magically transport yourself to another location. As a bonus action, you manifest one of your Psychic Blades and throw it at an unoccupied space you can see, up to a number of feet away equal to 5 times the highest number on your Psionic Talent die.You then teleport to that space, the blade vanishes, and your Psionic Talent die decreases by one die size.'),
(149, 'Psionic Veil', 13, 'When you reach 13th-level, you can weave a veil of psychic static to mask yourself. As an action, you can magically become invisible, along with anything you are wearing or carrying, for 10 minutes or until you dismiss this effect (no action required). This invisibility ends if you deal damage to a creature or if you force a creature to make a saving throw. Once you use this feature, you can’t do so again until you finish a long rest, unless you decrease your Psionic Talent die by one die size to use this feature again.'),
(149, 'Rend Mind', 17, 'By 17th-level, you can sweep your Psychic Blades directly through a creature’s mind. When you use your Psychic Blades to deal Sneak Attack damage to a creature, you can force that target to make a Wisdom saving throw (DC equal to 8 + your proficiency bonus + your Dexterity modifier). Unless the save succeeds, the target is stunned until the end of your next turn. Once you use this feature, you can’t do so again until you finish a long rest, unless you decrease your Psionic Talent die by one die size to use this feature again.');
