-- =============================================================================
-- MONK SUBCLASSES 
-- =============================================================================

-- Subclasse: Way of the Astral Self (ID: 95)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(95, 'Arms of the Astral Self', 3, 'At 3rd level, your mastery of your ki allows you to summon a portion of your astral self. As a bonus action, you can spend 1 ki point to summon the arms of your astral self. When you do so, each creature of your choice that you can see within 10 feet of you must succeed on a Dexterity saving throw or take force damage equal to two rolls of your Martial Arts die. For 10 minutes, these spectral arms hover near your shoulders or surround your arms (your choice). You determine the arms'' appearance, and they vanish early if you are incapacitated or die. While the spectral arms are present, you gain the following benefits: You can use your Wisdom modifier in place of your Strength modifier when making Strength checks and Strength saving throws. You can use the spectral arms to make unarmed strikes. When you make an unarmed strike with the arms on your turn, your reach for it is 5 feet greater than normal. The unarmed strikes you make with the arms can use your Wisdom modifier in place of your Strength or Dexterity modifier for the attack and damage rolls, and their damage type is force.'),
(95, 'Visage of the Astral Self', 6, 'When you reach 6th level, you can summon the visage of your astral self. As a bonus action, or as part of the bonus action you take to activate Arms of the Astral Self, you can spend 1 ki point to summon this visage for 10 minutes. It vanishes early if you are incapacitated or die. The spectral visage covers your face like a helmet or mask. You determine its appearance. While the spectral visage is present, you gain the following benefits. Astral Sight: You can see normally in darkness, both magical and nonmagical, to a distance of 120 feet. Wisdom of the Spirit: You have advantage on Wisdom (Insight) and Charisma (Intimidation) checks. Word of the Spirit: When you speak, you can direct your words to a creature of your choice that you can see within 60 feet of you, making it so only that creature can hear you. Alternatively, you can amplify your voice so that all creatures within 600 feet can hear you.'),
(95, 'Body of the Astral Self', 11, 'Starting at 11th level, when you have both your astral arms and visage summoned, you can cause the body of your astral self to appear (no action required). This spectral body covers your physical form like a suit of armor, connecting with the arms and visage. You determine its appearance. While the spectral body is present, you gain the following benefits. Deflect Energy: When you take acid, cold, fire, force, lightning, or thunder damage, you can use your reaction to deflect it. When you do so, the damage you take is reduced by 1d10 + your Wisdom modifier (minimum reduction of 1). Empowered Arms: Once on each of your turns when you hit a target with the Arms of the Astral Self, you can deal extra damage to the target equal to your Martial Arts die.'),
(95, 'Awakened Astral Self', 17, 'Starting at 17th level, your connection to your astral self is complete, allowing you to unleash its full potential. As a bonus action, you can spend 5 ki points to summon the arms, visage, and body of your astral self and awaken it for 10 minutes. This awakening ends early if you are incapacitated or die. While your astral self is awakened, you gain the following benefits. Armor of the Spirit: You gain a +2 bonus to Armor Class. Astral Barrage: Whenever you use the Extra Attack feature to attack twice, you can instead attack three times if all the attacks are made with your astral arms.');

-- Subclasse: Way of the Ascendant Dragon (ID: 96)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(96, 'Draconic Disciple', 3, 'At 3rd level, you can channel draconic power to magnify your presence and imbue your unarmed strikes with the essence of a dragon''s breath. You gain the following benefits: Draconic Presence: If you fail a Charisma (Intimidation) or Charisma (Persuasion) check, you can use your reaction to reroll the check, as you tap into the mighty presence of dragons. Once this feature turns a failure into a success, you can''t use it again until you finish a long rest. Draconic Strike: When you damage a target with an unarmed strike, you can change the damage type to acid, cold, fire, lightning, or poison. Tongue of Dragons: You learn to speak, read, and write Draconic or one other language of your choice.'),
(96, 'Breath of the Dragon', 3, 'At 3rd level you can channel destructive waves of energy, like those created by the dragons you emulate. When you take the Attack action on your turn, you can replace one of the attacks with an exhalation of draconic energy in either a 20-foot cone or a 30-foot line that is 5 feet wide (your choice). Choose a damage type: acid, cold, fire, lightning, or poison. Each creature in the area must make a Dexterity saving throw against your ki save DC, taking damage of the chosen type equal to two rolls of your Martial Arts die on a failed save, or half as much damage on a successful one. At 11th level, the damage of this feature increases to three rolls of your Martial Arts die. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest. While you have no uses available, you can spend 2 ki points to use this feature again.'),
(96, 'Wings Unfurled', 6, 'At 6th level when you use your Step of the Wind, you can unfurl spectral draconic wings from your back that vanish at the end of your turn. While the wings exist, you have a flying speed equal to your walking speed. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(96, 'Aspect of the Wyrm', 11, 'At 11th level the power of your draconic spirit now radiates from you, warding your allies or inspiring fear in your enemies. As a bonus action, you can create an aura of draconic power that radiates 10 feet from you for 1 minute. For the duration, you gain one of the following effects of your choice: Frightful Presence or Resistance to a chosen damage type. Once you create this aura, you can''t create it again until you finish a long rest, unless you expend 3 ki points to create it again.'),
(96, 'Ascendant Aspect', 17, 'At 17th level, your draconic spirit reaches its peak. You gain the following benefits: Augment Breath: When you use your Breath of the Dragon, you can spend 1 ki point to augment its shape and power. The exhalation of draconic energy becomes either a 60-foot cone or a 90-foot line that is 5 feet wide (your choice), and each creature in that area takes damage equal to four rolls of your Martial Arts die on a failed save, or half as much damage on a successful one. Blindsight: You gain blindsight out to 10 feet.');

-- Subclasse: Way of the Drunken Master (ID: 97)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(97, 'Bonus Proficiencies', 3, 'When you choose this tradition at 3rd level, you gain proficiency in the Performance skill if you don''t already have it. Your martial arts technique mixes combat training with the precision of a dancer and the antics of a jester. You also gain proficiency with brewer''s supplies if you don''t already have it.'),
(97, 'Drunken Technique', 3, 'At 3rd level, you learn how to twist and turn quickly as part of your Flurry of Blows. Whenever you use Flurry of Blows, you gain the benefit of the Disengage action, and your walking speed increases by 10 feet until the end of the current turn.'),
(97, 'Tipsy Sway', 6, 'Starting at 6th level, you can move in sudden, swaying ways. You gain the following benefits. Leap to Your Feet: When you''re prone, you can stand up by spending 5 feet of movement, rather than half your speed. Redirect Attack: When a creature misses you with a melee attack roll, you can spend 1 ki point as a reaction to cause that attack to hit one creature of your choice, other than the attacker, that you can see within 5 feet of you.'),
(97, 'Drunkard''s Luck', 11, 'Starting at 11th level, you always seem to get a lucky bounce at the right moment. When you make an ability check, an attack roll, or a saving throw and have disadvantage, you can spend 2 ki points to cancel the disadvantage for that roll.'),
(97, 'Intoxicated Frenzy', 17, 'At 17th level, you gain the ability to make an overwhelming number of attacks against a group of enemies. When you use your Flurry of Blows, you can make up to three additional attacks with it (up to a total of five Flurry of Blows attacks), provided that each Flurry of Blows attack targets a different creature this turn.');

-- Subclasse: Way of the Four Elements (ID: 98)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(98, 'Disciple of the Elements', 3, 'When you choose this tradition at 3rd level, you learn magical disciplines that harness the power of the four elements. A discipline requires you to spend ki points each time you use it. You know the Elemental Attunement discipline and one other elemental discipline of your choice. You learn one additional elemental discipline of your choice at 6th, 11th, and 17th level.'),
(98, 'Additional Elemental Discipline', 6, 'At 6th level, you learn one additional elemental discipline of your choice.'),
(98, 'Additional Elemental Discipline', 11, 'At 11th level, you learn one additional elemental discipline of your choice.'),
(98, 'Additional Elemental Discipline', 17, 'At 17th level, you learn one additional elemental discipline of your choice.');

-- Subclasse: Way of the Kensei (ID: 99)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(99, 'Path of the Kensei', 3, 'When you choose this tradition at 3rd level, your special martial arts training leads you to master the use of certain weapons. This path also includes instruction in the deft strokes of calligraphy or painting. You gain the following benefits: Kensei Weapons: Choose two types of weapons to be your kensei weapons: one melee weapon and one ranged weapon. Each of these weapons can be any simple or martial weapon that lacks the heavy and special properties. The longbow is also a valid choice. You gain proficiency with these weapons if you don''t already have it. Weapons of the chosen types are monk weapons for you. Many of this tradition''s features work only with your kensei weapons.'),
(99, 'One with the Blade', 6, 'At 6th level, you extend your ki into your kensei weapons, granting you the following benefits. Magic Kensei Weapons: Your attacks with your kensei weapons count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage. Deft Strike: When you hit a target with a kensei weapon, you can spend 1 ki point to cause the weapon to deal extra damage to the target equal to your Martial Arts die. You can use this feature only once on each of your turns.'),
(99, 'Sharpen the Blade', 11, 'At 11th level, you gain the ability to augment your weapons further with your ki. As a bonus action, you can expend up to 3 ki points to grant one kensei weapon you touch a bonus to attack and damage rolls when you attack with it. The bonus equals the number of ki points you spent. This bonus lasts for 1 minute or until you use this feature again.'),
(99, 'Unerring Accuracy', 17, 'At 17th level, your mastery of weapons grants you extraordinary accuracy. If you miss with an attack roll using a monk weapon on your turn, you can reroll it. You can use this feature only once on each of your turns.');

-- Subclasse: Way of the Long Death (ID: 100)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(100, 'Touch of Death', 3, 'Starting when you choose this tradition at 3rd level, your study of death allows you to extract vitality from another creature as it nears its demise. When you reduce a creature within 5 feet of you to 0 hit points, you gain temporary hit points equal to your Wisdom modifier + your monk level (minimum of 1 temporary hit point).'),
(100, 'Hour of Reaping', 6, 'At 6th level, you gain the ability to unsettle or terrify those around you as an action. When you take this action, each creature within 30 feet of you that can see you must succeed on a Wisdom saving throw or be frightened of you until the end of your next turn.'),
(100, 'Mastery of Death', 11, 'Beginning at 11th level, you use your familiarity with death to escape its grasp. When you are reduced to 0 hit points, you can expend 1 ki point (no action required) to have 1 hit point instead.'),
(100, 'Touch of the Long Death', 17, 'Starting at 17th level, your touch can channel the energy of death into a creature. As an action, you touch one creature within 5 feet of you, and you expend 1 to 10 ki points. The target must make a Constitution saving throw, and it takes 2d10 necrotic damage per ki point spent on a failed save, or half as much damage on a successful one.');

-- Subclasse: Way of Mercy (ID: 101)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(101, 'Implements of Mercy', 3, 'When you choose this tradition at 3rd level, you gain proficiency in the Insight and Medicine skills, and you gain proficiency with the herbalism kit. You also gain a special mask, which you often wear when using the features of this subclass. You determine its appearance, or generate it randomly by rolling on the Merciful Mask table.'),
(101, 'Hands of Healing', 3, 'At 3rd level, your mystical touch can mend wounds. As an action, you can spend 1 ki point to touch a creature and restore a number of hit points equal to a roll of your Martial Arts die + your Wisdom modifier. When you use your Flurry of Blows, you can replace one of the unarmed strikes with a use of this feature without spending a ki point for the healing.'),
(101, 'Hands of Harm', 3, 'At 3rd level, you use your ki to inflict wounds. When you hit a creature with an unarmed strike, you can spend 1 ki point to deal extra necrotic damage equal to one roll of your Martial Arts die + your Wisdom modifier. You can use this feature only once per turn.'),
(101, 'Physician''s Touch', 6, 'Starting at 6th level, you can administer even greater cures with a touch, and if you feel it''s necessary, you can use your knowledge to cause harm. When you use Hands of Healing on a creature, you can also end one disease or one of the following conditions affecting the creature: blinded, deafened, paralyzed, poisoned, or stunned. When you use Hands of Harm on a creature, you can subject that creature to the poisoned condition until the end of your next turn.'),
(101, 'Flurry of Healing and Harm', 11, 'Starting at 11th level, you can now mete out a flurry of comfort and hurt. When you use Flurry of Blows, you can now replace each of the unarmed strikes with a use of your Hands of Healing, without spending ki points for the healing. In addition, when you make an unarmed strike with Flurry of Blows, you can use Hand of Harm with that strike without spending the ki point for Hands of Harm. You can still use Hands of Harm only once per turn.'),
(101, 'Hand of Ultimate Mercy', 17, 'By 17th level, your mastery of life energy opens the door to the ultimate mercy. As an action, you can touch the corpse of a creature that died within the past 24 hours and expend 5 ki points. The creature then returns to life, regaining a number of hit points equal to 4d10 + your Wisdom modifier. If the creature died while subject to any of the following conditions, it revives with them removed: blinded, deafened, paralyzed, poisoned, and stunned. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Way of the Open Hand (ID: 102)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(102, 'Open Hand Technique', 3, 'Starting when you choose this tradition at 3rd level, you can manipulate your enemy''s ki when you harness your own. Whenever you hit a creature with one of the attacks granted by your Flurry of Blows, you can impose one of the following effects on that target: It must succeed on a Dexterity saving throw or be knocked prone. It must make a Strength saving throw. If it fails, you can push it up to 15 feet away from you. It can''t take reactions until the end of your next turn.'),
(102, 'Wholeness of Body', 6, 'At 6th level, you gain the ability to heal yourself. As an action, you can regain hit points equal to three times your monk level. You must finish a long rest before you can use this feature again.'),
(102, 'Tranquility', 11, 'Beginning at 11th level, you can enter a special meditation that surrounds you with an aura of peace. At the end of a long rest, you gain the effect of a Sanctuary spell that lasts until the start of your next long rest.'),
(102, 'Quivering Palm', 17, 'At 17th level, you gain the ability to set up lethal vibrations in someone''s body. When you hit a creature with an unarmed strike, you can spend 3 ki points to start these imperceptible vibrations, which last for a number of days equal to your monk level.');

-- Subclasse: Way of Shadow (ID: 103)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(103, 'Shadow Arts', 3, 'Starting when you choose this tradition at 3rd level, you can use your ki to duplicate the effects of certain spells. As an action, you can spend 2 ki points to cast darkness, darkvision, pass without trace, or silence, without providing material components. Additionally, you gain the minor illusion cantrip if you don''t already know it.'),
(103, 'Shadow Step', 6, 'At 6th level, you gain the ability to step from one shadow into another. When you are in dim light or darkness, as a bonus action you can teleport up to 60 feet to an unoccupied space you can see that is also in dim light or darkness. You then have advantage on the first melee attack you make before the end of the turn.'),
(103, 'Cloak of Shadows', 11, 'By 11th level, you have learned to become one with the shadows. When you are in an area of dim light or darkness, you can use your action to become invisible. You remain invisible until you make an attack, cast a spell, or are in an area of bright light.'),
(103, 'Opportunist', 17, 'At 17th level, you can exploit a creature''s momentary distraction when it is hit by an attack. Whenever a creature within 5 feet of you is hit by an attack made by a creature other than you, you can use your reaction to make a melee attack against that creature.');

-- Subclasse: Way of the Sun Soul (ID: 104)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(104, 'Radiant Sun Bolt', 3, 'Starting when you choose this tradition at 3rd level, you can hurl searing bolts of magical radiance. You gain a new attack option that you can use with the Attack action. This special attack is a ranged spell attack with a range of 30 feet. You are proficient with it, and you add your Dexterity modifier to its attack and damage rolls. Its damage is radiant, and its damage die is a d4. This die changes as you gain monk levels. When you take the Attack action on your turn and use this special attack as part of it, you can spend 1 ki point to make the special attack twice as a bonus action.'),
(104, 'Searing Arc Strike', 6, 'At 6th level, you gain the ability to channel your ki into searing waves of energy. Immediately after you take the Attack action on your turn, you can spend 2 ki points to cast the Burning Hands spell as a bonus action.'),
(104, 'Searing Sunburst', 11, 'At 11th level, you gain the ability to create an orb of light that erupts into a devastating explosion. As an action, you magically create an orb and hurl it at a point you choose within 150 feet, where it erupts into a sphere of radiant light for a brief but deadly instant. Each creature in that 20-foot-radius sphere must succeed on a Constitution saving throw or take 2d6 radiant damage.'),
(104, 'Sun Shield', 17, 'At 17th level, you become wreathed in a luminous, magical aura. You shed bright light in a 30-foot radius and dim light for an additional 30 feet. If a creature hits you with a melee attack while this light shines, you can use your reaction to deal radiant damage to the creature equal to 5 + your Wisdom modifier.');

-- Subclasse: Way of the Ascendant Dragon (UA) (ID: 105)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(105, 'Draconic Disciple', 3, 'At 3rd-level you can channel your draconic ki to imbue your unarmed strikes with the essence of a dragon''s breath and to use your connection with draconic creatures to magnify your presence. You gain the following benefits: When you damage a target with an unarmed strike, you can change the damage type to acid, cold, fire, lightning, or poison. If you can''t already, you learn to speak, read, and write Draconic. If you fail a Charisma (Intimidation) or Charisma (Persuasion) check, you can use your reaction to reroll the check, as you tap into the mighty presence of dragons. Once this feature turns a failure into a success, you can''t use it again until you finish a long rest.'),
(105, 'Breath of the Dragon', 3, 'At 3rd-level you can channel your ki into destructive waves of energy like the dragons you emulate. When you take the Attack action on your turn, you can replace one of the attacks with an exhalation of draconic energy in either a 20-foot cone or a 30-foot line that is 5 feet wide (your choice). Choose a damage type: acid, cold, fire, lightning, or poison. Each creature in the area must make a Dexterity saving throw against your ki save DC, taking damage of the chosen type equal to two rolls of your Martial Arts die on a failure, or half as much damage on a success. At 11th level, the damage of your breath increases to three rolls of your Martial Arts die. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest. While you have no uses available, you can spend 1 ki point to use this feature again.'),
(105, 'Wings Unfurled', 6, 'At 6th-level when you use your Step of the Wind, you can unfurl spectral draconic wings from your back that vanish at the end of your turn. While the wings exist, you have a flying speed equal to your walking speed. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest. While you have no uses available, you can spend 1 additional ki point when you activate Step of the Wind to use this feature again.'),
(105, 'Aspect of the Wyrm', 11, 'When you reach 11th-level the power of your draconic ki now radiates from you, protecting your allies from harm and punishing any who raise arms against them. As a bonus action, you can create an aura of draconic power that radiates 30 feet from you for 1 minute. Choose acid, cold, fire, lightning, or poison damage, and for the duration, you gain the following effects: You and your allies within your aura gain resistance to the chosen damage type. Once you use this bonus action, you can''t use it again until you finish a long rest, unless you expend 4 ki points to use it again.'),
(105, 'Ascendant Aspect', 17, 'At 17th-level your draconic ki reaches its peak. You gain the following benefits: You gain blindsight out to 30 feet. When you activate your Aspect of the Wyrm, draconic fury explodes from you. Choose any number of creatures you can see within your aura. Those creatures each take 4d10 acid, cold, fire, lightning, or poison damage (your choice).');

-- Subclasse: Way of the Astral Self (UA) (ID: 106)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(106, 'Arms of the Astral Self', 3, 'At 3rd level, your mastery of your ki allows you to summon a portion of your astral self. On your turn, you can spend 2 ki points as a bonus action to summon the arms of your astral self for 10 minutes. These spectral arms hover near your shoulders. While your astral arms are summoned, you gain the following benefits: You can use your Wisdom modifier in place of your Strength modifier when making Strength checks and Strength saving throws. The arms are monk weapons and have a reach of 10 feet. The arms deal radiant or necrotic damage (your choice).'),
(106, 'Visage of the Astral Self', 6, 'Starting at 6th level, you can summon the visage of your astral self. On your turn, you can spend 1 ki point as a bonus action, or as part of summoning your astral arms, to summon this visage for 10 minutes. While your visage is summoned, you gain Wisdom of the Spirit and Astral Sight.'),
(106, 'Awakening of the Astral Self', 11, 'Starting at 11th level, you tap into the greater power of your astral self. While you have both your astral arms and visage summoned, you gain Deflect Energy and Empowered Arms.'),
(106, 'Complete Astral Self', 17, 'Starting at 17th level, your connection to your astral self is complete, allowing you summon it entirely. On your turn, you can spend 10 ki points as a bonus action to summon the arms, visage, and body of your astral self for 10 minutes. While your astral self is summoned, you gain a +2 bonus to AC and Astral Barrage.');

-- Subclasse: Kensei (UA) (ID: 107)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(107, 'Path of the Kensei', 3, 'When you choose this tradition at 3rd level, you learn to extend your knowledge of the martial arts beyond the standard array of monk weapons. You gain proficiency with three martial weapons of your choice. A martial weapon is considered a kensei weapon for you if you''re proficient with it. Whenever you wield a kensei weapon, you choose whether to use Dexterity or Strength for the attack and damage rolls of the weapon.'),
(107, 'One with the Blade', 6, 'At 6th level, you extend your ki into the weapons you hold, granting you benefits: your kensei weapon attacks count as magical for overcoming resistance and you can use Precise Strike once per rest.'),
(107, 'Sharpen the Blade', 11, 'At 11th level, you can expend up to 3 ki points to grant a weapon you touch a bonus to attack and damage rolls equal to the number of ki points spent for 1 minute.'),
(107, 'Unerring Accuracy', 17, 'At 17th level, on each of your turns, you can reroll one weapon attack roll you make that misses.');

-- Subclasse: Way of Mercy (UA) (ID: 108)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(108, 'Implements of Mercy', 3, 'At 3rd level, you gain proficiency in the Insight or Medicine skill (your choice), and you gain proficiency with the herbalism kit and the poisoner''s kit.'),
(108, 'Hands of Healing', 3, 'As an action, you can spend 1 ki point to touch a creature and restore a number of hit points equal to a roll of your Martial Arts die + your Wisdom modifier.'),
(108, 'Hands of Harm', 3, 'When you hit a creature with an unarmed strike, you can spend 1 ki point to deal extra necrotic damage equal to one roll of your Martial Arts die.'),
(108, 'Noxious Aura', 6, 'As a bonus action, you spend 1 ki point to turn your ki into an aura of toxic miasma. The aura extends 5 feet from you, lasts 1 minute, and forces creatures starting their turn there to make a Constitution save or be poisoned and take poison damage equal to your Wisdom modifier.'),
(108, 'Healing Technique', 11, 'When you restore hit points to a creature using your Hands of Healing, you can also end one disease or a condition from the specified list.'),
(108, 'Hand of Mercy', 17, 'As an action, you can touch a creature, expend 4 ki points, and force the creature to make a Constitution saving throw; on a failed save the creature enters suspended animation.');

-- Subclasse: Way of Tranquility (UA) (ID: 109)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(109, 'Path of Tranquility', 3, 'When you choose this tradition at 3rd level, you can become an island of calm in even the most chaotic of situations. With this feature, you can cast the sanctuary spell on yourself, no material component required, and it lasts up to 8 hours.'),
(109, 'Healing Hands', 3, 'You have a pool of magical healing power that replenishes when you take a long rest. You can restore hit points from this pool as an action.'),
(109, 'Emissary of Peace', 6, 'At 6th level, you gain advantage on Charisma checks to calm violent emotions and gain proficiency in Performance or Persuasion.'),
(109, 'Douse the Flames of War', 11, 'As an action, you can touch a creature; it must make a Wisdom save or be unable to attack for 1 minute.'),
(109, 'Anger of a Gentle Soul', 17, 'When you see a creature reduce another to 0 HP, you can use your reaction to gain a bonus to all damage rolls against the aggressor equal to your monk level.');
