-- =============================================================================
-- FIGHTER SUBCLASSES 
-- =============================================================================

-- Subclasse: Arcane Archer (ID: 72)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(72, 'Arcane Arrow', 3, 'When you choose this archetype at 3rd level, you learn to channel magic into your attacks with a longbow or shortbow.'),
(72, 'Arcane Shot', 3, 'At 3rd level, you learn to unleash special magical effects with some of your shots. When you gain this feature, you learn two Arcane Shot options of your choice. Whenever you create a magic arrow with this feature, you can apply the benefits of one of your Arcane Shot options to that arrow. You gain an additional Arcane Shot option of your choice at 7th, 10th, 15th, and 18th level.'),
(72, 'Archer''s Lore', 3, 'At 3rd level, you learn a few skills relating to the typical duties of an Arcane Archer. You learn to understand magical theory and develop survival skills for wandering the wilds. You gain proficiency in two of the following skills of your choice: Arcana, Athletics, Nature, Perception, Stealth, and Survival.'),
(72, 'Conjure Arrows', 7, 'At 7th level, you learn a minor but useful magical trick. As an action, you can conjure 20 non-magical arrows. The arrows appear in your hand or in a container, such as a quiver, on your body. The arrows remain for 10 minutes or until you use this feature again; they then vanish.'),
(72, 'Ever-Ready Arrow', 15, 'Starting at 15th level, you can conjure forth a magic-infused arrow more often than before. One minute after expending your last remaining use of Arcane Arrow, you regain one use of it.'),
(72, 'Deadly Arrow', 18, 'At 18th level, your Arcane Arrow''s bonus damage increases to 4d6 force damage.');

-- Subclasse: Banneret (ID: 73)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(73, 'Rallying Cry', 3, 'When you choose this archetype at 3rd level, you learn how to inspire your allies to fight on past their injuries. When you use your Second Wind feature, you can choose up to three creatures within 60 feet of you that are allied with you. Each one regains hit points equal to your fighter level, provided that the creature can see or hear you.'),
(73, 'Royal Envoy', 7, 'Knights of high standing are expected to conduct themselves with grace. At 7th level, you gain proficiency in the Persuasion skill. If you are already proficient in it, you gain proficiency in one of the following skills of your choice: Animal Handling, Insight, Intimidation, or Performance. Your proficiency bonus is doubled for any ability check you make that uses Persuasion. You receive this benefit regardless of the skill proficiency you gain from this feature.'),
(73, 'Inspiring Surge', 10, 'Starting at 10th level, when you use your Action Surge feature, you can choose one creature within 60 feet of you that is allied with you. That creature can make one melee or ranged weapon attack with its reaction, provided that it can see or hear you. Starting at 18th level, you can choose two allies within 60 feet of you, rather than one.'),
(73, 'Bulwark', 15, 'Beginning at 15th level, you can extend the benefit of your Indomitable feature to an ally. When you decide to use Indomitable to reroll an Intelligence, a Wisdom, or a Charisma saving throw and you aren''t incapacitated, you can choose one ally within 60 feet of you that also failed its saving throw against the same effect. If that creature can see or hear you, it can reroll its saving throw and must use the new roll.');

-- Subclasse: Battle Master (ID: 74)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(74, 'Combat Superiority', 3, 'When you choose this archetype at 3rd level, you learn maneuvers that are fueled by special dice called superiority dice. You learn three maneuvers of your choice. You gain four superiority dice, which are d8s. A superiority die is expended when you use it. You regain all expended superiority dice when you finish a short or long rest. You gain one additional superiority die at 7th level and another at 15th level.'),
(74, 'Student of War', 3, 'At 3rd level, you gain proficiency with one type of artisan''s tools of your choice.'),
(74, 'Know Your Enemy', 7, 'At 7th level, if you spend at least 1 minute observing or interacting with another creature outside combat, you can learn certain information about its capabilities.'),
(74, 'Improved Combat Superiority', 10, 'At 10th level, your superiority dice turn into d10s. At 18th level, they become d12s.'),
(74, 'Relentless', 15, 'Starting at 15th level, when you roll initiative and have no superiority dice remaining, you regain one superiority die.');

-- Subclasse: Cavalier (ID: 75)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(75, 'Bonus Proficiency', 3, 'When you choose this archetype at 3rd level, you gain proficiency in one of the following skills of your choice: Animal Handling, History, Insight, Performance, or Persuasion. Alternatively, you learn one language of your choice.'),
(75, 'Born to the Saddle', 3, 'At 3rd level, your mastery of mounts allows you to fight with a steed. You have advantage on saving throws made to avoid falling off your mount. If you fall off your mount and land on your feet, you can use your reaction to make a melee attack against a creature within 5 feet of you.'),
(75, 'Unwavering Mark', 3, 'Starting at 3rd level, you can mark a creature you hit with a weapon attack. Until the end of your next turn, any attack roll against the marked creature has advantage if it doesn''t include you as a target. You can use this feature a number of times equal to your Strength modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(75, 'Warding Maneuver', 7, 'At 7th level, you learn to interpose your shield or weapon to deflect an attack. When a creature you can see within 5 feet of you is hit by an attack, you can use your reaction to add your proficiency bonus to the target''s AC against that attack, potentially causing the attack to miss.'),
(75, 'Hold the Line', 10, 'At 10th level, you are a master of battlefield control. Creatures provoke an opportunity attack from you when they move 5 feet or more while within your reach.'),
(75, 'Vigilant Defender', 15, 'At 15th level, you are a master of battlefield control. You can make an opportunity attack against a creature that moves 5 feet or more while within your reach.'),
(75, 'Unyielding Sentinel', 18, 'At 18th level, you are a master of battlefield control. When you are reduced to 0 hit points, you can choose to drop to 1 hit point instead. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Champion (ID: 76)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(76, 'Improved Critical', 3, 'Beginning when you choose this archetype at 3rd level, your weapon attacks score a critical hit on a roll of 19 or 20.'),
(76, 'Remarkable Athlete', 7, 'Starting at 7th level, you can add half your proficiency bonus (rounded up) to any Strength, Dexterity, or Constitution check you make that doesn''t already use your proficiency bonus. In addition, when you make a running long jump, the distance you can cover increases by a number of feet equal to your Strength modifier.'),
(76, 'Additional Fighting Style', 10, 'At 10th level, you can choose a second option from the Fighting Style class feature.'),
(76, 'Superior Critical', 15, 'Starting at 15th level, your weapon attacks score a critical hit on a roll of 18–20.'),
(76, 'Survivor', 18, 'At 18th level, you attain the pinnacle of resilience in battle. At the start of each of your turns, you regain hit points equal to 5 + your Constitution modifier if you have no more than half of your hit points left. You don''t gain this benefit if you have 0 hit points.');

-- Subclasse: Echo Knight (ID: 77)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(77, 'Manifest Echo', 3, 'You can use a bonus action to manifest an echo of yourself in an unoccupied space within 15 feet of you. This echo is a magical, translucent, gray image of you. It has 1 hit point, an AC of 14 + your proficiency bonus, and immunity to all conditions. If it takes any damage, it is destroyed. It lasts until it is destroyed, until you dismiss it as a bonus action, or until you manifest another echo. You can use your echo to make melee attacks, and you can teleport to its space.'),
(77, 'Unleash Incarnation', 3, 'Whenever you take the Attack action, you can make one additional melee attack from the echo''s position.'),
(77, 'Echo Avatar', 7, 'You can temporarily transfer your consciousness to your echo. As an action, you can see and hear through your echo and control it for 10 minutes. During this time, you are blind and deaf. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(77, 'Resonance Cascade', 10, 'When your echo is destroyed, you can use your reaction to cause it to explode, dealing 2d8 force damage to creatures within 10 feet of it.'),
(77, 'Shadow Martyr', 15, 'When an ally within 30 feet of you takes damage, you can use your reaction to teleport your echo to an unoccupied space within 5 feet of that ally. Your echo takes the damage instead of your ally.'),
(77, 'Legion of One', 18, 'You can manifest two echoes at once. When you do so, you can use your bonus action to make one additional melee attack from each echo''s position.');

-- Subclasse: Eldritch Knight (ID: 78)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(78, 'Weapon Bond', 3, 'You learn a ritual that creates a magical bond between yourself and one weapon. You can have up to two bonded weapons. You can''t be disarmed of a bonded weapon unless you are incapacitated. If it is on the same plane of existence, you can summon that weapon as a bonus action on your turn, causing it to teleport instantly to your hand.'),
(78, 'Spellcasting', 3, 'You gain the ability to cast spells. See chapter 10 for the general rules of spellcasting and chapter 11 for the Eldritch Knight spell list. Cantrips. You learn two cantrips of your choice from the wizard spell list. You learn an additional wizard cantrip of your choice at 10th level. Spell Slots. The Eldritch Knight Spellcasting table shows how many spell slots you have to cast your spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell''s level or higher. You regain all expended spell slots when you finish a long rest. Spells Known of 1st Level and Higher. You know three 1st-level wizard spells of your choice, two of which you must choose from the abjuration and evocation spells sections of the wizard spell list. The Spells Known column of the Eldritch Knight Spellcasting table shows when you learn more wizard spells of 1st level and higher. Each of these spells must be an abjuration or evocation spell of your choice, and must be of a level for which you have spell slots. When you reach 8th, 14th, and 20th level, you can choose one spell from any school of magic. Whenever you gain a level in this class, you can replace one of the wizard spells you know with another spell of your choice from the wizard spell list. The new spell must also be an abjuration or evocation spell, unless you''re replacing the spell you gained at 8th, 14th, or 20th level. Spellcasting Ability. Intelligence is your spellcasting ability for your wizard spells, since you learn your spells through study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for a wizard spell you cast and when making an attack roll with one.'),
(78, 'War Magic', 7, 'When you use your action to cast a cantrip, you can make one weapon attack as a bonus action.'),
(78, 'Eldritch Strike', 10, 'When you hit a creature with a weapon attack, that creature has disadvantage on the next saving throw it makes against a spell you cast before the end of your next turn.'),
(78, 'Arcane Charge', 15, 'When you use your Action Surge feature, you can teleport up to 30 feet to an unoccupied space you can see.'),
(78, 'Improved War Magic', 18, 'When you use your action to cast a spell, you can make one weapon attack as a bonus action.');

-- Subclasse: Psi Warrior (ID: 79)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(79, 'Psionic Power', 3, 'You harbor a wellspring of psionic energy within yourself. This energy is represented by your Psionic Energy dice, which are d6s. You have a number of these dice equal to twice your proficiency bonus, and they fuel various psionic powers you have, which are detailed below. Some of your powers expend the die they use, and some don’t. You regain all expended Psionic Energy dice when you finish a long rest. In addition, as a bonus action, you can regain one expended Psionic Energy die, but you can’t do so again until you finish a short or long rest.'),
(79, 'Protective Field', 3, 'When you or another creature you can see within 30 feet of you takes damage, you can use your reaction to expend one Psionic Energy die, roll the die, and reduce the damage by the number rolled + your Intelligence modifier (minimum reduction of 1).'),
(79, 'Telekinetic Movement', 3, 'As a bonus action, you can move an object or creature with your mind. You can move one object that isn''t being worn or carried and that weighs no more than 1,000 pounds up to 30 feet in any direction. Alternatively, you can move one willing creature that isn''t being worn or carried and that weighs no more than 1,000 pounds up to 30 feet in any direction.'),
(79, 'Telekinetic Thrust', 7, 'When you hit a creature with a weapon attack, you can expend one Psionic Energy die, roll the die, and push the target up to 15 feet away from you. If the target is pushed into an object or another creature, it takes bludgeoning damage equal to the number rolled on the Psionic Energy die.'),
(79, 'Psi-Powered Leap', 7, 'As a bonus action, you can expend one Psionic Energy die, roll the die, and increase your jump distance by a number of feet equal to 10 times the number rolled. This increase lasts until the end of your turn.'),
(79, 'Guarded Mind', 10, 'You gain resistance to psychic damage. If you are charmed or frightened, you can use your action to end the effect.'),
(79, 'Psionic Strike', 10, 'When you hit a creature with a weapon attack, you can expend one Psionic Energy die, roll the die, and deal extra force damage to the target equal to the number rolled.'),
(79, 'Bulwark', 15, 'When you or another creature you can see within 30 feet of you takes damage, you can use your reaction to expend one Psionic Energy die, roll the die, and reduce the damage by the number rolled + your Intelligence modifier (minimum of 1).'),
(79, 'Telekinetic Master', 18, 'You can cast the Telekinesis spell without expending a spell slot. You can do so a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.');

-- Subclasse: Psi Knight (ID: 80)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(80, 'Psionic Talent', 3, 'You harbor a wellspring of psionic power within yourself, an energy that ebbs and flows as you channel it in various ways. This power is represented by your Psionic Talent die, the starting size of which is a d6. You can use your Psionic Talent die in the following ways: Protective Field, Psi-Powered Leap, Telekinetic Strike.'),
(80, 'Psi Replenishment', 3, 'As a bonus action, you can calm your mind for a moment and restore your Psionic Talent die to its starting size. You then can’t use Psi Replenishment again until you finish a long rest.'),
(80, 'Telekinetic Adept', 7, 'You have mastered new ways to use your telekinesis: Psionic Thrust and Telekinetic Movement.'),
(80, 'Psi-Enhanced Metabolism', 10, 'The psionic energy flowing through you has bolstered your mind and body. You have resistance to poison and psychic damage, and you are immune to the poisoned condition.'),
(80, 'Bulwark of Force', 15, 'You can shield yourself and others with telekinetic force. As a bonus action, you can choose creatures, which can include you, that you can see within 30 feet of you, up to a number of creatures equal to your Intelligence modifier (minimum of one creature). Each of the chosen creatures is protected by half cover for 1 minute or until you’re incapacitated. Once you use this feature, you can’t do so again until you finish a long rest, unless you decrease your Psionic Talent die by one die size to use this feature again.'),
(80, 'Telekinetic Master', 18, 'Your ability to move creatures and objects with your mind is matched by few. If your Psionic Talent die is available, you can cast the telekinesis spell, requiring no components. Your spellcasting ability for the spell is Intelligence. When you cast this spell, your Psionic Talent die decreases by one die size.');

-- Subclasse: Rune Knight (ID: 81)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(81, 'Bonus Proficiencies', 3, 'You gain proficiency with smith''s tools, and you learn to speak, read, and write Giant.'),
(81, 'Rune Carver', 3, 'You learn two runes of your choice. Each time you gain a level in this class, you can replace one rune you know with a different one. When you gain certain fighter levels, you learn additional runes.'),
(81, 'Giant''s Might', 3, 'As a bonus action, you can magically increase your size. You become Large, your reach increases by 5 feet, and your weapon attacks deal an extra 1d6 damage. This lasts for 1 minute. You can use this feature a number of times equal to your proficiency bonus per long rest.'),
(81, 'Defensive Runes', 7, 'You learn to invoke your runes to protect your allies. When a creature you can see within 30 feet of you takes damage, you can use your reaction to expend one use of your Rune Carver feature, roll a d6, and reduce the damage by the number rolled + your Intelligence modifier.'),
(81, 'Great Stature', 10, 'The benefits of your Giant''s Might feature increase. Your size becomes Huge, your reach increases by 10 feet, and your weapon attacks deal an extra 2d6 damage.'),
(81, 'Runic Shield', 15, 'When a creature you can see within 60 feet of you makes an attack roll, you can use your reaction to force that creature to reroll the attack roll. You can use this feature a number of times equal to your proficiency bonus per long rest.'),
(81, 'Demigod''s Might', 18, 'The benefits of your Giant''s Might feature increase. Your size becomes Gargantuan, your reach increases by 15 feet, and your weapon attacks deal an extra 3d6 damage.');

-- Subclasse: Samurai (ID: 82)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(82, 'Bonus Proficiency', 3, 'When you choose this archetype at 3rd level, you gain proficiency in one of the following skills of your choice: History, Insight, Performance, or Persuasion. Alternatively, you learn one language of your choice.'),
(82, 'Fighting Spirit', 3, 'As a bonus action on your turn, you can give yourself advantage on all weapon attack rolls until the end of the current turn. When you do so, you also gain temporary hit points equal to 5 + your fighter level. You can use this feature three times, and you regain all expended uses when you finish a long rest.'),
(82, 'Elegant Courtier', 7, 'Your discipline and charm allow you to remain composed in any social situation. You gain proficiency in the Persuasion skill. If you are already proficient in it, you gain proficiency in one of the following skills of your choice: Animal Handling, Insight, Intimidation, or Performance. Your proficiency bonus is doubled for any ability check you make that uses Persuasion. You receive this benefit regardless of the skill proficiency you gain from this feature.'),
(82, 'Tireless Spirit', 10, 'Starting at 10th level, when you roll initiative and have no uses of Fighting Spirit remaining, you regain one use.'),
(82, 'Rapid Strike', 15, 'At 15th level, you learn to trade accuracy for a flurry of blows. When you take the Attack action on your turn and have advantage on an attack roll against one of the targets, you can forgo that advantage to make an additional weapon attack against that target, as part of the same action. You can do so only once per turn.'),
(82, 'Strength Before Death', 18, 'Starting at 18th level, your will to fight can defy even death. If you are reduced to 0 hit points and don''t die outright, you can use your reaction to delay falling unconscious, and you can immediately take an extra turn. While you have 0 hit points during that extra turn, taking damage causes death saving throw failures as normal, and three failures still result in death. When the extra turn ends, you fall unconscious if you still have 0 hit points. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Arcane Archer (UA) (ID: 83)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(83, 'Magic Arrow', 3, 'When you choose this archetype at 3rd level, you gain the ability to infuse arrows with magic. Whenever you fire a nonmagical arrow from a shortbow or longbow, you can make it a magic arrow, with a +1 bonus to the attack and damage rolls. The magic fades from the arrow immediately after it hits or misses its target.'),
(83, 'Arcane Shot', 3, 'At 3rd level, you learn to unleash special magical effects with some of your shots. When you gain this feature, you learn two Arcane Shot options of your choice. Once per turn when you fire a magic arrow from a shortbow or longbow as part of the Attack action, you can apply one of your Arcane Shot options to that arrow. You decide to use the option when the arrow hits, unless the option doesn''t involve an attack roll. You have two uses of this ability, and you regain all expended uses of it when you finish a short or long rest.'),
(83, 'Arcane Archer''s Lore', 3, 'At 3rd level, you learn magical theory or some of the secrets of nature—typical for practitioners of this elven martial tradition. You gain proficiency in either the Arcana or the Nature skill.'),
(83, 'Curving Shot', 7, 'At 7th level, you learn how to direct an errant arrow toward a new target. When you make an attack roll with a magic arrow and miss, you can use a bonus action to reroll the attack rollagainst a different target within 60 feet of the original target.'),
(83, 'Ever-Ready Shot', 15, 'Starting at 15th level, your magical archery is ever available to you when you need it most. If you roll initiative and have no uses of Arcane Shot remaining, you regain one use of it.');

-- Subclasse: Arcane Archer Revised (UA) (ID: 84)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(84, 'Magic Arrow', 3, 'When you choose this archetype at 3rd level, you gain the ability to infuse arrows with magic. Whenever you fire a nonmagical arrow from a shortbow or longbow, you can make it a magic arrow, with a +1 bonus to the attack and damage rolls. The magic fades from the arrow immediately after it hits or misses its target.'),
(84, 'Arcane Shot', 3, 'At 3rd level, you learn to unleash special magical effects with some of your shots. When you gain this feature, you learn two Arcane Shot options of your choice. Once per turn when you fire a magic arrow from a shortbow or longbow as part of the Attack action, you can apply one of your Arcane Shot options to that arrow. You decide to use the option when the arrow hits, unless the option doesn''t involve an attack roll. You have two uses of this ability, and you regain all expended uses of it when you finish a short or long rest.'),
(84, 'Arcane Archer''s Lore', 3, 'At 3rd level, you learn magical theory or some of the secrets of nature—typical for practitioners of this elven martial tradition. You gain proficiency in either the Arcana or the Nature skill.'),
(84, 'Curving Shot', 7, 'At 7th level, you learn how to direct an errant arrow toward a new target. When you make an attack roll with a magic arrow and miss, you can use a bonus action to reroll the attack rollagainst a different target within 60 feet of the original target.'),
(84, 'Ever-Ready Shot', 15, 'Starting at 15th level, your magical archery is ever available to you when you need it most. If you roll initiative and have no uses of Arcane Shot remaining, you regain one use of it.');

-- Subclasse: Brute (UA) (ID: 85)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(85, 'Brute Force', 3, 'When you hit a creature with a weapon attack, you can cause the attack to deal extra damage equal to 1d4. This extra damage increases as you gain levels in this class, increasing to 1d6 at 5th level, 1d8 at 11th level, and 1d10 at 17th level.'),
(85, 'Brutish Durability', 7, 'Your hit point maximum increases by an amount equal to your fighter level, and it increases by 1 every time you gain a level in this class.'),
(85, 'Devastating Critical', 10, 'When you score a critical hit with a weapon attack, you can roll one additional damage die for the attack.'),
(85, 'Feral Instinct', 15, 'You have advantage on initiative rolls. Additionally, if you are surprised at the beginning of combat and aren''t incapacitated, you can act normally on your first turn, but only if you move at least 10 feet and make a melee attack.'),
(85, 'Brute Superiority', 18, 'When you use your Action Surge feature, you can make one additional weapon attack as part of that action.');

-- Subclasse: Cavalier (UA) (ID: 86)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(86, 'Bonus Proficiency', 3, 'When you choose this archetype at 3rd level, you gain proficiency in one of the following skills of your choice: Animal Handling, History, Insight, Performance, or Persuasion. Alternatively, you learn one language of your choice.'),
(86, 'Born to the Saddle', 3, 'At 3rd level, your mastery of mounts allows you to fight with a steed. You have advantage on saving throws made to avoid falling off your mount. If you fall off your mount and land on your feet, you can use your reaction to make a melee attack against a creature within 5 feet of you.'),
(86, 'Unwavering Mark', 3, 'Starting at 3rd level, you can mark a creature you hit with a weapon attack. Until the end of your next turn, any attack roll against the marked creature has advantage if it doesn''t include you as a target. You can use this feature a number of times equal to your Strength modifier (minimum of once). You regain all expended uses when you finish a long rest.'),
(86, 'Warding Maneuver', 7, 'At 7th level, you learn to interpose your shield or weapon to deflect an attack. When a creature you can see within 5 feet of you is hit by an attack, you can use your reaction to add your proficiency bonus to the target''s AC against that attack, potentially causing the attack to miss.'),
(86, 'Hold the Line', 10, 'At 10th level, you are a master of battlefield control. Creatures provoke an opportunity attack from you when they move 5 feet or more while within your reach.'),
(86, 'Vigilant Defender', 15, 'At 15th level, you are a master of battlefield control. You can make an opportunity attack against a creature that moves 5 feet or more while within your reach.'),
(86, 'Unyielding Sentinel', 18, 'At 18th level, you are a master of battlefield control. When you are reduced to 0 hit points, you can choose to drop to 1 hit point instead. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Knight (UA) (ID: 87)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(87, 'Born to the Saddle', 3, 'Starting at 3rd level, mounting or dismounting a creature costs you only 5 feet of movement, rather than half your speed. In addition, you have advantage on saving throws made to avoid falling off your mount. If you fall off it, you can automatically land on your feet if you aren’t incapacitated and you fall less than 10 feet.'),
(87, 'Implacable Mark', 3, 'At 3rd level, you excel at foiling attacks and protecting your allies by menacing your foes. When you hit a creature with a melee weapon attack, the target is marked by you until the end of your next turn. A creature ignores this effect if the creature can’t be frightened. The marked target has disadvantage on any attack roll against a creature other than you or someone else who marked it. If a target marked by you is within 5 feet of you on its turn and it moves at least 1 foot or makes an attack that suffers disadvantage from this feature, you can make one melee weapon attack against it using your reaction. This attack roll has advantage, and if it hits, the attack’s weapon deals extra damage to the target equal to your fighter level. You can make this special attack even if you have already expended your reaction this round, but not if you have already used your reaction this turn. You can make this attack three times, and you regain all expended uses of it when you finish a short or long rest.'),
(87, 'Noble Cavalry', 7, 'At 7th level, you gain proficiency in two of the following skills of your choice: Animal Handling, History, Insight, Persuasion, or Religion. Alternatively, you learn one language of your choice.'),
(87, 'Hold the Line', 10, 'At 10th level, you master the ability to harass and slow your enemies. As a reaction when a creature moves at least 1 foot within 5 feet of you, you can make one melee weapon attack against that creature. If you hit, the attack’s weapon deals extra damage to the target equal to half your fighter level, and the target’s speed is reduced to 0 until the end of this turn.'),
(87, 'Rapid Strike', 15, 'Starting at 15th level, you learn to trade accuracy for swift strikes. If you have advantage on a weapon attack against a target on your turn, you can forgo that advantage to immediately make an additional weapon attack against the same target as a bonus action.'),
(87, 'Defender''s Blade', 18, 'At 18th level, you respond to danger with extraordinary vigilance. You can use your reaction for an opportunity attack even if you have already expended your reaction this round, but not if you have already used your reaction this turn. In addition, you gain a +1 bonus to AC while wearing heavy armor.');

-- Subclasse: Monster Hunter (UA) (ID: 88)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(88, 'Hunter''s Sense', 3, 'You gain the ability to magically discern the weaknesses of creatures. As a bonus action, you can choose one creature you can see within 60 feet of you. You learn its damage vulnerabilities, resistances, and immunities, if any, and any condition immunities it has. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(88, 'Slayer''s Prey', 3, 'As a bonus action, you can mark one creature you can see within 60 feet of you as your prey. The first time you hit the prey with a weapon attack on each of your turns, you deal an extra 1d6 damage to it. This benefit lasts until you finish a short or long rest. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.'),
(88, 'Supernatural Defense', 7, 'You gain an uncanny ability to thwart the attacks of creatures you have marked. When a creature you have marked as your prey hits you with an attack, you can use your reaction to reduce the damage by an amount equal to your proficiency bonus.'),
(88, 'Relentless Hunter', 10, 'When you reduce a creature you have marked as your prey to 0 hit points, you can use your reaction to move up to half your speed and make one weapon attack against a new creature.'),
(88, 'Improved Slayer''s Prey', 15, 'The extra damage from your Slayer''s Prey feature increases to 2d6.'),
(88, 'Slayer''s Counter', 18, 'When a creature you have marked as your prey hits you with an attack, you can use your reaction to make one weapon attack against that creature.');

-- Subclasse: Psi Warrior (UA) (ID: 89)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(89, 'Psionic Power', 3, 'You harbor a wellspring of psionic energy within yourself. This energy is represented by your Psionic Energy dice, which are d6s. You have a number of these dice equal to twice your proficiency bonus, and they fuel various psionic powers you have, which are detailed below. Some of your powers expend the die they use, and some don’t. You regain all expended Psionic Energy dice when you finish a long rest. In addition, as a bonus action, you can regain one expended Psionic Energy die, but you can’t do so again until you finish a short or long rest.'),
(89, 'Protective Field', 3, 'When you or another creature you can see within 30 feet of you takes damage, you can use your reaction to expend one Psionic Energy die, roll the die, and reduce the damage by the number rolled + your Intelligence modifier (minimum reduction of 1).'),
(89, 'Telekinetic Movement', 3, 'As a bonus action, you can move an object or creature with your mind. You can move one object that isn''t being worn or carried and that weighs no more than 1,000 pounds up to 30 feet in any direction. Alternatively, you can move one willing creature that isn''t being worn or carried and that weighs no more than 1,000 pounds up to 30 feet in any direction.'),
(89, 'Telekinetic Thrust', 7, 'When you hit a creature with a weapon attack, you can expend one Psionic Energy die, roll the die, and push the target up to 15 feet away from you. If the target is pushed into an object or another creature, it takes bludgeoning damage equal to the number rolled on the Psionic Energy die.'),
(89, 'Psi-Powered Leap', 7, 'As a bonus action, you can expend one Psionic Energy die, roll the die, and increase your jump distance by a number of feet equal to 10 times the number rolled. This increase lasts until the end of your turn.'),
(89, 'Guarded Mind', 10, 'You gain resistance to psychic damage. If you are charmed or frightened, you can use your action to end the effect.'),
(89, 'Psionic Strike', 10, 'When you hit a creature with a weapon attack, you can expend one Psionic Energy die, roll the die, and deal extra force damage to the target equal to the number rolled.'),
(89, 'Bulwark', 15, 'When you or another creature you can see within 30 feet of you takes damage, you can use your reaction to expend one Psionic Energy die, roll the die, and reduce the damage by the number rolled + your Intelligence modifier (minimum of 1).'),
(89, 'Telekinetic Master', 18, 'You can cast the Telekinesis spell without expending a spell slot. You can do so a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.');

-- Subclasse: Psychic Warrior (UA) (ID: 90)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(90, 'Telekinetic Hand', 3, 'At 3rd level, you learn the Mage Hand cantrip. You can cast it without components, and you can make the spectral hand invisible. Intelligence is your spellcasting ability for this spell.'),
(90, 'Psionic Armament', 3, 'Starting at 3rd level, you can channel your psychic power to magically augment your prowess. When you finish a long rest, choose whether to augment your defenses or your strikes. The chosen benefit lasts until you finish a long rest.'),
(90, 'Strength of Mind', 7, 'At 7th level, as a bonus action, you can telekinetically lash out at a creature you can see within 20 feet of you. The target must make a Strength saving throw against a DC equal to 8 + your proficiency modifier + your Intelligence modifier. On a failed save, the target takes force damage equal to 2d6 plus your Intelligence modifier and is telekinetically moved 15 feet directly toward or away from you (your choice). On a successful save, it takes half as much damage and isn''t moved. You can use this feature a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(90, 'Telekinetic Bulwark', 10, 'At 10th level, when you take the Attack action, you can forgo one of your attacks to project a bastion of psionic power in a 10-foot radius around yourself. It lasts for 1 minute or until you''re incapacitated. For the duration, you and your allies in that area gain the benefits of half cover and have advantage on Strength saving throws. Once you use this feature, you can''t do so again until you finish a long rest or until after you use your Second Wind feature.'),
(90, 'Agonizing Strikes', 15, 'Starting at 15th level, your attacks can channel psychic agony. When you hit a creature with a weapon attack, you can also deal 2d10 psychic damage to that target and force it to make a Constitution saving throw against a DC equal to 8 + your proficiency bonus + your Intelligence modifier. Unless the save succeeds, the target falls prone, and it suffers disadvantage on ability checks until the end of your next turn. You can use this feature a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(90, 'Psychic Dreadnought', 18, 'At 18th level, the power of your mind suffuses your entire being, making you a nigh-unstoppable force on the battlefield. Using your reaction when you take damage, you can give yourself the following benefits for 1 minute or until you''re incapacitated: At the start of each of your turns, you regain 10 hit points. Your walking speed increases by 10 feet. If you''re prone, you can stand up by spending 5 feet of movement. Once you activate this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Rune Knight (UA) (ID: 91)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(91, 'Bonus Proficiencies', 3, 'When you choose this archetype at 3rd level, you gain proficiency with smith’s tools, and you learn to speak, read, and write Giant.'),
(91, 'Rune Magic', 3, 'You learn how to use runes to enhance your gear. You learn two runes of your choice. Each time you gain a level in this class, you can replace one rune you know with a different one.'),
(91, 'Giant Might', 3, 'You can imbue yourself with the might of giants. As a bonus action, you magically gain benefits for 1 minute: you become Large, have advantage on Strength checks and saves, and your weapon attacks deal an extra 1d6 damage. You can use this feature twice per long rest.'),
(91, 'Defensive Runes', 7, 'You learn to invoke your rune magic to protect your allies. When another creature you can see within 60 feet of you is hit by an attack roll, you can use your reaction to grant a bonus to the creature’s AC against that attack equal to 1 + your Intelligence modifier. You also learn one new rune.'),
(91, 'Great Stature', 10, 'The magic of your runes permanently alters you. You grow 3d4 inches in height. The extra damage from Giant Might increases to 1d8. You also learn one new rune.'),
(91, 'Master of Runes', 15, 'You can invoke each rune you know twice, regaining all uses on a short or long rest. You also learn one new rune.'),
(91, 'Blessing of the All Father', 18, 'You learn how to share your rune magic. When you use your Giant Might feature, you can choose one willing creature within 60 feet to also gain its benefits.');

-- Subclasse: Samurai (UA) (ID: 92)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(92, 'Bonus Proficiency', 3, 'When you choose this archetype at 3rd level, you gain proficiency in one of the following skills of your choice: History, Insight, Performance, or Persuasion. Alternatively, you learn one language of your choice.'),
(92, 'Fighting Spirit', 3, 'As a bonus action on your turn, you can give yourself advantage on all weapon attack rolls until the end of the current turn. When you do so, you also gain temporary hit points equal to 5 + your fighter level. You can use this feature three times, and you regain all expended uses when you finish a long rest.'),
(92, 'Elegant Courtier', 7, 'Your discipline and charm allow you to remain composed in any social situation. You gain proficiency in the Persuasion skill. If you are already proficient in it, you gain proficiency in one of the following skills of your choice: Animal Handling, Insight, Intimidation, or Performance. Your proficiency bonus is doubled for any ability check you make that uses Persuasion. You receive this benefit regardless of the skill proficiency you gain from this feature.'),
(92, 'Tireless Spirit', 10, 'Starting at 10th level, when you roll initiative and have no uses of Fighting Spirit remaining, you regain one use.'),
(92, 'Rapid Strike', 15, 'At 15th level, you learn to trade accuracy for a flurry of blows. When you take the Attack action on your turn and have advantage on an attack roll against one of the targets, you can forgo that advantage to make an additional weapon attack against that target, as part of the same action. You can do so only once per turn.'),
(92, 'Strength Before Death', 18, 'Starting at 18th level, your will to fight can defy even death. If you are reduced to 0 hit points and don''t die outright, you can use your reaction to delay falling unconscious, and you can immediately take an extra turn. While you have 0 hit points during that extra turn, taking damage causes death saving throw failures as normal, and three failures still result in death. When the extra turn ends, you fall unconscious if you still have 0 hit points. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Scout (UA) (ID: 93)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(93, 'Bonus Proficiencies', 3, 'When you choose this archetype at 3rd level, you gain proficiency in three of the following skills of your choice: Acrobatics, Athletics, Investigation, Medicine, Nature, Perception, Stealth, or Survival. You can choose to gain proficiency with thieves’ tools in place of one skill choice.'),
(93, 'Combat Superiority', 3, 'At 3rd level, you gain a set of abilities that are fueled by special dice called superiority dice. You have four superiority dice, which are d8s. You regain all of your expended superiority dice when you finish a long or short rest. You can expend superiority dice to gain a number of different benefits: Survival Superiority, Precision Attack, Scout’s Evasion.'),
(93, 'Natural Explorer', 3, 'At 3rd level, you are particularly familiar with one type of natural environment and are adept at traveling and surviving in such regions. Choose one type of favored terrain. When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled if you are using a skill that you’re proficient in. While traveling for an hour or more in your favored terrain, you gain several benefits.'),
(93, 'Improved Combat Superiority', 10, 'At 10th level, your superiority dice turn into d10s. At 18th level, they turn into d12s.'),
(93, 'Relentless', 15, 'Starting at 15th level, when you roll initiative and have no superiority dice remaining, you regain 1 superiority die.');

-- Subclasse: Sharpshooter (UA) (ID: 94)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(94, 'Steady Aim', 3, 'Beginning when you choose this archetype at 3rd level, your aim becomes deadly. As a bonus action on your turn, you can take careful aim at a creature you can see that is within range of a ranged weapon you’re wielding. Until the end of this turn, your ranged attacks with that weapon gain two benefits against the target: The attacks ignore half and three-quarters cover. On each hit, the weapon deals additional damage to the target equal to 2 + half your fighter level. You can use this feature three times. You regain all expended uses of it when you finish a short or long rest.'),
(94, 'Careful Eyes', 7, 'Starting at 7th level, you excel at picking out hidden enemies and other threats. You can take the Search action as a bonus action. You also gain proficiency in the Perception, Investigation, or Survival skill (choose one).'),
(94, 'Close-Quarters Shooting', 10, 'At 10th level, you learn to handle yourself in close combat. Making a ranged attack roll while within 5 feet of an enemy doesn’t impose disadvantage on your roll. In addition, if you hit a creature within 5 feet of you with a ranged attack on your turn, that creature can’t take reactions until the end of this turn.'),
(94, 'Rapid Strike', 15, 'Starting at 15th level, you learn to trade accuracy for swift strikes. If you have advantage on a weapon attack against a target on your turn, you can forgo that advantage to immediately make an additional weapon attack against the same target as a bonus action.'),
(94, 'Snap Shot', 18, 'Starting at 18th level, you are ever ready to spring into action. If you take the Attack action on your first turn of a combat, you can make one additional ranged weapon attack as part of that action.');
