-- =============================================================================
-- ARTIFICER SUBCLASSES
-- =============================================================================

-- Subclasse: Alchemist (ID: 1)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(1, 'Tool Proficiency', 3, 'When you adopt this specialization at 3rd level, you gain proficiency with alchemist supplies. If you already have this proficiency, you gain proficiency with one other type of artisan tools of your choice.'),
(1, 'Alchemist Spells', 3, 'Starting at 3rd level, you always have certain spells prepared. These spells count as artificer spells for you. 3rd: Healing Word, Ray of Sickness. 5th: Flaming Sphere, Acid Arrow. 9th: Gaseous Form, Mass Healing Word. 13th: Blight, Death Ward. 17th: Cloudkill, Raise Dead.'),
(1, 'Experimental Elixir', 3, 'Beginning at 3rd level, whenever you finish a long rest, you can magically produce an experimental elixir in an empty flask. Roll on the Experimental Elixir table for the elixir effect. You can create additional experimental elixirs by expending spell slots. At 6th level you can make 2 elixirs, and 3 at 15th level.'),
(1, 'Alchemical Savant', 5, 'At 5th level, you have developed masterful command of magical chemicals. Whenever you cast a spell using your alchemist supplies as the spellcasting focus, you gain a bonus to one damage or healing roll equal to your Intelligence modifier (minimum of +1).'),
(1, 'Restorative Reagents', 9, 'Starting at 9th level, whenever a creature drinks an experimental elixir you created, the creature gains temporary hit points equal to 2d6 + your Intelligence modifier. You can cast Lesser Restoration without expending a spell slot, using alchemist supplies as focus.'),
(1, 'Chemical Mastery', 15, 'By 15th level, you have been exposed to so many chemicals that they pose little risk to you, and you can use them to quickly end certain ailments: You gain resistance to acid damage and poison damage, and you are now immune to the poisoned condition. You can cast Greater Restoration and Heal without expending a spell slot, without preparing the spell, and without providing the material component, provided you use alchemist’s supplies as the spellcasting focus. Once you cast either spell with this feature, you can’t cast that spell with it again until you finish a long rest.');

-- Subclasse: Armorer (ID: 2)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(2, 'Tools of the Trade', 3, 'When you adopt this specialization at 3rd level, you gain proficiency with heavy armor. You also gain proficiency with smith tools. If you already have this tool proficiency, you gain proficiency with one other type of artisan tools of your choice.'),
(2, 'Armorer Spells', 3, 'Starting at 3rd level, you always have certain spells prepared. These spells count as artificer spells for you. 3rd: Magic Missile, Thunderwave. 5th: Mirror Image, Shatter. 9th: Hypnotic Pattern, Lightning Bolt. 13th: Fire Shield, Greater Invisibility. 17th: Passwall, Wall of Force.'),
(2, 'Arcane Armor', 3, 'Beginning at 3rd level, your metallurgical pursuits have led to you making armor a conduit for your magic. As an action, you can turn a suit of armor you are wearing into Arcane Armor, provided you have smith tools in hand. The armor lacks Strength requirements, can be used as a spellcasting focus, attaches to you, covers your entire body, and replaces missing limbs.'),
(2, 'Armor Model', 3, 'Beginning at 3rd level, you can customize your Arcane Armor. Choose Guardian (Thunder Gauntlets and Defensive Field) or Infiltrator (Lightning Launcher, Powered Steps, and Dampening Field). You can change the model whenever you finish a short or long rest with smith tools in hand.'),
(2, 'Extra Attack', 5, 'Starting at 5th level, you can attack twice, rather than once, whenever you take the Attack action on your turn.'),
(2, 'Armor Modifications', 9, 'At 9th level, you learn how to use your artificer infusions to specially modify your Arcane Armor. That armor now counts as separate items for the purposes of your Infuse Items feature: armor (the chest piece), boots, helmet, and the special weapon. The maximum number of items can infuse at once increases by 2.'),
(2, 'Perfected Armor', 15, 'At 15th level, your Arcane Armor gains additional benefits based on its model. Guardian: You can use your reaction to pull creatures within 30 feet up to 25 feet toward you. Infiltrator: Creatures taking lightning damage from your Lightning Launcher have disadvantage on attack rolls against you.');

-- Subclasse: Artillerist (ID: 3)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(3, 'Tool Proficiency', 3, 'When you adopt this specialization at 3rd level, you gain proficiency with woodcarver''s tools. If you already have this proficiency, you gain proficiency with one other type of artisan''s tools of your choice.'),
(3, 'Artillerist Spells', 3, 'Starting at 3rd level, you always have certain spells prepared. These spells count as artificer spells for you. 3rd: Shield, Thunderwave. 5th: Scorching Ray, Shatter. 9th: Fireball, Wind Wall. 13th: Ice Storm, Wall of Fire. 17th: Cone of Cold, Wall of Force.'),
(3, 'Eldritch Cannon', 3, 'At 3rd level, you have learned how to create a magical cannon. Using woodcarver tools or smith tools, you can take an action to magically create a Small or Tiny eldritch cannon. You can have only one cannon at a time. The cannon can be Flamethrower (15-foot cone of fire), Force Ballista (ranged spell attack), or Protector (grants temporary hit points).'),
(3, 'Arcane Firearm', 5, 'At 5th level, you know how to turn a wand, staff, or rod into an arcane firearm, a conduit for your destructive spells. When you cast an artificer spell through the firearm, roll a d8, and you gain a bonus to one of the spell damage rolls equal to the number rolled.'),
(3, 'Explosive Cannon', 9, 'Starting at 9th level, every eldritch cannon you create is more destructive: The cannon damage rolls all increase by 1d8. As an action, you can command the cannon to detonate if you are within 60 feet of it, forcing creatures within 20 feet to make a Dexterity saving throw against 3d8 force damage.'),
(3, 'Fortified Position', 15, 'By 15th level, you’re a master at forming well-defended emplacements using Eldritch Cannon: You and your allies have half cover while within 10 feet of a cannon you create with Eldritch Cannon, as a result of a shimmering field of magical protection that the cannon emits. You can now have two cannons at the same time. You can create two with the same action (but not the same spell slot), and you can activate both of them with the same bonus action. You determine whether the cannons are identical to each other or different. You can’t create a third cannon while you have two.');

-- Subclasse: Battle Smith (ID: 4)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(4, 'Tool Proficiency', 3, 'When you adopt this specialization at 3rd level, you gain proficiency with smith tools. If you already have this proficiency, you gain proficiency with one other type of artisan tools of your choice.'),
(4, 'Battle Ready', 3, 'When you reach 3rd level, your combat training and your experiments with magic have paid off in two ways: You gain proficiency with martial weapons. When you attack with a magic weapon, you can use your Intelligence modifier, instead of Strength or Dexterity, for the attack and damage rolls.'),
(4, 'Battle Smith Spells', 3, 'Starting at 3rd level, you always have certain spells prepared. These spells count as artificer spells for you. 3rd: Heroism, Shield. 5th: Branding Smite, Warding Bond. 9th: Aura of Vitality, Conjure Barrage. 13th: Aura of Purity, Fire Shield. 17th: Banishing Smite, Mass Cure Wounds.'),
(4, 'Steel Defender', 3, 'By 3rd level, your tinkering has borne you a faithful companion, a steel defender. It is friendly to you and your companions, and it obeys your commands. In combat, the defender shares your initiative count, but it takes its turn immediately after yours.'),
(4, 'Extra Attack', 5, 'Starting at 5th level, you can attack twice, rather than once, whenever you take the Attack action on your turn.'),
(4, 'Arcane Jolt', 9, 'At 9th level, you have learned new ways to channel arcane energy to harm or heal. When either you hit a target with a magic weapon attack or your steel defender hits a target, you can channel magical energy through the strike to deal an extra 2d6 force damage, or choose a creature within 30 feet to restore 2d6 hit points to it.'),
(4, 'Improved Defender', 15, 'At 15th level, your Arcane Jolt and steel defender become more powerful: The extra damage and the healing of your Arcane Jolt both increase to 4d6. Your steel defender gains a +2 bonus to Armor Class. Whenever your steel defender uses its Deflect Attack, the attacker takes force damage equal to 1d4 + your Intelligence modifier.');

-- Subclasse: Archivist UA (ID: 5)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(5, 'Tools of the Trade', 3, 'By the time you adopt this specialty at 3rd level, you are deeply familiar with employing its tools. You gain proficiency with calligrapher supplies and the forgery kit. If you craft a magic item in the scroll category, it takes you a quarter of the normal time, and it costs you half as much of the usual gold.'),
(5, 'Archivist Spells', 3, 'Starting at 3rd level, you always have certain spells prepared. These spells count as artificer spells for you. 3rd: Comprehend Languages, Dissonant Whispers. 5th: Detect Thoughts, Locate Object. 9th: Hypnotic Pattern, Tongues. 13th: Locate Creature, Phantasmal Killer. 17th: Legend Lore, Modify Memory.'),
(5, 'Artificial Mind', 3, 'At 3rd level, you discover how to awaken a mind inside an object. When you finish a long rest and your calligrapher supplies are with you, you can magically rouse a keen mind within a Tiny, nonmagical object. The object becomes a magic item with telepathic advisor and manifest mind properties.'),
(5, 'Mind Network', 5, 'At 5th level, you have learned how to use your artifices to access minds. While you have your Artificial Mind item, you can communicate telepathically with anyone carrying an item bearing one of your artificer infusions. When you make a psychic damage roll, you gain a bonus equal to your Intelligence modifier.'),
(5, 'Pure Information', 14, 'At 14th level, your Artificial Mind can receive and transmit more information than ever before. When you expend a spell slot to increase Information Overload damage, the target must succeed on an Intelligence saving throw or be stunned. You can teleport to your spectral mind or an item bearing your artificer infusion.');

-- Subclasse: Armorer (UA) (ID: 6)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(6, 'Tool Proficiency', 3, 'When you adopt this specialization at 3rd level, you gain proficiency with heavy armor. You also gain proficiency with smith’s tools. If you already have this tool proficiency, you gain proficiency with one other type of artisan’s tools of your choice.'),
(6, 'Armorer Spells', 3, 'Starting at 3rd level, you always have certain spells prepared. These spells count as artificer spells for you. 3rd: Magic Missile, Shield. 5th: Mirror Image, Shatter. 9th: Hypnotic Pattern, Lightning Bolt. 13th: Fire Shield, Greater Invisibility. 17th: Passwall, Wall of Force.'),
(6, 'Power Armor', 3, 'Beginning at 3rd level, you can turn a suit of heavy armor you are wearing into power armor. You gain benefits like no Strength requirement, using it as a spellcasting focus, and it can replace missing limbs.'),
(6, 'Armor Model', 3, 'Beginning at 3rd level, you can customize your power armor, choosing between Guardian (melee-focused with Thunder Gauntlets and a defensive field) or Infiltrator (stealth-focused with a Lightning Launcher and increased speed). You can change the model on a short or long rest.'),
(6, 'Extra Attack', 5, 'Starting at 5th level, you can attack twice, rather than once, whenever you take the Attack action on your turn.'),
(6, 'Armor Modifications', 9, 'At 9th level, you learn how to specially modify your power armor with infusions. The armor (chest, boots, bracers, weapon) counts as separate items for infusions, and you can infuse 2 additional items that are part of your power armor.'),
(6, 'Perfected Armor', 15, 'At 15th level, your power armor gains additional benefits based on its model. Guardian: Use your reaction to pull a creature up to 30 feet towards you. Infiltrator: Creatures hit by your Lightning Launcher glimmer, giving the next attack against them advantage.');
