-- =============================================================================
-- DRUID SUBCLASSES 
-- =============================================================================

-- Subclasse: Circle of Dreams (ID: 59)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(59, 'Balm of the Summer Court', 2, 'You have a pool of fey energy represented by a number of d6s equal to your druid level. As a bonus action, you can choose an ally you can see within 120 feet of you and spend a number of those dice equal to half your druid level or less. Roll the spent dice and add them together. The target regains a number of hit points equal to the total. The target also gains 1 temporary hit point per die spent. You regain the expended dice when you finish a long rest.'),
(59, 'Hearth of Moonlight and Shadow', 6, 'During a short or long rest, you can invoke the shadowy power of the Gloaming Court to help guard your respite. At the start of the rest, you touch a point in space, and an invisible, 30-foot-radius sphere of magic appears, centered on that point. Total cover blocks the sphere. While within the sphere, you and your allies gain a +5 bonus to Dexterity (Stealth) and Wisdom (Perception) checks, and any light from open flames in the sphere (a campfire, torches, or the like) isn''t visible outside it. The sphere vanishes at the end of the rest or when you leave the sphere.'),
(59, 'Hidden Paths', 10, 'As a bonus action on your turn, you can teleport up to 60 feet to an unoccupied space you can see. Alternatively, you can use your action to teleport one willing creature you touch up to 30 feet to an unoccupied space you can see. You can use this feature a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses of it when you finish a long rest.'),
(59, 'Walker in Dreams', 14, 'When you finish a short rest, you can cast one of the following spells, without expending a spell slot or requiring material components: Dream (with you as the messenger), Scrying, or Teleportation Circle. This use of Teleportation Circle is special. Rather than opening a portal to a permanent teleportation circle, it opens a portal to the last location where you finished a long rest on your current plane of existence. If you haven''t taken a long rest on your current plane, the spell fails but isn''t wasted. Once you use this feature, you can''t use it again until you finish a long rest.');

-- Subclasse: Circle of the Land (ID: 60)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(60, 'Bonus Cantrip', 2, 'When you choose this circle at 2nd level, you learn one additional druid cantrip of your choice. This cantrip doesn’t count against the number of druid cantrips you know.'),
(60, 'Natural Recovery', 2, 'During a short rest, you choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your druid level (rounded up), and none of the slots can be 6th level or higher. You can''t use this feature again until you finish a long rest.'),
(60, 'Circle Spells', 3, 'Your mystical connection to the land infuses you with the ability to cast certain spells. At 3rd, 5th, 7th, and 9th level you gain access to circle spells connected to the land where you became a druid.'),
(60, 'Land''s Stride', 6, 'Moving through nonmagical difficult terrain costs you no extra movement. You can also pass through nonmagical plants without being slowed by them and without taking damage from them if they have thorns, spines, or a similar hazard. In addition, you have advantage on saving throws against plants that are magically created or manipulated to impede movement, such as those created by the Entangle spell.'),
(60, 'Nature''s Ward', 10, 'When you reach 10th level, you can''t be charmed or frightened by elementals or fey, and you are immune to poison and disease.'),
(60, 'Nature''s Sanctuary', 14, 'When you reach 14th level, creatures of the natural world sense your connection to nature and become hesitant to attack you.');

-- Subclasse: Circle of the Moon (ID: 61)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(61, 'Combat Wild Shape', 2, 'You gain the ability to use Wild Shape on your turn as a bonus action, rather than as an action. Additionally, while you are transformed by Wild Shape, you can use a bonus action to expend one spell slot to regain 1d8 hit points per level of the spell slot expended.'),
(61, 'Circle Forms', 2, 'The rites of your circle grant you the ability to transform into more dangerous animal forms. Starting at 2nd level, you can use your Wild Shape to transform into a beast with a challenge rating as high as 1. You ignore the Max. CR column of the Beast Shapes table, but must abide by the other limitations there. Starting at 6th level, you can transform into a beast with a challenge rating as high as your druid level divided by 3, rounded down.'),
(61, 'Primal Strike', 6, 'Your attacks in beast form count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.'),
(61, 'Elemental Wild Shape', 10, 'You can expend two uses of Wild Shape at the same time to transform into an air elemental, an earth elemental, a fire elemental, or a water elemental.');

-- Subclasse: Circle of the Shepherd (ID: 62)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(62, 'Speech of the Woods', 2, 'You gain the ability to converse with beasts and many fey. You learn to speak, read, and write Sylvan. In addition, beasts can understand your speech, and you gain the ability to decipher their noises and motions.'),
(62, 'Spirit Totem', 2, 'As a bonus action, you can magically summon an incorporeal spirit to a point you can see within 60 feet of you. The spirit creates an aura in a 30-foot radius around that point. It counts as neither a creature nor an object, though it has the spectral appearance of the creature it represents. The effect of the spirit’s aura depends on the type of spirit you summon from the options below: Bear Spirit, Hawk Spirit, Unicorn Spirit.'),
(62, 'Mighty Summoner', 6, 'Beasts and fey that you conjure are more resilient than normal. Any beast or fey summoned or created by a spell that you cast gains two benefits: The creature appears with more hit points than normal: 2 extra hit points per Hit Die it has. The damage from its natural weapons is considered magical for the purpose of overcoming immunity and resistance to nonmagical attacks and damage.'),
(62, 'Guardian Spirit', 10, 'When a beast or fey that you summoned or created with a spell ends its turn in your Spirit Totem aura, that creature regains a number of hit points equal to half your druid level.'),
(62, 'Faithful Summons', 14, 'If you are reduced to 0 hit points or are incapacitated against your will, you can immediately gain the benefits of Conjure Animals as if it were cast with a 9th-level spell slot. It summons four beasts of your choice that are challenge rating 2 or lower. The conjured beasts appear within 20 feet of you. If they receive no commands from you, they protect you from harm and attack your foes. The spell lasts for 1 hour, requiring no concentration, or until you dismiss it (no action required). Once you use this feature, you can’t use it again until you finish a long rest.');

-- Subclasse: Circle of Spores (ID: 63)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(63, 'Circle Spells', 2, 'Your symbiotic link to fungi and your ability to tap into the cycle of life and death grants you access to certain spells. At 2nd level, you learn the Chill Touch cantrip. At 3rd, 5th, 7th, and 9th level you gain access to the spells listed for that level in the Circle of Spores Spells table. Once you gain access to one of these spells, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day. If you gain access to a spell that doesn''t appear on the druid spell list, the spell is nonetheless a druid spell for you.'),
(63, 'Halo of Spores', 2, 'You are surrounded by invisible, necrotic spores that are harmless until you unleash them on a creature nearby. When a creature you can see moves into a space within 10 feet of you or starts its turn there, you can use your reaction to deal 1d4 necrotic damage to that creature unless it succeeds on a Constitution saving throw against your spell save DC. The necrotic damage increases to 1d6 at 6th level, 1d8 at 10th level, and 1d10 at 14th level.'),
(63, 'Symbiotic Entity', 2, 'You gain the ability to channel magic into your spores. As an action, you can expend a use of your Wild Shape feature to awaken those spores, rather than transforming into a beast form, and you gain 4 temporary hit points for each level you have in this class. While this feature is active, you gain the following benefits: When you deal your Halo of Spores damage, roll the damage die a second time and add it to the total. Your melee weapon attacks deal an extra 1d6 necrotic damage to any target they hit. These benefits last for 10 minutes, until you lose all these temporary hit points. or until you use your Wild Shape again.'),
(63, 'Fungal Infestation', 6, 'Your spores gain the ability to infest a corpse and animate it. If a beast or a humanoid that is Small or Medium dies within 10 feet of you, you can use your reaction to animate it, causing it to stand up immediately with 1 hit point. The creature uses the Zombie stat block in the Monster Manual. It remains animate for 1 hour, after which time it collapses and dies. In combat, the zombie''s turn comes immediately after yours. It obeys your mental commands, and the only action it can take is the Attack action, making one melee attack. You can use this feature a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses of it when you finish a long rest.'),
(63, 'Spreading Spores', 10, 'You gain the ability to seed an area with deadly spores. As a bonus action while your Symbiotic Entity feature is active, you can hurl spores up to 30 feet away, where they swirl in a 10-foot cube for 1 minute. The spores disappear early if you use this feature again, if you dismiss them as a bonus action, or if your Symbiotic Entity feature is no longer active. Whenever a creature moves into the cube or starts its turn there, that creature takes your Halo of Spores damage, unless the creature succeeds on a Constitution saving throw against your spell save DC. A creature can take this damage no more than once per turn. While the cube of spores persists, you can''t use your Halo of Spores reaction.'),
(63, 'Fungal Body', 14, 'The fungal spores in your body alter you: you can’t be blinded, deafened, frightened, or poisoned, and any critical hit against you counts as a normal hit instead, unless you’re incapacitated.');

-- Subclasse: Circle of Stars (ID: 64)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(64, 'Star Map', 2, 'You''ve created a star map as part of your study of the heavens. The map is a Tiny object and can serve as a spellcasting focus for your druid spells. You decide what form the object takes, or you can determine what it is by rolling on the Star Map table. You can cast the Augury and Guiding Bolt spells without expending a spell slot and without preparing the spell, provided you use the star map as the spellcasting focus. You can cast a spell from the map in this way a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(64, 'Starry Form', 2, 'You gain the ability to harness constellations’ power to alter your form. As an action, you can expend a use of your Wild Shape feature to take on a starry form rather than transforming into a beast. While in your starry form, you retain your game statistics, but your body takes on a luminous, starlike quality; your joints glimmer like stars, and glowing lines connect them as on a star chart. This form sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The form lasts for 10 minutes or until you’re incapacitated. Whenever you assume your starry form, choose which of the following constellations glimmers on your body; your choice gives you certain benefits while in the form: Chalice, Archer, Dragon.'),
(64, 'Full of Stars', 10, 'While your Starry Form feature is active, you become partially incorporeal, giving you resistance to bludgeoning, piercing, and slashing damage.'),
(64, 'Star Flare', 14, 'Your connection to the cosmos allows you to conjure brilliant starlight. As an action, you conjure a burst of light in a 30-foot-radius sphere centered on a point you can see within 120 feet of you. You can immediately teleport each willing creature in the sphere to an unoccupied space within 30 feet of it. Each creature remaining in the sphere must succeed on a Constitution saving throw against your spell save DC or take 4d10 radiant damage and be blinded until the end of your next turn. Once you have used this action, you can’t use it again until you finish a long rest or until you expend a spell slot of 5th level or higher to use it again.');

-- Subclasse: Circle of Wildfire (ID: 65)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(65, 'Circle Spells', 2, 'You have formed a mystical bond with a wildfire spirit, a primal being of creation and destruction. Your link with this spirit grants you access to certain spells. At 2nd level, you learn the Fire Bolt cantrip. When you reach certain levels in this class, you gain access to the spells listed for that level in the Circle of Wildfire Spells table. Once you gain access to one of these spells, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day. If you gain access to a spell that doesn''t appear on the Druid Spell List, the spell is nonetheless a druid spell for you.'),
(65, 'Summon Wildfire', 2, 'You can summon the primal spirit bound to your soul. As an action, you can expend one use of your Wild Shape feature to summon your wildfire spirit, rather than assuming a beast form. The spirit appears in an unoccupied space of your choice you can see within 30 feet of you. Each creature within 10 feet of the spirit (other than you) when it appears must succeed on a Dexterity saving throw against your spell save DC or take 2d10 fire damage. The wildfire spirit is friendly to you and your companions and obeys your commands. You determine the spirit’s appearance. In combat, the wildfire spirit shares your initiative count, but it takes its turn immediately after yours. The only action it takes on its turn is the Dodge action, unless you take a bonus action on your turn to command it to take another action. The wildfire spirit manifests for 1 hour, until it is reduced to 0 hit points, or until you use your Wild Shape again.'),
(65, 'Enhanced Bond', 6, 'The bond with your wildfire spirit enhances your destructive and restorative spells. Whenever you cast a spell that deals fire damage or restores hit points while your wildfire spirit is summoned, roll a d8, and you gain a bonus to one roll of the spell equal to the number rolled. In addition, when you cast a spell with a range other than self, the spell can originate from you or your wildfire spirit.'),
(65, 'Blazing Endurance', 14, 'The bond with your wildfire spirit is exceptionally strong, even fatal blows only fuel your defiance. If you drop to 0 hit points and don’t die outright, you drop to 1 hit point instead and gain temporary hit points equal to five times your druid level, and each creature of your choice within 30 feet of you that you can see takes fire damage equal to 2d10 + your druid level. Once you use this feature, you can’t use it again until you finish a long rest.');

-- Subclasse: Circle of the Primeval (UA) (ID: 66)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(66, 'Keeper of Old', 2, 'Your connection to the mighty primeval behemoths allows you new insight into the ancient world. You gain proficiency in the History skill. When you make an Intelligence (History) check, you can roll a d4 and add the number rolled to the ability check.'),
(66, 'Primeval Companion', 2, 'You can call upon the primeval creature whose spirit is bound to you. As an action, you can expend one use of your Wild Shape feature to summon your primeval companion, rather than assuming a beast form. The companion appears in an unoccupied space of your choice within 30 feet of you.'),
(66, 'Prehistoric Conduit', 6, 'You learn how to channel your magic through your primeval companion. When you cast a spell with a range other than self, the spell can originate from you or your primeval companion.'),
(66, 'Titanic Bond', 10, 'The primeval companion grows to Large size, and when you summon it, you can grant it either a climbing speed or a swimming speed equal to its walking speed. In turn, the primeval companion lends you some of its terrifying might. Once per turn while your primeval companion is summoned, when you hit a creature with an attack or deal damage to a creature you can see with a spell you cast, you can force that creature to make a Wisdom saving throw against your spell save DC; on a failure, the creature is frightened of you until the end of your next turn.'),
(66, 'Scourge of the Ancients', 14, 'You have learned to fully harness the titanic legacy of your companion. As part of the bonus action you use to command your companion, you can expend a spell slot of any level to heighten your primeval companion’s might.');

-- Subclasse: Circle of Stars (UA) (ID: 67)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(67, 'Star Map', 2, 'You''ve created a star map as part of your study of the heavens. The map is a Tiny object and can serve as a spellcasting focus for your druid spells. You decide what form the object takes, or you can determine what it is by rolling on the Star Map table. You can cast the Augury and Guiding Bolt spells without expending a spell slot and without preparing the spell, provided you use the star map as the spellcasting focus. You can cast a spell from the map in this way a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses when you finish a long rest.'),
(67, 'Starry Form', 2, 'You''ve gained the ability to harness constellations’ power to alter your form. As an action, you can expend a use of your Wild Shape feature to take on a starry form rather than transforming into a beast. While in your starry form, you retain your game statistics, but your body takes on a luminous, starlike quality; your joints glimmer like stars, and glowing lines connect them as on a star chart. This form sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The form lasts for 10 minutes. Whenever you assume your starry form, choose which of the following constellations glimmers on your body; your choice gives you certain benefits while in the form: Chalice, Archer, Dragon.'),
(67, 'Full of Stars', 10, 'While your Starry Form feature is active, you become partially incorporeal, giving you resistance to bludgeoning, piercing, and slashing damage.'),
(67, 'Star Flare', 14, 'Your connection to the cosmos allows you to conjure brilliant starlight. As an action, you conjure a burst of light in a 30-foot-radius sphere centered on a point you can see within 120 feet of you. You can immediately teleport each willing creature in the sphere to an unoccupied space within 30 feet of it. Each creature remaining in the sphere must succeed on a Constitution saving throw against your spell save DC or take 4d10 radiant damage and be blinded until the end of your next turn.');

-- Subclasse: Circle of Twilight (UA) (ID: 68)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(68, 'Harvest''s Scythe', 2, 'You learn to unravel and harvest the life energy of other creatures. You have a pool of energy represented by a number of d10s equal to your druid level. When you roll damage for a spell, you can increase that damage by spending dice from the pool. You can spend a number of dice equal to half your druid level or less. Roll the spent dice and add them to the damage as necrotic damage. If you kill one or more hostile creatures with a spell augmented in this way, you or an ally of your choice that you can see within 30 feet of you regains 2 hit points per die spent to increase the spell’s damage, or 5 hit points per die if at least one of the slain creatures was undead. You regain the expended dice when you finish a long rest.'),
(68, 'Speech Beyond the Grave', 6, 'You gain the ability to reach beyond death’s veil in search of knowledge. Using this feature, you can cast Speak with Dead without material components, and you understand what the target of this casting says. It can understand your questions, even if you don’t share a language or it is not intelligent enough to speak. Once you use this feature, you can’t use it again until you finish a short or long rest.'),
(68, 'Watcher at the Threshold', 10, 'You gain resistance to necrotic and radiant damage. In addition, while you aren’t incapacitated, any ally within 30 feet of you has advantage on death saving throws.'),
(68, 'Paths of the Dead', 14, 'Your mastery of death allows you to tread the paths used by ghosts and other spirits. Using this feature, you can cast Etherealness. Once the spell ends, you can’t cast it with this feature again until you finish a short or long rest.');

-- Subclasse: Circle of Wildfire (UA) (ID: 69)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(69, 'Circle Spells', 2, 'You have formed a mystical bond with a wildfire spirit. At 2nd level, you learn the Fire Bolt cantrip. You also gain access to certain spells at the levels specified in the Circle of Wildfire Spells table.'),
(69, 'Summon Wildfire', 2, 'You can summon the primal spirit bound to your soul. As an action, you can expend one use of your Wild Shape feature to summon your wildfire spirit. The spirit appears in an unoccupied space of your choice within 30 feet of you. Each creature within 10 feet of the spirit (other than you) when it appears must succeed on a Dexterity saving throw against your spell save DC or take 2d10 fire damage.'),
(69, 'Enhanced Bond', 6, 'The bond with your wildfire spirit enhances your destructive and restorative spells. Whenever you cast a spell that deals fire damage or restores hit points while your wildfire spirit is summoned, roll a d8, and you gain a bonus to one roll of the spell equal to the number rolled. In addition, when you cast a spell with a range other than self, the spell can originate from you or your wildfire spirit.'),
(69, 'Flames of Life', 10, 'You gain the ability to turn death into flames of vitality. When a Small or larger creature that you can see dies within 30 feet of you or your wildfire spirit, you can use your reaction to cause primal flames to spring from the body. When a creature you can see touches these flames, the creature regains hit points or takes fire damage (your choice) equal to 2d10 + your Wisdom modifier. You can use this feature a number of times equal to your Wisdom modifier.'),
(69, 'Blazing Endurance', 14, 'The bond with your wildfire spirit is exceptionally strong. If you drop to 0 hit points and don’t die outright, you drop to 1 hit point instead and gain temporary hit points equal to five times your druid level, and each creature of your choice within 30 feet of you that you can see takes fire damage equal to 2d10 + your druid level. Once you use this feature, you can’t use it again until you finish a long rest.');

-- Subclasse: Mage of Prismari (UA) (ID: 70)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(70, 'Creative Skills', 1, 'You gain proficiency in two of the following skills of your choice: Acrobatics, Athletics, Nature, or Performance.'),
(70, 'Kinetic Artistry', 1, 'You can Dash as a bonus action. When you take this bonus action, you can choose an additional effect: Boreal Sweep, Scorching Whirl, or Thunderlight Jaunt.'),
(70, 'Favored Medium', 6, 'You have honed your forms of elemental expression to best suit your ideas. Choose one of the following damage types: cold, fire, or lightning. You gain resistance to that damage type. Additionally, when you cast a spell using a spell slot that deals the chosen damage type, you emit a spectacular aura of artistry.'),
(70, 'Focused Expression', 10, 'Honing your talents, you skillfully infuse your motions with even more potent expressions of elemental might. Once per turn when you deal damage to at least one target, you gain an additional effect determined by the damage type chosen for your Favored Medium feature.'),
(70, 'Impeccable Physicality', 14, 'Your relentless dedication and training have instilled an outstanding sense of precision and grace in your art. You gain proficiency in Dexterity saving throws if you do not already have it. Additionally, when you make a Dexterity saving throw, you can treat a d20 roll of a 9 or lower as a 10.');

-- Subclasse: Mage of Witherbloom (UA) (ID: 71)
INSERT INTO subclass_features (subclass_id, feature_name, level, description) VALUES
(71, 'Witherbloom Spells', 1, 'You learn the cantrip Spare the Dying and the 1st level spells Cure Wounds and Inflict Wounds. You learn additional spells when you reach certain levels in this class.'),
(71, 'Essence Tap', 1, 'As a bonus action, you can draw on a reservoir of life essence to empower yourself for 1 minute, choosing between Overgrowth and Withering Strike.'),
(71, 'Witherbloom Brew', 6, 'You gain proficiency with herbalism kits. When you finish a long rest, you can create magical brews with various effects.'),
(71, 'Witherbloom Adept', 10, 'Once per turn when you deal necrotic damage or restore hit points using a spell, one target of the spell takes additional damage or regains additional hit points equal to your proficiency bonus.'),
(71, 'Withering Vortex', 14, 'When you cast a spell using a spell slot that deals necrotic damage, you can drain life energy from one of the targets to heal another creature.');
